-- テーブル用DDL

CREATE TABLE PJTM_PJ_STUB_CONFIG   
(
    STUB_ID                        VARCHAR2(2000) NOT NULL ,
    DATA_KEY                       VARCHAR2(2000) NOT NULL ,
    PROP_NAME                      VARCHAR2(2000) NOT NULL ,
    PROP_VALUE                     VARCHAR2(2000) ,
    DEL_FLG                        CHAR(1) DEFAULT '0' NOT NULL ,
    REG_USR_ID                     NUMBER(10) NOT NULL ,
    REG_PGM_ID                     CHAR(11) NOT NULL ,
    REG_TS                         TIMESTAMP(3) NOT NULL ,
    UPD_USR_ID                     NUMBER(10) NOT NULL ,
    UPD_PGM_ID                     CHAR(11) NOT NULL ,
    UPD_TS                         TIMESTAMP(3) NOT NULL ,
    VER_NO                         NUMBER(10) DEFAULT 0 NOT NULL
);
ALTER TABLE PJTM_PJ_STUB_CONFIG ADD CONSTRAINT PK_PJTM_PJ_STUB_CONFIG PRIMARY KEY (STUB_ID, DATA_KEY, PROP_NAME ) ;

COMMENT ON TABLE PJTM_PJ_STUB_CONFIG IS 'スタブ構成';
COMMENT ON COLUMN PJTM_PJ_STUB_CONFIG.STUB_ID IS 'スタブID';
COMMENT ON COLUMN PJTM_PJ_STUB_CONFIG.DATA_KEY IS 'データキー';
COMMENT ON COLUMN PJTM_PJ_STUB_CONFIG.PROP_NAME IS 'プロパティ名';
COMMENT ON COLUMN PJTM_PJ_STUB_CONFIG.PROP_VALUE IS 'プロパティ値';
COMMENT ON COLUMN PJTM_PJ_STUB_CONFIG.DEL_FLG IS '削除フラグ';
COMMENT ON COLUMN PJTM_PJ_STUB_CONFIG.REG_USR_ID IS '登録ユーザID';
COMMENT ON COLUMN PJTM_PJ_STUB_CONFIG.REG_PGM_ID IS '登録プログラムID';
COMMENT ON COLUMN PJTM_PJ_STUB_CONFIG.REG_TS IS '登録タイムスタンプ';
COMMENT ON COLUMN PJTM_PJ_STUB_CONFIG.UPD_USR_ID IS '更新ユーザID';
COMMENT ON COLUMN PJTM_PJ_STUB_CONFIG.UPD_PGM_ID IS '更新プログラムID';
COMMENT ON COLUMN PJTM_PJ_STUB_CONFIG.UPD_TS IS '更新タイムスタンプ';
COMMENT ON COLUMN PJTM_PJ_STUB_CONFIG.VER_NO IS 'バージョン番号';

-- ユニークインデックス用DDL

-- インデックス用DDL
