PROMPT WBSタスクEVMシミュレーショントラン < PJ_MOD.PJTR_PJ_WBS_TSK_EVM_SIM > シノニム再作成
CREATE OR REPLACE SYNONYM PJ_MOD.PJTR_PJ_WBS_TSK_EVM_SIM
                      FOR PJNAVI.PJTR_PJ_WBS_TSK_EVM_SIM
;
PROMPT WBSタスクEVMトラン < PJ_MOD.PJTR_PJ_WBS_TSK_EVM > シノニム再作成
CREATE OR REPLACE SYNONYM PJ_MOD.PJTR_PJ_WBS_TSK_EVM
                      FOR PJNAVI.PJTR_PJ_WBS_TSK_EVM
;
PROMPT プロジェクトEVMシミュレーショントラン < PJ_MOD.PJTR_PJ_PRJ_EVM_SIM > シノニム再作成
CREATE OR REPLACE SYNONYM PJ_MOD.PJTR_PJ_PRJ_EVM_SIM
                      FOR PJNAVI.PJTR_PJ_PRJ_EVM_SIM
;
PROMPT プロジェクトEVMトラン < PJ_MOD.PJTR_PJ_PRJ_EVM > シノニム再作成
CREATE OR REPLACE SYNONYM PJ_MOD.PJTR_PJ_PRJ_EVM
                      FOR PJNAVI.PJTR_PJ_PRJ_EVM
;