col now_time new_value v_now_time
SELECT TO_CHAR(SYSDATE,'YYYYMMDD_HH24MISS') NOW_TIME FROM DUAL ;
spool c:\spool_&v_now_time..log
set timing on
set echo on

-- WBSタスクEVMシミュレーショントラン
-- 1.新規テーブル作成
CREATE TABLE PJTR_PJ_WBS_TSK_EVM_SIM
(
    TSK_UID                        NUMBER(15) NOT NULL ,
    SIM_TYP                        CHAR(1) NOT NULL ,
    FCT_TAR_DT                     DATE NOT NULL ,
    PRJ_CD                         CHAR(10) NOT NULL ,
    BAC                            NUMBER(10,2) NOT NULL ,
    PV                             NUMBER(10,2) NOT NULL ,
    EV                             NUMBER(10,2) NOT NULL ,
    AC                             NUMBER(10,2) NOT NULL ,
    BAC_PRICE                      NUMBER(12) NOT NULL ,
    PV_PRICE                       NUMBER(12) NOT NULL ,
    EV_PRICE                       NUMBER(12) NOT NULL ,
    AC_PRICE                       NUMBER(12) NOT NULL ,
    AC2_PRICE                      NUMBER(12) ,
    DEL_FLG                        CHAR(1) DEFAULT '0' NOT NULL ,
    REG_USR_ID                     NUMBER(10) NOT NULL ,
    REG_PGM_ID                     CHAR(11) NOT NULL ,
    REG_TS                         TIMESTAMP(3) NOT NULL ,
    UPD_USR_ID                     NUMBER(10) NOT NULL ,
    UPD_PGM_ID                     CHAR(11) NOT NULL ,
    UPD_TS                         TIMESTAMP(3) NOT NULL ,
    VER_NO                         NUMBER(10) DEFAULT 0 NOT NULL
);
ALTER TABLE PJTR_PJ_WBS_TSK_EVM_SIM ADD CONSTRAINT PK_PJTR_PJ_WBS_TSK_EVM_SIM PRIMARY KEY (TSK_UID, SIM_TYP, FCT_TAR_DT ) ;

COMMENT ON TABLE PJTR_PJ_WBS_TSK_EVM_SIM IS 'WBSタスクEVMシミュレーショントラン(ver.1.0)';
COMMENT ON COLUMN PJTR_PJ_WBS_TSK_EVM_SIM.TSK_UID IS 'タスクUID';
COMMENT ON COLUMN PJTR_PJ_WBS_TSK_EVM_SIM.SIM_TYP IS 'シミュレーションタイプ';
COMMENT ON COLUMN PJTR_PJ_WBS_TSK_EVM_SIM.FCT_TAR_DT IS '予測対象日';
COMMENT ON COLUMN PJTR_PJ_WBS_TSK_EVM_SIM.PRJ_CD IS 'プロジェクトコード';
COMMENT ON COLUMN PJTR_PJ_WBS_TSK_EVM_SIM.BAC IS 'BAC';
COMMENT ON COLUMN PJTR_PJ_WBS_TSK_EVM_SIM.PV IS 'PV';
COMMENT ON COLUMN PJTR_PJ_WBS_TSK_EVM_SIM.EV IS 'EV';
COMMENT ON COLUMN PJTR_PJ_WBS_TSK_EVM_SIM.AC IS 'AC';
COMMENT ON COLUMN PJTR_PJ_WBS_TSK_EVM_SIM.BAC_PRICE IS 'BAC額';
COMMENT ON COLUMN PJTR_PJ_WBS_TSK_EVM_SIM.PV_PRICE IS 'PV額';
COMMENT ON COLUMN PJTR_PJ_WBS_TSK_EVM_SIM.EV_PRICE IS 'EV額';
COMMENT ON COLUMN PJTR_PJ_WBS_TSK_EVM_SIM.AC_PRICE IS 'AC額';
COMMENT ON COLUMN PJTR_PJ_WBS_TSK_EVM_SIM.AC2_PRICE IS 'AC2額';
COMMENT ON COLUMN PJTR_PJ_WBS_TSK_EVM_SIM.DEL_FLG IS '削除フラグ';
COMMENT ON COLUMN PJTR_PJ_WBS_TSK_EVM_SIM.REG_USR_ID IS '登録ユーザID';
COMMENT ON COLUMN PJTR_PJ_WBS_TSK_EVM_SIM.REG_PGM_ID IS '登録プログラムID';
COMMENT ON COLUMN PJTR_PJ_WBS_TSK_EVM_SIM.REG_TS IS '登録タイムスタンプ';
COMMENT ON COLUMN PJTR_PJ_WBS_TSK_EVM_SIM.UPD_USR_ID IS '更新ユーザID';
COMMENT ON COLUMN PJTR_PJ_WBS_TSK_EVM_SIM.UPD_PGM_ID IS '更新プログラムID';
COMMENT ON COLUMN PJTR_PJ_WBS_TSK_EVM_SIM.UPD_TS IS '更新タイムスタンプ';
COMMENT ON COLUMN PJTR_PJ_WBS_TSK_EVM_SIM.VER_NO IS 'バージョン番号';

-- ユニークインデックス用DDL

-- インデックス用DDL
CREATE INDEX IX1_PJTR_PJ_WBS_TSK_EVM_SIM ON PJTR_PJ_WBS_TSK_EVM_SIM (
    PRJ_CD 
);


-- WBSタスクEVMトラン
-- 1.新規テーブル作成
CREATE TABLE PJTR_PJ_WBS_TSK_EVM
(
    TSK_UID                        NUMBER(15) NOT NULL ,
    SUM_UNT_SEG                    CHAR(1) NOT NULL ,
    RPT_BSDT                       DATE NOT NULL ,
    PLN_RESRC_FLG                  CHAR(1) NOT NULL ,
    RESRC_EMP_CD                   VARCHAR2(30) NOT NULL ,
    RESRC_SHIP_MNG_NO              CHAR(3) NOT NULL ,
    ENT_CLOSE_DT                   DATE NOT NULL ,
    TSK_CD                         VARCHAR2(30) NOT NULL ,
    TSK_NM                         VARCHAR2(150) NOT NULL ,
    SI_DEAL_CD                     CHAR(10) NOT NULL ,
    PRJ_CD                         CHAR(10) NOT NULL ,
    WBS_ID                         NUMBER(15) NOT NULL ,
    PARENT_TSK_ID                  NUMBER(15) ,
    TSK_TYP                        CHAR(2) NOT NULL ,
    SHIP_TSK_FLG                   CHAR(1) NOT NULL ,
    HDAY_OPE_FLG                   CHAR(1) NOT NULL ,
    ACC_MES_KND_CD                 CHAR(2) NOT NULL ,
    PLN_PROD_QUAL                  NUMBER(10,2) ,
    ACC_MES_KND_PV                 NUMBER(12,4) ,
    THIS_RSLT                      NUMBER(12,4) ,
    THIS_RSLT_REM                  NUMBER(12,4) ,
    STR_PLN_DT                     DATE ,
    END_PLN_DT                     DATE ,
    STR_RSLT_DT                    DATE ,
    END_RSLT_DT                    DATE ,
    SAC                            NUMBER(4) ,
    AT                             NUMBER(4) ,
    BAC                            NUMBER(10,2) NOT NULL ,
    PV                             NUMBER(10,2) NOT NULL ,
    EV                             NUMBER(10,2) NOT NULL ,
    AC                             NUMBER(10,2) NOT NULL ,
    SPI                            NUMBER(6,4) NOT NULL ,
    CPI                            NUMBER(6,4) NOT NULL ,
    EAC                            NUMBER(10,2) NOT NULL ,
    ETC                            NUMBER(10,2) NOT NULL ,
    VAC                            NUMBER(10,2) NOT NULL ,
    SV                             NUMBER(10,2) NOT NULL ,
    CV                             NUMBER(10,2) NOT NULL ,
    BAC_PRICE                      NUMBER(12) NOT NULL ,
    PV_PRICE                       NUMBER(12) NOT NULL ,
    EV_PRICE                       NUMBER(12) NOT NULL ,
    AC_PRICE                       NUMBER(12) NOT NULL ,
    SPI_PRICE                      NUMBER(6,4) NOT NULL ,
    CPI_PRICE                      NUMBER(6,4) NOT NULL ,
    EAC_PRICE                      NUMBER(12) NOT NULL ,
    ETC_PRICE                      NUMBER(12) NOT NULL ,
    VAC_PRICE                      NUMBER(12) NOT NULL ,
    SV_PRICE                       NUMBER(12) NOT NULL ,
    CV_PRICE                       NUMBER(12) NOT NULL ,
    AC2_PRICE                      NUMBER(12) ,
    CPI2_PRICE                     NUMBER(6,4) ,
    EAC2_PRICE                     NUMBER(12) ,
    ETC2_PRICE                     NUMBER(12) ,
    VAC2_PRICE                     NUMBER(12) ,
    CV2_PRICE                      NUMBER(12) ,
    ES                             NUMBER(4) ,
    SPI_T                          NUMBER(6,4) ,
    TEAC                           NUMBER(4) ,
    UNTPRICE                       NUMBER(10) NOT NULL ,
    PLN_ACC_RATE                   NUMBER(6,4) NOT NULL ,
    ACC_RATE                       NUMBER(6,4) NOT NULL ,
    DELAY_DAYS                     NUMBER(4) ,
    FCT_CMP_DT                     DATE ,
    PROD_FIX_SIM_RES_SEG           CHAR(2) NOT NULL ,
    DLVDT_FIX_SIM_RES_SEG          CHAR(2) NOT NULL ,
    DLVDT_FIX_RCV_MNHOUR           NUMBER(10,2) ,
    DLVDT_FIX_RCV_STAF_NUM         NUMBER(4) ,
    DEL_FLG                        CHAR(1) DEFAULT '0' NOT NULL ,
    REG_USR_ID                     NUMBER(10) NOT NULL ,
    REG_PGM_ID                     CHAR(11) NOT NULL ,
    REG_TS                         TIMESTAMP(3) NOT NULL ,
    UPD_USR_ID                     NUMBER(10) NOT NULL ,
    UPD_PGM_ID                     CHAR(11) NOT NULL ,
    UPD_TS                         TIMESTAMP(3) NOT NULL ,
    VER_NO                         NUMBER(10) DEFAULT 0 NOT NULL
);
ALTER TABLE PJTR_PJ_WBS_TSK_EVM ADD CONSTRAINT PK_PJTR_PJ_WBS_TSK_EVM PRIMARY KEY (TSK_UID, SUM_UNT_SEG, RPT_BSDT, PLN_RESRC_FLG, RESRC_EMP_CD, RESRC_SHIP_MNG_NO ) ;

COMMENT ON TABLE PJTR_PJ_WBS_TSK_EVM IS 'WBSタスクEVMトラン(ver.1.0)';
COMMENT ON COLUMN PJTR_PJ_WBS_TSK_EVM.TSK_UID IS 'タスクUID';
COMMENT ON COLUMN PJTR_PJ_WBS_TSK_EVM.SUM_UNT_SEG IS '集計単位区分';
COMMENT ON COLUMN PJTR_PJ_WBS_TSK_EVM.RPT_BSDT IS '報告基準日';
COMMENT ON COLUMN PJTR_PJ_WBS_TSK_EVM.PLN_RESRC_FLG IS '計画リソースフラグ';
COMMENT ON COLUMN PJTR_PJ_WBS_TSK_EVM.RESRC_EMP_CD IS 'リソース従業員コード';
COMMENT ON COLUMN PJTR_PJ_WBS_TSK_EVM.RESRC_SHIP_MNG_NO IS 'リソース発注管理番号';
COMMENT ON COLUMN PJTR_PJ_WBS_TSK_EVM.ENT_CLOSE_DT IS '入力締日';
COMMENT ON COLUMN PJTR_PJ_WBS_TSK_EVM.TSK_CD IS 'タスクコード';
COMMENT ON COLUMN PJTR_PJ_WBS_TSK_EVM.TSK_NM IS 'タスク名';
COMMENT ON COLUMN PJTR_PJ_WBS_TSK_EVM.SI_DEAL_CD IS 'SI案件コード';
COMMENT ON COLUMN PJTR_PJ_WBS_TSK_EVM.PRJ_CD IS 'プロジェクトコード';
COMMENT ON COLUMN PJTR_PJ_WBS_TSK_EVM.WBS_ID IS 'WBS_ID';
COMMENT ON COLUMN PJTR_PJ_WBS_TSK_EVM.PARENT_TSK_ID IS '親タスクID';
COMMENT ON COLUMN PJTR_PJ_WBS_TSK_EVM.TSK_TYP IS 'タスクタイプ';
COMMENT ON COLUMN PJTR_PJ_WBS_TSK_EVM.SHIP_TSK_FLG IS '発注タスクフラグ';
COMMENT ON COLUMN PJTR_PJ_WBS_TSK_EVM.HDAY_OPE_FLG IS '休日稼働フラグ';
COMMENT ON COLUMN PJTR_PJ_WBS_TSK_EVM.ACC_MES_KND_CD IS '達成計測種別コード';
COMMENT ON COLUMN PJTR_PJ_WBS_TSK_EVM.PLN_PROD_QUAL IS '予定成果物量';
COMMENT ON COLUMN PJTR_PJ_WBS_TSK_EVM.ACC_MES_KND_PV IS '達成計測種別PV';
COMMENT ON COLUMN PJTR_PJ_WBS_TSK_EVM.THIS_RSLT IS '今回実績';
COMMENT ON COLUMN PJTR_PJ_WBS_TSK_EVM.THIS_RSLT_REM IS '今回実績残';
COMMENT ON COLUMN PJTR_PJ_WBS_TSK_EVM.STR_PLN_DT IS '開始予定日';
COMMENT ON COLUMN PJTR_PJ_WBS_TSK_EVM.END_PLN_DT IS '終了予定日';
COMMENT ON COLUMN PJTR_PJ_WBS_TSK_EVM.STR_RSLT_DT IS '開始実績日';
COMMENT ON COLUMN PJTR_PJ_WBS_TSK_EVM.END_RSLT_DT IS '終了実績日';
COMMENT ON COLUMN PJTR_PJ_WBS_TSK_EVM.SAC IS 'SAC';
COMMENT ON COLUMN PJTR_PJ_WBS_TSK_EVM.AT IS 'AT';
COMMENT ON COLUMN PJTR_PJ_WBS_TSK_EVM.BAC IS 'BAC';
COMMENT ON COLUMN PJTR_PJ_WBS_TSK_EVM.PV IS 'PV';
COMMENT ON COLUMN PJTR_PJ_WBS_TSK_EVM.EV IS 'EV';
COMMENT ON COLUMN PJTR_PJ_WBS_TSK_EVM.AC IS 'AC';
COMMENT ON COLUMN PJTR_PJ_WBS_TSK_EVM.SPI IS 'SPI';
COMMENT ON COLUMN PJTR_PJ_WBS_TSK_EVM.CPI IS 'CPI';
COMMENT ON COLUMN PJTR_PJ_WBS_TSK_EVM.EAC IS 'EAC';
COMMENT ON COLUMN PJTR_PJ_WBS_TSK_EVM.ETC IS 'ETC';
COMMENT ON COLUMN PJTR_PJ_WBS_TSK_EVM.VAC IS 'VAC';
COMMENT ON COLUMN PJTR_PJ_WBS_TSK_EVM.SV IS 'SV';
COMMENT ON COLUMN PJTR_PJ_WBS_TSK_EVM.CV IS 'CV';
COMMENT ON COLUMN PJTR_PJ_WBS_TSK_EVM.BAC_PRICE IS 'BAC額';
COMMENT ON COLUMN PJTR_PJ_WBS_TSK_EVM.PV_PRICE IS 'PV額';
COMMENT ON COLUMN PJTR_PJ_WBS_TSK_EVM.EV_PRICE IS 'EV額';
COMMENT ON COLUMN PJTR_PJ_WBS_TSK_EVM.AC_PRICE IS 'AC額';
COMMENT ON COLUMN PJTR_PJ_WBS_TSK_EVM.SPI_PRICE IS 'SPI額';
COMMENT ON COLUMN PJTR_PJ_WBS_TSK_EVM.CPI_PRICE IS 'CPI額';
COMMENT ON COLUMN PJTR_PJ_WBS_TSK_EVM.EAC_PRICE IS 'EAC額';
COMMENT ON COLUMN PJTR_PJ_WBS_TSK_EVM.ETC_PRICE IS 'ETC額';
COMMENT ON COLUMN PJTR_PJ_WBS_TSK_EVM.VAC_PRICE IS 'VAC額';
COMMENT ON COLUMN PJTR_PJ_WBS_TSK_EVM.SV_PRICE IS 'SV額';
COMMENT ON COLUMN PJTR_PJ_WBS_TSK_EVM.CV_PRICE IS 'CV額';
COMMENT ON COLUMN PJTR_PJ_WBS_TSK_EVM.AC2_PRICE IS 'AC2額';
COMMENT ON COLUMN PJTR_PJ_WBS_TSK_EVM.CPI2_PRICE IS 'CPI2額';
COMMENT ON COLUMN PJTR_PJ_WBS_TSK_EVM.EAC2_PRICE IS 'EAC2額';
COMMENT ON COLUMN PJTR_PJ_WBS_TSK_EVM.ETC2_PRICE IS 'ETC2額';
COMMENT ON COLUMN PJTR_PJ_WBS_TSK_EVM.VAC2_PRICE IS 'VAC2額';
COMMENT ON COLUMN PJTR_PJ_WBS_TSK_EVM.CV2_PRICE IS 'CV2額';
COMMENT ON COLUMN PJTR_PJ_WBS_TSK_EVM.ES IS 'ES';
COMMENT ON COLUMN PJTR_PJ_WBS_TSK_EVM.SPI_T IS 'SPI（t）';
COMMENT ON COLUMN PJTR_PJ_WBS_TSK_EVM.TEAC IS 'TEAC';
COMMENT ON COLUMN PJTR_PJ_WBS_TSK_EVM.UNTPRICE IS '単価';
COMMENT ON COLUMN PJTR_PJ_WBS_TSK_EVM.PLN_ACC_RATE IS '計画達成率';
COMMENT ON COLUMN PJTR_PJ_WBS_TSK_EVM.ACC_RATE IS '達成率';
COMMENT ON COLUMN PJTR_PJ_WBS_TSK_EVM.DELAY_DAYS IS '遅延日数';
COMMENT ON COLUMN PJTR_PJ_WBS_TSK_EVM.FCT_CMP_DT IS '予測完了日';
COMMENT ON COLUMN PJTR_PJ_WBS_TSK_EVM.PROD_FIX_SIM_RES_SEG IS '生産性FIXシミュレーション結果区分';
COMMENT ON COLUMN PJTR_PJ_WBS_TSK_EVM.DLVDT_FIX_SIM_RES_SEG IS '納期FIXシミュレーション結果区分';
COMMENT ON COLUMN PJTR_PJ_WBS_TSK_EVM.DLVDT_FIX_RCV_MNHOUR IS '納期FIXリカバリ工数';
COMMENT ON COLUMN PJTR_PJ_WBS_TSK_EVM.DLVDT_FIX_RCV_STAF_NUM IS '納期FIXリカバリ要員数';
COMMENT ON COLUMN PJTR_PJ_WBS_TSK_EVM.DEL_FLG IS '削除フラグ';
COMMENT ON COLUMN PJTR_PJ_WBS_TSK_EVM.REG_USR_ID IS '登録ユーザID';
COMMENT ON COLUMN PJTR_PJ_WBS_TSK_EVM.REG_PGM_ID IS '登録プログラムID';
COMMENT ON COLUMN PJTR_PJ_WBS_TSK_EVM.REG_TS IS '登録タイムスタンプ';
COMMENT ON COLUMN PJTR_PJ_WBS_TSK_EVM.UPD_USR_ID IS '更新ユーザID';
COMMENT ON COLUMN PJTR_PJ_WBS_TSK_EVM.UPD_PGM_ID IS '更新プログラムID';
COMMENT ON COLUMN PJTR_PJ_WBS_TSK_EVM.UPD_TS IS '更新タイムスタンプ';
COMMENT ON COLUMN PJTR_PJ_WBS_TSK_EVM.VER_NO IS 'バージョン番号';

-- ユニークインデックス用DDL

-- インデックス用DDL
CREATE INDEX IX1_PJTR_PJ_WBS_TSK_EVM ON PJTR_PJ_WBS_TSK_EVM (
    WBS_ID ,
    RPT_BSDT ,
    SUM_UNT_SEG 
);

CREATE INDEX IX2_PJTR_PJ_WBS_TSK_EVM ON PJTR_PJ_WBS_TSK_EVM (
    PRJ_CD ,
    RPT_BSDT ,
    SUM_UNT_SEG 
);

-- プロジェクトEVMシミュレーショントラン
-- 1.新規テーブル作成
CREATE TABLE PJTR_PJ_PRJ_EVM_SIM
(
    PRJ_CD                         CHAR(10) NOT NULL ,
    SIM_TYP                        CHAR(1) NOT NULL ,
    FCT_TAR_DT                     DATE NOT NULL ,
    BAC                            NUMBER(10,2) NOT NULL ,
    PV                             NUMBER(10,2) NOT NULL ,
    EV                             NUMBER(10,2) NOT NULL ,
    AC                             NUMBER(10,2) NOT NULL ,
    BAC_PRICE                      NUMBER(12) NOT NULL ,
    PV_PRICE                       NUMBER(12) NOT NULL ,
    EV_PRICE                       NUMBER(12) NOT NULL ,
    AC_PRICE                       NUMBER(12) NOT NULL ,
    AC2_PRICE                      NUMBER(12) NOT NULL ,
    DEL_FLG                        CHAR(1) DEFAULT '0' NOT NULL ,
    REG_USR_ID                     NUMBER(10) NOT NULL ,
    REG_PGM_ID                     CHAR(11) NOT NULL ,
    REG_TS                         TIMESTAMP(3) NOT NULL ,
    UPD_USR_ID                     NUMBER(10) NOT NULL ,
    UPD_PGM_ID                     CHAR(11) NOT NULL ,
    UPD_TS                         TIMESTAMP(3) NOT NULL ,
    VER_NO                         NUMBER(10) DEFAULT 0 NOT NULL
);
ALTER TABLE PJTR_PJ_PRJ_EVM_SIM ADD CONSTRAINT PK_PJTR_PJ_PRJ_EVM_SIM PRIMARY KEY (PRJ_CD, SIM_TYP, FCT_TAR_DT ) ;

COMMENT ON TABLE PJTR_PJ_PRJ_EVM_SIM IS 'プロジェクトEVMシミュレーショントラン(ver.1.0)';
COMMENT ON COLUMN PJTR_PJ_PRJ_EVM_SIM.PRJ_CD IS 'プロジェクトコード';
COMMENT ON COLUMN PJTR_PJ_PRJ_EVM_SIM.SIM_TYP IS 'シミュレーションタイプ';
COMMENT ON COLUMN PJTR_PJ_PRJ_EVM_SIM.FCT_TAR_DT IS '予測対象日';
COMMENT ON COLUMN PJTR_PJ_PRJ_EVM_SIM.BAC IS 'BAC';
COMMENT ON COLUMN PJTR_PJ_PRJ_EVM_SIM.PV IS 'PV';
COMMENT ON COLUMN PJTR_PJ_PRJ_EVM_SIM.EV IS 'EV';
COMMENT ON COLUMN PJTR_PJ_PRJ_EVM_SIM.AC IS 'AC';
COMMENT ON COLUMN PJTR_PJ_PRJ_EVM_SIM.BAC_PRICE IS 'BAC額';
COMMENT ON COLUMN PJTR_PJ_PRJ_EVM_SIM.PV_PRICE IS 'PV額';
COMMENT ON COLUMN PJTR_PJ_PRJ_EVM_SIM.EV_PRICE IS 'EV額';
COMMENT ON COLUMN PJTR_PJ_PRJ_EVM_SIM.AC_PRICE IS 'AC額';
COMMENT ON COLUMN PJTR_PJ_PRJ_EVM_SIM.AC2_PRICE IS 'AC2額';
COMMENT ON COLUMN PJTR_PJ_PRJ_EVM_SIM.DEL_FLG IS '削除フラグ';
COMMENT ON COLUMN PJTR_PJ_PRJ_EVM_SIM.REG_USR_ID IS '登録ユーザID';
COMMENT ON COLUMN PJTR_PJ_PRJ_EVM_SIM.REG_PGM_ID IS '登録プログラムID';
COMMENT ON COLUMN PJTR_PJ_PRJ_EVM_SIM.REG_TS IS '登録タイムスタンプ';
COMMENT ON COLUMN PJTR_PJ_PRJ_EVM_SIM.UPD_USR_ID IS '更新ユーザID';
COMMENT ON COLUMN PJTR_PJ_PRJ_EVM_SIM.UPD_PGM_ID IS '更新プログラムID';
COMMENT ON COLUMN PJTR_PJ_PRJ_EVM_SIM.UPD_TS IS '更新タイムスタンプ';
COMMENT ON COLUMN PJTR_PJ_PRJ_EVM_SIM.VER_NO IS 'バージョン番号';

-- プロジェクトEVMトラン
-- 1.新規テーブル作成
CREATE TABLE PJTR_PJ_PRJ_EVM
(
    PRJ_CD                         CHAR(10) NOT NULL ,
    SUM_UNT_SEG                    CHAR(1) NOT NULL ,
    RPT_BSDT                       DATE NOT NULL ,
    PLN_RESRC_FLG                  CHAR(1) NOT NULL ,
    RESRC_EMP_CD                   VARCHAR2(30) NOT NULL ,
    RESRC_SHIP_MNG_NO              CHAR(3) NOT NULL ,
    ENT_CLOSE_DT                   DATE NOT NULL ,
    PRJ_NM                         VARCHAR2(90) NOT NULL ,
    SI_DEAL_CD                     CHAR(10) NOT NULL ,
    HDAY_OPE_FLG                   CHAR(1) NOT NULL ,
    STR_PLN_DT                     DATE ,
    END_PLN_DT                     DATE ,
    STR_RSLT_DT                    DATE ,
    END_RSLT_DT                    DATE ,
    SAC                            NUMBER(4) ,
    AT                             NUMBER(4) ,
    BAC                            NUMBER(10,2) NOT NULL ,
    PV                             NUMBER(10,2) NOT NULL ,
    EV                             NUMBER(10,2) NOT NULL ,
    AC                             NUMBER(10,2) NOT NULL ,
    SPI                            NUMBER(6,4) NOT NULL ,
    CPI                            NUMBER(6,4) NOT NULL ,
    EAC                            NUMBER(10,2) NOT NULL ,
    ETC                            NUMBER(10,2) NOT NULL ,
    VAC                            NUMBER(10,2) NOT NULL ,
    SV                             NUMBER(10,2) NOT NULL ,
    CV                             NUMBER(10,2) NOT NULL ,
    BAC_PRICE                      NUMBER(12) NOT NULL ,
    PV_PRICE                       NUMBER(12) NOT NULL ,
    EV_PRICE                       NUMBER(12) NOT NULL ,
    AC_PRICE                       NUMBER(12) NOT NULL ,
    SPI_PRICE                      NUMBER(6,4) NOT NULL ,
    CPI_PRICE                      NUMBER(6,4) NOT NULL ,
    EAC_PRICE                      NUMBER(12) NOT NULL ,
    ETC_PRICE                      NUMBER(12) NOT NULL ,
    VAC_PRICE                      NUMBER(12) NOT NULL ,
    SV_PRICE                       NUMBER(12) NOT NULL ,
    CV_PRICE                       NUMBER(12) NOT NULL ,
    AC2_PRICE                      NUMBER(12) NOT NULL ,
    CPI2_PRICE                     NUMBER(6,4) NOT NULL ,
    EAC2_PRICE                     NUMBER(12) NOT NULL ,
    ETC2_PRICE                     NUMBER(12) NOT NULL ,
    VAC2_PRICE                     NUMBER(12) NOT NULL ,
    CV2_PRICE                      NUMBER(12) NOT NULL ,
    ES                             NUMBER(4) ,
    SPI_T                          NUMBER(6,4) ,
    TEAC                           NUMBER(4) ,
    UNTPRICE                       NUMBER(10) NOT NULL ,
    PLN_ACC_RATE                   NUMBER(6,4) NOT NULL ,
    ACC_RATE                       NUMBER(6,4) NOT NULL ,
    DELAY_DAYS                     NUMBER(4) ,
    FCT_CMP_DT                     DATE ,
    PROD_FIX_SIM_RES_SEG           CHAR(2) NOT NULL ,
    DLVDT_FIX_SIM_RES_SEG          CHAR(2) NOT NULL ,
    DLVDT_FIX_RCV_MNHOUR           NUMBER(10,2) ,
    DLVDT_FIX_RCV_STAF_NUM         NUMBER(4) ,
    DEL_FLG                        CHAR(1) DEFAULT '0' NOT NULL ,
    REG_USR_ID                     NUMBER(10) NOT NULL ,
    REG_PGM_ID                     CHAR(11) NOT NULL ,
    REG_TS                         TIMESTAMP(3) NOT NULL ,
    UPD_USR_ID                     NUMBER(10) NOT NULL ,
    UPD_PGM_ID                     CHAR(11) NOT NULL ,
    UPD_TS                         TIMESTAMP(3) NOT NULL ,
    VER_NO                         NUMBER(10) DEFAULT 0 NOT NULL
);
ALTER TABLE PJTR_PJ_PRJ_EVM ADD CONSTRAINT PK_PJTR_PJ_PRJ_EVM PRIMARY KEY (PRJ_CD, SUM_UNT_SEG, RPT_BSDT, PLN_RESRC_FLG, RESRC_EMP_CD, RESRC_SHIP_MNG_NO ) ;

COMMENT ON TABLE PJTR_PJ_PRJ_EVM IS 'プロジェクトEVMトラン(ver.1.0)';
COMMENT ON COLUMN PJTR_PJ_PRJ_EVM.PRJ_CD IS 'プロジェクトコード';
COMMENT ON COLUMN PJTR_PJ_PRJ_EVM.SUM_UNT_SEG IS '集計単位区分';
COMMENT ON COLUMN PJTR_PJ_PRJ_EVM.RPT_BSDT IS '報告基準日';
COMMENT ON COLUMN PJTR_PJ_PRJ_EVM.PLN_RESRC_FLG IS '計画リソースフラグ';
COMMENT ON COLUMN PJTR_PJ_PRJ_EVM.RESRC_EMP_CD IS 'リソース従業員コード';
COMMENT ON COLUMN PJTR_PJ_PRJ_EVM.RESRC_SHIP_MNG_NO IS 'リソース発注管理番号';
COMMENT ON COLUMN PJTR_PJ_PRJ_EVM.ENT_CLOSE_DT IS '入力締日';
COMMENT ON COLUMN PJTR_PJ_PRJ_EVM.PRJ_NM IS 'プロジェクト名';
COMMENT ON COLUMN PJTR_PJ_PRJ_EVM.SI_DEAL_CD IS 'SI案件コード';
COMMENT ON COLUMN PJTR_PJ_PRJ_EVM.HDAY_OPE_FLG IS '休日稼働フラグ';
COMMENT ON COLUMN PJTR_PJ_PRJ_EVM.STR_PLN_DT IS '開始予定日';
COMMENT ON COLUMN PJTR_PJ_PRJ_EVM.END_PLN_DT IS '終了予定日';
COMMENT ON COLUMN PJTR_PJ_PRJ_EVM.STR_RSLT_DT IS '開始実績日';
COMMENT ON COLUMN PJTR_PJ_PRJ_EVM.END_RSLT_DT IS '終了実績日';
COMMENT ON COLUMN PJTR_PJ_PRJ_EVM.SAC IS 'SAC';
COMMENT ON COLUMN PJTR_PJ_PRJ_EVM.AT IS 'AT';
COMMENT ON COLUMN PJTR_PJ_PRJ_EVM.BAC IS 'BAC';
COMMENT ON COLUMN PJTR_PJ_PRJ_EVM.PV IS 'PV';
COMMENT ON COLUMN PJTR_PJ_PRJ_EVM.EV IS 'EV';
COMMENT ON COLUMN PJTR_PJ_PRJ_EVM.AC IS 'AC';
COMMENT ON COLUMN PJTR_PJ_PRJ_EVM.SPI IS 'SPI';
COMMENT ON COLUMN PJTR_PJ_PRJ_EVM.CPI IS 'CPI';
COMMENT ON COLUMN PJTR_PJ_PRJ_EVM.EAC IS 'EAC';
COMMENT ON COLUMN PJTR_PJ_PRJ_EVM.ETC IS 'ETC';
COMMENT ON COLUMN PJTR_PJ_PRJ_EVM.VAC IS 'VAC';
COMMENT ON COLUMN PJTR_PJ_PRJ_EVM.SV IS 'SV';
COMMENT ON COLUMN PJTR_PJ_PRJ_EVM.CV IS 'CV';
COMMENT ON COLUMN PJTR_PJ_PRJ_EVM.BAC_PRICE IS 'BAC額';
COMMENT ON COLUMN PJTR_PJ_PRJ_EVM.PV_PRICE IS 'PV額';
COMMENT ON COLUMN PJTR_PJ_PRJ_EVM.EV_PRICE IS 'EV額';
COMMENT ON COLUMN PJTR_PJ_PRJ_EVM.AC_PRICE IS 'AC額';
COMMENT ON COLUMN PJTR_PJ_PRJ_EVM.SPI_PRICE IS 'SPI額';
COMMENT ON COLUMN PJTR_PJ_PRJ_EVM.CPI_PRICE IS 'CPI額';
COMMENT ON COLUMN PJTR_PJ_PRJ_EVM.EAC_PRICE IS 'EAC額';
COMMENT ON COLUMN PJTR_PJ_PRJ_EVM.ETC_PRICE IS 'ETC額';
COMMENT ON COLUMN PJTR_PJ_PRJ_EVM.VAC_PRICE IS 'VAC額';
COMMENT ON COLUMN PJTR_PJ_PRJ_EVM.SV_PRICE IS 'SV額';
COMMENT ON COLUMN PJTR_PJ_PRJ_EVM.CV_PRICE IS 'CV額';
COMMENT ON COLUMN PJTR_PJ_PRJ_EVM.AC2_PRICE IS 'AC2額';
COMMENT ON COLUMN PJTR_PJ_PRJ_EVM.CPI2_PRICE IS 'CPI2額';
COMMENT ON COLUMN PJTR_PJ_PRJ_EVM.EAC2_PRICE IS 'EAC2額';
COMMENT ON COLUMN PJTR_PJ_PRJ_EVM.ETC2_PRICE IS 'ETC2額';
COMMENT ON COLUMN PJTR_PJ_PRJ_EVM.VAC2_PRICE IS 'VAC2額';
COMMENT ON COLUMN PJTR_PJ_PRJ_EVM.CV2_PRICE IS 'CV2額';
COMMENT ON COLUMN PJTR_PJ_PRJ_EVM.ES IS 'ES';
COMMENT ON COLUMN PJTR_PJ_PRJ_EVM.SPI_T IS 'SPI(t)';
COMMENT ON COLUMN PJTR_PJ_PRJ_EVM.TEAC IS 'TEAC';
COMMENT ON COLUMN PJTR_PJ_PRJ_EVM.UNTPRICE IS '単価';
COMMENT ON COLUMN PJTR_PJ_PRJ_EVM.PLN_ACC_RATE IS '計画達成率';
COMMENT ON COLUMN PJTR_PJ_PRJ_EVM.ACC_RATE IS '達成率';
COMMENT ON COLUMN PJTR_PJ_PRJ_EVM.DELAY_DAYS IS '遅延日数';
COMMENT ON COLUMN PJTR_PJ_PRJ_EVM.FCT_CMP_DT IS '予測完了日';
COMMENT ON COLUMN PJTR_PJ_PRJ_EVM.PROD_FIX_SIM_RES_SEG IS '生産性FIXシミュレーション結果区分';
COMMENT ON COLUMN PJTR_PJ_PRJ_EVM.DLVDT_FIX_SIM_RES_SEG IS '納期FIXシミュレーション結果区分';
COMMENT ON COLUMN PJTR_PJ_PRJ_EVM.DLVDT_FIX_RCV_MNHOUR IS '納期FIXリカバリ工数';
COMMENT ON COLUMN PJTR_PJ_PRJ_EVM.DLVDT_FIX_RCV_STAF_NUM IS '納期FIXリカバリ要員数';
COMMENT ON COLUMN PJTR_PJ_PRJ_EVM.DEL_FLG IS '削除フラグ';
COMMENT ON COLUMN PJTR_PJ_PRJ_EVM.REG_USR_ID IS '登録ユーザID';
COMMENT ON COLUMN PJTR_PJ_PRJ_EVM.REG_PGM_ID IS '登録プログラムID';
COMMENT ON COLUMN PJTR_PJ_PRJ_EVM.REG_TS IS '登録タイムスタンプ';
COMMENT ON COLUMN PJTR_PJ_PRJ_EVM.UPD_USR_ID IS '更新ユーザID';
COMMENT ON COLUMN PJTR_PJ_PRJ_EVM.UPD_PGM_ID IS '更新プログラムID';
COMMENT ON COLUMN PJTR_PJ_PRJ_EVM.UPD_TS IS '更新タイムスタンプ';
COMMENT ON COLUMN PJTR_PJ_PRJ_EVM.VER_NO IS 'バージョン番号';

-- ユニークインデックス用DDL

-- インデックス用DDL
CREATE INDEX IX1_PJTR_PJ_PRJ_EVM ON PJTR_PJ_PRJ_EVM (
    PRJ_CD ,
    RPT_BSDT ,
    SUM_UNT_SEG 
);

-- 稼働仮コストトラン
--1. [AC額]⇒[稼働仮コスト]に変更
--2. [入力締日]⇒[処理日]に変更
ALTER TABLE PJTR_PJ_OPE_TMP_CST 
	RENAME COLUMN AC_PRICE TO OPE_TMP_CST;
ALTER TABLE PJTR_PJ_OPE_TMP_CST 
	RENAME COLUMN ENT_CLOSE_DT TO PROC_DT;
COMMENT ON TABLE PJTR_PJ_OPE_TMP_CST IS '稼働仮コストトラン(ver.1.01)';
COMMENT ON COLUMN PJTR_PJ_OPE_TMP_CST.OPE_TMP_CST IS '稼働仮コスト';
COMMENT ON COLUMN PJTR_PJ_OPE_TMP_CST.PROC_DT IS '処理日';

spool off