col now_time new_value v_now_time
SELECT TO_CHAR(SYSDATE,'YYYYMMDD_HH24MISS') NOW_TIME FROM DUAL ;
spool c:\spool_&v_now_time..log
set timing on
set echo on

-- 汎用日付管理マスタ
-- 1.新規テーブル作成
CREATE TABLE PJTM_PJ_HNYO_DT_MNG_MST
(
    HNYO_SEG_CD                    CHAR(3) NOT NULL ,
    HNYO_SEG_DT_CD                 VARCHAR2(30) NOT NULL ,
    MNG_DT                         DATE ,
    DEL_FLG                        CHAR(1) DEFAULT '0' NOT NULL ,
    REG_USR_ID                     NUMBER(10) NOT NULL ,
    REG_PGM_ID                     CHAR(11) NOT NULL ,
    REG_TS                         TIMESTAMP(3) NOT NULL ,
    UPD_USR_ID                     NUMBER(10) NOT NULL ,
    UPD_PGM_ID                     CHAR(11) NOT NULL ,
    UPD_TS                         TIMESTAMP(3) NOT NULL ,
    VER_NO                         NUMBER(10) DEFAULT 0 NOT NULL
);
ALTER TABLE PJTM_PJ_HNYO_DT_MNG_MST ADD CONSTRAINT PK_PJTM_PJ_HNYO_DT_MNG_MST PRIMARY KEY (HNYO_SEG_CD, HNYO_SEG_DT_CD ) ;

COMMENT ON TABLE PJTM_PJ_HNYO_DT_MNG_MST IS '汎用日付管理マスタ(ver.1.0)';
COMMENT ON COLUMN PJTM_PJ_HNYO_DT_MNG_MST.HNYO_SEG_CD IS '汎用区分コード';
COMMENT ON COLUMN PJTM_PJ_HNYO_DT_MNG_MST.HNYO_SEG_DT_CD IS '汎用区分明細コード';
COMMENT ON COLUMN PJTM_PJ_HNYO_DT_MNG_MST.MNG_DT IS '管理日付';
COMMENT ON COLUMN PJTM_PJ_HNYO_DT_MNG_MST.DEL_FLG IS '削除フラグ';
COMMENT ON COLUMN PJTM_PJ_HNYO_DT_MNG_MST.REG_USR_ID IS '登録ユーザID';
COMMENT ON COLUMN PJTM_PJ_HNYO_DT_MNG_MST.REG_PGM_ID IS '登録プログラムID';
COMMENT ON COLUMN PJTM_PJ_HNYO_DT_MNG_MST.REG_TS IS '登録タイムスタンプ';
COMMENT ON COLUMN PJTM_PJ_HNYO_DT_MNG_MST.UPD_USR_ID IS '更新ユーザID';
COMMENT ON COLUMN PJTM_PJ_HNYO_DT_MNG_MST.UPD_PGM_ID IS '更新プログラムID';
COMMENT ON COLUMN PJTM_PJ_HNYO_DT_MNG_MST.UPD_TS IS '更新タイムスタンプ';
COMMENT ON COLUMN PJTM_PJ_HNYO_DT_MNG_MST.VER_NO IS 'バージョン番号';

-- ユニークインデックス用DDL

-- インデックス用DDL

PROMPT 汎用日付管理マスタ < PJ_MOD.PJTM_PJ_HNYO_DT_MNG_MST > シノニム再作成
CREATE OR REPLACE SYNONYM PJ_MOD.PJTM_PJ_HNYO_DT_MNG_MST
                      FOR PJNAVI.PJTM_PJ_HNYO_DT_MNG_MST
;

PROMPT 汎用日付管理マスタ < PJ_REF.PJTM_PJ_HNYO_DT_MNG_MST > シノニム再作成
CREATE OR REPLACE SYNONYM PJ_REF.PJTM_PJ_HNYO_DT_MNG_MST
                      FOR PJNAVI.PJTM_PJ_HNYO_DT_MNG_MST
;


spool off