-- テーブル用DDL
DROP TABLE PJTM_PJ_INOFFICE_RATE CASCADE CONSTRAINTS;

CREATE TABLE PJTM_PJ_INOFFICE_RATE
(
    CONV_SRC_CUR                   VARCHAR2(15) NOT NULL ,
    CONV_DEST_CUR                  VARCHAR2(15) NOT NULL ,
    CONV_DT                        DATE NOT NULL ,
    CONV_RATE                      NUMBER(5,2) NOT NULL ,
    DEL_FLG                        CHAR(1) DEFAULT '0' NOT NULL ,
    REG_USR_ID                     NUMBER(10) NOT NULL ,
    REG_PGM_ID                     CHAR(11) NOT NULL ,
    REG_TS                         TIMESTAMP(3) NOT NULL ,
    UPD_USR_ID                     NUMBER(10) NOT NULL ,
    UPD_PGM_ID                     CHAR(11) NOT NULL ,
    UPD_TS                         TIMESTAMP(3) NOT NULL ,
    VER_NO                         NUMBER(10) DEFAULT 0 NOT NULL
);
ALTER TABLE PJTM_PJ_INOFFICE_RATE ADD CONSTRAINT PK_PJTM_PJ_INOFFICE_RATE PRIMARY KEY (CONV_SRC_CUR, CONV_DEST_CUR, CONV_DT ) ;

COMMENT ON TABLE PJTM_PJ_INOFFICE_RATE IS '社内レートマスタ(ver.0.5)';
COMMENT ON COLUMN PJTM_PJ_INOFFICE_RATE.CONV_SRC_CUR IS '変換元通貨';
COMMENT ON COLUMN PJTM_PJ_INOFFICE_RATE.CONV_DEST_CUR IS '変換先通貨';
COMMENT ON COLUMN PJTM_PJ_INOFFICE_RATE.CONV_DT IS '換算日付';
COMMENT ON COLUMN PJTM_PJ_INOFFICE_RATE.CONV_RATE IS '換算レート';
COMMENT ON COLUMN PJTM_PJ_INOFFICE_RATE.DEL_FLG IS '削除フラグ';
COMMENT ON COLUMN PJTM_PJ_INOFFICE_RATE.REG_USR_ID IS '登録ユーザID';
COMMENT ON COLUMN PJTM_PJ_INOFFICE_RATE.REG_PGM_ID IS '登録プログラムID';
COMMENT ON COLUMN PJTM_PJ_INOFFICE_RATE.REG_TS IS '登録タイムスタンプ';
COMMENT ON COLUMN PJTM_PJ_INOFFICE_RATE.UPD_USR_ID IS '更新ユーザID';
COMMENT ON COLUMN PJTM_PJ_INOFFICE_RATE.UPD_PGM_ID IS '更新プログラムID';
COMMENT ON COLUMN PJTM_PJ_INOFFICE_RATE.UPD_TS IS '更新タイムスタンプ';
COMMENT ON COLUMN PJTM_PJ_INOFFICE_RATE.VER_NO IS 'バージョン番号';

-- ユニークインデックス用DDL

-- インデックス用DDL
CREATE INDEX IX1_PJTM_PJ_INOFFICE_RATE ON PJTM_PJ_INOFFICE_RATE (
    CONV_DEST_CUR ,
    CONV_DT 
);

