-- テーブル用DDL
DROP TABLE PJTM_PJ_PRJ_TPL CASCADE CONSTRAINTS;

CREATE TABLE PJTM_PJ_PRJ_TPL
(
    TPL_ID                         NUMBER(15) NOT NULL ,
    TPL_NO                         VARCHAR2(25) ,
    VLD_STR_DT                     DATE ,
    VLD_END_DT                     DATE ,
    TPL_SNM                        VARCHAR2(90) ,
    TPL_FM_NM                      VARCHAR2(720) ,
    PRJ_TYP_NM                     VARCHAR2(60) ,
    PROP_PRJ_FLG                   CHAR(1) DEFAULT '0' NOT NULL ,
    DEL_FLG                        CHAR(1) DEFAULT '0' NOT NULL ,
    REG_USR_ID                     NUMBER(10) NOT NULL ,
    REG_PGM_ID                     CHAR(11) NOT NULL ,
    REG_TS                         TIMESTAMP(3) NOT NULL ,
    UPD_USR_ID                     NUMBER(10) NOT NULL ,
    UPD_PGM_ID                     CHAR(11) NOT NULL ,
    UPD_TS                         TIMESTAMP(3) NOT NULL ,
    VER_NO                         NUMBER(10) DEFAULT 0 NOT NULL
);
ALTER TABLE PJTM_PJ_PRJ_TPL ADD CONSTRAINT PK_PJTM_PJ_PRJ_TPL PRIMARY KEY (TPL_ID ) ;

COMMENT ON TABLE PJTM_PJ_PRJ_TPL IS 'プロジェクトテンプレートマスタ(ver.0.4)';
COMMENT ON COLUMN PJTM_PJ_PRJ_TPL.TPL_ID IS 'テンプレートID';
COMMENT ON COLUMN PJTM_PJ_PRJ_TPL.TPL_NO IS 'テンプレート番号';
COMMENT ON COLUMN PJTM_PJ_PRJ_TPL.VLD_STR_DT IS '有効開始日';
COMMENT ON COLUMN PJTM_PJ_PRJ_TPL.VLD_END_DT IS '有効終了日';
COMMENT ON COLUMN PJTM_PJ_PRJ_TPL.TPL_SNM IS 'テンプレート略称';
COMMENT ON COLUMN PJTM_PJ_PRJ_TPL.TPL_FM_NM IS 'テンプレート正式名称';
COMMENT ON COLUMN PJTM_PJ_PRJ_TPL.PRJ_TYP_NM IS 'プロジェクトタイプ名称';
COMMENT ON COLUMN PJTM_PJ_PRJ_TPL.PROP_PRJ_FLG IS '提案プロジェクトフラグ';
COMMENT ON COLUMN PJTM_PJ_PRJ_TPL.DEL_FLG IS '削除フラグ';
COMMENT ON COLUMN PJTM_PJ_PRJ_TPL.REG_USR_ID IS '登録ユーザID';
COMMENT ON COLUMN PJTM_PJ_PRJ_TPL.REG_PGM_ID IS '登録プログラムID';
COMMENT ON COLUMN PJTM_PJ_PRJ_TPL.REG_TS IS '登録タイムスタンプ';
COMMENT ON COLUMN PJTM_PJ_PRJ_TPL.UPD_USR_ID IS '更新ユーザID';
COMMENT ON COLUMN PJTM_PJ_PRJ_TPL.UPD_PGM_ID IS '更新プログラムID';
COMMENT ON COLUMN PJTM_PJ_PRJ_TPL.UPD_TS IS '更新タイムスタンプ';
COMMENT ON COLUMN PJTM_PJ_PRJ_TPL.VER_NO IS 'バージョン番号';

-- ユニークインデックス用DDL

-- インデックス用DDL
