-- テーブル用DDL
DROP TABLE PJTM_PJ_HNYO_PMO_ALERT CASCADE CONSTRAINTS;

CREATE TABLE PJTM_PJ_HNYO_PMO_ALERT
(
    HNYO_ALERT_NO                  CHAR(3) NOT NULL ,
    MIN_SCALE                      NUMBER(12) NOT NULL ,
    MAX_SCALE                      NUMBER(12) NOT NULL ,
    BS_PRICE                       NUMBER(12) DEFAULT 0 NOT NULL ,
    WHCO_PMO_ALERT_NOTICE_DEST_1   VARCHAR2(240) NOT NULL ,
    WHCO_PMO_ALERT_NOTICE_DEST_2   VARCHAR2(240) ,
    WHCO_PMO_ALERT_NOTICE_DEST_3   VARCHAR2(240) ,
    DEL_FLG                        CHAR(1) DEFAULT '0' NOT NULL ,
    REG_USR_ID                     NUMBER(10) NOT NULL ,
    REG_PGM_ID                     CHAR(11) NOT NULL ,
    REG_TS                         TIMESTAMP(3) NOT NULL ,
    UPD_USR_ID                     NUMBER(10) NOT NULL ,
    UPD_PGM_ID                     CHAR(11) NOT NULL ,
    UPD_TS                         TIMESTAMP(3) NOT NULL ,
    VER_NO                         NUMBER(10) DEFAULT 0 NOT NULL
);
ALTER TABLE PJTM_PJ_HNYO_PMO_ALERT ADD CONSTRAINT PK_PJTM_PJ_HNYO_PMO_ALERT PRIMARY KEY (HNYO_ALERT_NO, MIN_SCALE, MAX_SCALE ) ;

COMMENT ON TABLE PJTM_PJ_HNYO_PMO_ALERT IS '汎用全社PMOアラート基準マスタ(ver.1.0)';
COMMENT ON COLUMN PJTM_PJ_HNYO_PMO_ALERT.HNYO_ALERT_NO IS '汎用アラート番号';
COMMENT ON COLUMN PJTM_PJ_HNYO_PMO_ALERT.MIN_SCALE IS '下限規模';
COMMENT ON COLUMN PJTM_PJ_HNYO_PMO_ALERT.MAX_SCALE IS '上限規模';
COMMENT ON COLUMN PJTM_PJ_HNYO_PMO_ALERT.BS_PRICE IS '基準金額';
COMMENT ON COLUMN PJTM_PJ_HNYO_PMO_ALERT.WHCO_PMO_ALERT_NOTICE_DEST_1 IS '全社PMOアラート通知先１';
COMMENT ON COLUMN PJTM_PJ_HNYO_PMO_ALERT.WHCO_PMO_ALERT_NOTICE_DEST_2 IS '全社PMOアラート通知先２';
COMMENT ON COLUMN PJTM_PJ_HNYO_PMO_ALERT.WHCO_PMO_ALERT_NOTICE_DEST_3 IS '全社PMOアラート通知先３';
COMMENT ON COLUMN PJTM_PJ_HNYO_PMO_ALERT.DEL_FLG IS '削除フラグ';
COMMENT ON COLUMN PJTM_PJ_HNYO_PMO_ALERT.REG_USR_ID IS '登録ユーザID';
COMMENT ON COLUMN PJTM_PJ_HNYO_PMO_ALERT.REG_PGM_ID IS '登録プログラムID';
COMMENT ON COLUMN PJTM_PJ_HNYO_PMO_ALERT.REG_TS IS '登録タイムスタンプ';
COMMENT ON COLUMN PJTM_PJ_HNYO_PMO_ALERT.UPD_USR_ID IS '更新ユーザID';
COMMENT ON COLUMN PJTM_PJ_HNYO_PMO_ALERT.UPD_PGM_ID IS '更新プログラムID';
COMMENT ON COLUMN PJTM_PJ_HNYO_PMO_ALERT.UPD_TS IS '更新タイムスタンプ';
COMMENT ON COLUMN PJTM_PJ_HNYO_PMO_ALERT.VER_NO IS 'バージョン番号';

-- ユニークインデックス用DDL

-- インデックス用DDL
