-- テーブル用DDL
DROP TABLE PJTM_PJ_DP_UNTPRICE CASCADE CONSTRAINTS;

CREATE TABLE PJTM_PJ_DP_UNTPRICE
(
    EMP_ID                         NUMBER(10) NOT NULL ,
    CONT_STR_DT                    DATE NOT NULL ,
    CONT_END_DT                    DATE NOT NULL ,
    EXP_SELL_TMPRICE               NUMBER(10) NOT NULL ,
    SUPP_ID                        NUMBER(15) NOT NULL ,
    DEL_FLG                        CHAR(1) DEFAULT '0' NOT NULL ,
    REG_USR_ID                     NUMBER(10) NOT NULL ,
    REG_PGM_ID                     CHAR(11) NOT NULL ,
    REG_TS                         TIMESTAMP(3) NOT NULL ,
    UPD_USR_ID                     NUMBER(10) NOT NULL ,
    UPD_PGM_ID                     CHAR(11) NOT NULL ,
    UPD_TS                         TIMESTAMP(3) NOT NULL ,
    VER_NO                         NUMBER(10) DEFAULT 0 NOT NULL
);
ALTER TABLE PJTM_PJ_DP_UNTPRICE ADD CONSTRAINT PK_PJTM_PJ_DP_UNTPRICE PRIMARY KEY (EMP_ID, CONT_STR_DT, CONT_END_DT ) ;

COMMENT ON TABLE PJTM_PJ_DP_UNTPRICE IS '派遣単価マスタ(ver.0.5)';
COMMENT ON COLUMN PJTM_PJ_DP_UNTPRICE.EMP_ID IS '従業員ID';
COMMENT ON COLUMN PJTM_PJ_DP_UNTPRICE.CONT_STR_DT IS '契約開始日';
COMMENT ON COLUMN PJTM_PJ_DP_UNTPRICE.CONT_END_DT IS '契約終了日';
COMMENT ON COLUMN PJTM_PJ_DP_UNTPRICE.EXP_SELL_TMPRICE IS '経費込時間単価';
COMMENT ON COLUMN PJTM_PJ_DP_UNTPRICE.SUPP_ID IS '仕入先ID';
COMMENT ON COLUMN PJTM_PJ_DP_UNTPRICE.DEL_FLG IS '削除フラグ';
COMMENT ON COLUMN PJTM_PJ_DP_UNTPRICE.REG_USR_ID IS '登録ユーザID';
COMMENT ON COLUMN PJTM_PJ_DP_UNTPRICE.REG_PGM_ID IS '登録プログラムID';
COMMENT ON COLUMN PJTM_PJ_DP_UNTPRICE.REG_TS IS '登録タイムスタンプ';
COMMENT ON COLUMN PJTM_PJ_DP_UNTPRICE.UPD_USR_ID IS '更新ユーザID';
COMMENT ON COLUMN PJTM_PJ_DP_UNTPRICE.UPD_PGM_ID IS '更新プログラムID';
COMMENT ON COLUMN PJTM_PJ_DP_UNTPRICE.UPD_TS IS '更新タイムスタンプ';
COMMENT ON COLUMN PJTM_PJ_DP_UNTPRICE.VER_NO IS 'バージョン番号';

-- ユニークインデックス用DDL

-- インデックス用DDL
