-- テーブル用DDL
DROP TABLE PJTM_PJ_PRJ_ALERT CASCADE CONSTRAINTS;

CREATE TABLE PJTM_PJ_PRJ_ALERT
(
    MIN_SCALE                      NUMBER(12) NOT NULL ,
    MAX_SCALE                      NUMBER(12) NOT NULL ,
    SPI                            NUMBER(6,4) DEFAULT 0.0 NOT NULL ,
    CPI                            NUMBER(6,4) DEFAULT 0.0 NOT NULL ,
    DEL_FLG                        CHAR(1) DEFAULT '0' NOT NULL ,
    REG_USR_ID                     NUMBER(10) NOT NULL ,
    REG_PGM_ID                     CHAR(11) NOT NULL ,
    REG_TS                         TIMESTAMP(3) NOT NULL ,
    UPD_USR_ID                     NUMBER(10) NOT NULL ,
    UPD_PGM_ID                     CHAR(11) NOT NULL ,
    UPD_TS                         TIMESTAMP(3) NOT NULL ,
    VER_NO                         NUMBER(10) DEFAULT 0 NOT NULL
);
ALTER TABLE PJTM_PJ_PRJ_ALERT ADD CONSTRAINT PK_PJTM_PJ_PRJ_ALERT PRIMARY KEY (MIN_SCALE, MAX_SCALE ) ;

COMMENT ON TABLE PJTM_PJ_PRJ_ALERT IS 'プロジェクトアラート基準マスタ(ver.0.1)';
COMMENT ON COLUMN PJTM_PJ_PRJ_ALERT.MIN_SCALE IS '下限規模';
COMMENT ON COLUMN PJTM_PJ_PRJ_ALERT.MAX_SCALE IS '上限規模';
COMMENT ON COLUMN PJTM_PJ_PRJ_ALERT.SPI IS 'SPI';
COMMENT ON COLUMN PJTM_PJ_PRJ_ALERT.CPI IS 'CPI';
COMMENT ON COLUMN PJTM_PJ_PRJ_ALERT.DEL_FLG IS '削除フラグ';
COMMENT ON COLUMN PJTM_PJ_PRJ_ALERT.REG_USR_ID IS '登録ユーザID';
COMMENT ON COLUMN PJTM_PJ_PRJ_ALERT.REG_PGM_ID IS '登録プログラムID';
COMMENT ON COLUMN PJTM_PJ_PRJ_ALERT.REG_TS IS '登録タイムスタンプ';
COMMENT ON COLUMN PJTM_PJ_PRJ_ALERT.UPD_USR_ID IS '更新ユーザID';
COMMENT ON COLUMN PJTM_PJ_PRJ_ALERT.UPD_PGM_ID IS '更新プログラムID';
COMMENT ON COLUMN PJTM_PJ_PRJ_ALERT.UPD_TS IS '更新タイムスタンプ';
COMMENT ON COLUMN PJTM_PJ_PRJ_ALERT.VER_NO IS 'バージョン番号';

-- ユニークインデックス用DDL

-- インデックス用DDL
