-- テーブル用DDL
DROP TABLE PJTM_PJ_NEXTMI_TPL_TSK CASCADE CONSTRAINTS;

CREATE TABLE PJTM_PJ_NEXTMI_TPL_TSK
(
    TPL_ID                         NUMBER(15) NOT NULL ,
    NEXTMI_FLNK_TSK_ID             NUMBER(15) NOT NULL ,
    NEXTMI_TSK_NO                  VARCHAR2(38) ,
    NEXTMI_TSK_NM                  VARCHAR2(60) ,
    LEVY_POS_FLG                   CHAR(1) DEFAULT '0' NOT NULL ,
    SV_TYP_CD                      VARCHAR2(30) ,
    TSK_ENF_ORGAN_ID               NUMBER(15) NOT NULL ,
    FLAW_FLG                       CHAR(1) DEFAULT '0' NOT NULL ,
    DEL_FLG                        CHAR(1) DEFAULT '0' NOT NULL ,
    REG_USR_ID                     NUMBER(10) NOT NULL ,
    REG_PGM_ID                     CHAR(11) NOT NULL ,
    REG_TS                         TIMESTAMP(3) NOT NULL ,
    UPD_USR_ID                     NUMBER(10) NOT NULL ,
    UPD_PGM_ID                     CHAR(11) NOT NULL ,
    UPD_TS                         TIMESTAMP(3) NOT NULL ,
    VER_NO                         NUMBER(10) DEFAULT 0 NOT NULL
);
ALTER TABLE PJTM_PJ_NEXTMI_TPL_TSK ADD CONSTRAINT PK_PJTM_PJ_NEXTMI_TPL_TSK PRIMARY KEY (TPL_ID, NEXTMI_FLNK_TSK_ID ) ;

COMMENT ON TABLE PJTM_PJ_NEXTMI_TPL_TSK IS 'Next.MIテンプレートタスクマスタ(ver.0.5)';
COMMENT ON COLUMN PJTM_PJ_NEXTMI_TPL_TSK.TPL_ID IS 'テンプレートID';
COMMENT ON COLUMN PJTM_PJ_NEXTMI_TPL_TSK.NEXTMI_FLNK_TSK_ID IS 'NextMI連携用タスクID';
COMMENT ON COLUMN PJTM_PJ_NEXTMI_TPL_TSK.NEXTMI_TSK_NO IS 'NextMIタスク番号';
COMMENT ON COLUMN PJTM_PJ_NEXTMI_TPL_TSK.NEXTMI_TSK_NM IS 'NextMIタスク名';
COMMENT ON COLUMN PJTM_PJ_NEXTMI_TPL_TSK.LEVY_POS_FLG IS '賦課可能フラグ';
COMMENT ON COLUMN PJTM_PJ_NEXTMI_TPL_TSK.SV_TYP_CD IS 'サービスタイプコード';
COMMENT ON COLUMN PJTM_PJ_NEXTMI_TPL_TSK.TSK_ENF_ORGAN_ID IS 'タスク実施組織ID';
COMMENT ON COLUMN PJTM_PJ_NEXTMI_TPL_TSK.FLAW_FLG IS '瑕疵フラグ';
COMMENT ON COLUMN PJTM_PJ_NEXTMI_TPL_TSK.DEL_FLG IS '削除フラグ';
COMMENT ON COLUMN PJTM_PJ_NEXTMI_TPL_TSK.REG_USR_ID IS '登録ユーザID';
COMMENT ON COLUMN PJTM_PJ_NEXTMI_TPL_TSK.REG_PGM_ID IS '登録プログラムID';
COMMENT ON COLUMN PJTM_PJ_NEXTMI_TPL_TSK.REG_TS IS '登録タイムスタンプ';
COMMENT ON COLUMN PJTM_PJ_NEXTMI_TPL_TSK.UPD_USR_ID IS '更新ユーザID';
COMMENT ON COLUMN PJTM_PJ_NEXTMI_TPL_TSK.UPD_PGM_ID IS '更新プログラムID';
COMMENT ON COLUMN PJTM_PJ_NEXTMI_TPL_TSK.UPD_TS IS '更新タイムスタンプ';
COMMENT ON COLUMN PJTM_PJ_NEXTMI_TPL_TSK.VER_NO IS 'バージョン番号';

-- ユニークインデックス用DDL

-- インデックス用DDL
