-- テーブル用DDL
DROP TABLE PJTM_PJ_ORGAN CASCADE CONSTRAINTS;

CREATE TABLE PJTM_PJ_ORGAN
(
    HR_ORGAN_ID                    NUMBER(15) NOT NULL ,
    VLD_STR_DT                     DATE NOT NULL ,
    VLD_END_DT                     DATE NOT NULL ,
    DEPT_CD                        VARCHAR2(150) NOT NULL ,
    DEPT_NM                        VARCHAR2(225) NOT NULL ,
    DEPT_SNM                       VARCHAR2(225) NOT NULL ,
    ORGAN_CATE_ENBL_FLG            CHAR(1) NOT NULL ,
    ORGAN_LAYER_SEG                NUMBER(10) ,
    BUGU_FLG                       CHAR(1) NOT NULL ,
    HIGH_HR_ORGAN_ID               NUMBER(15) NOT NULL ,
    SLS_COST_TRNS_ENBL_FLG         CHAR(1) NOT NULL ,
    DEL_FLG                        CHAR(1) DEFAULT '0' NOT NULL ,
    REG_USR_ID                     NUMBER(10) NOT NULL ,
    REG_PGM_ID                     CHAR(11) NOT NULL ,
    REG_TS                         TIMESTAMP(3) NOT NULL ,
    UPD_USR_ID                     NUMBER(10) NOT NULL ,
    UPD_PGM_ID                     CHAR(11) NOT NULL ,
    UPD_TS                         TIMESTAMP(3) NOT NULL ,
    VER_NO                         NUMBER(10) DEFAULT 0 NOT NULL
);
ALTER TABLE PJTM_PJ_ORGAN ADD CONSTRAINT PK_PJTM_PJ_ORGAN PRIMARY KEY (HR_ORGAN_ID ) ;

COMMENT ON TABLE PJTM_PJ_ORGAN IS '組織マスタ(ver.0.91)';
COMMENT ON COLUMN PJTM_PJ_ORGAN.HR_ORGAN_ID IS 'HR組織ID';
COMMENT ON COLUMN PJTM_PJ_ORGAN.VLD_STR_DT IS '有効開始日';
COMMENT ON COLUMN PJTM_PJ_ORGAN.VLD_END_DT IS '有効終了日';
COMMENT ON COLUMN PJTM_PJ_ORGAN.DEPT_CD IS '部課コード';
COMMENT ON COLUMN PJTM_PJ_ORGAN.DEPT_NM IS '部課名';
COMMENT ON COLUMN PJTM_PJ_ORGAN.DEPT_SNM IS '部課略称';
COMMENT ON COLUMN PJTM_PJ_ORGAN.ORGAN_CATE_ENBL_FLG IS '組織分類使用可フラグ';
COMMENT ON COLUMN PJTM_PJ_ORGAN.ORGAN_LAYER_SEG IS '組織階層区分';
COMMENT ON COLUMN PJTM_PJ_ORGAN.BUGU_FLG IS '部口フラグ';
COMMENT ON COLUMN PJTM_PJ_ORGAN.HIGH_HR_ORGAN_ID IS '上位HR組織ID';
COMMENT ON COLUMN PJTM_PJ_ORGAN.SLS_COST_TRNS_ENBL_FLG IS '売上原価振替先設定可フラグ';
COMMENT ON COLUMN PJTM_PJ_ORGAN.DEL_FLG IS '削除フラグ';
COMMENT ON COLUMN PJTM_PJ_ORGAN.REG_USR_ID IS '登録ユーザID';
COMMENT ON COLUMN PJTM_PJ_ORGAN.REG_PGM_ID IS '登録プログラムID';
COMMENT ON COLUMN PJTM_PJ_ORGAN.REG_TS IS '登録タイムスタンプ';
COMMENT ON COLUMN PJTM_PJ_ORGAN.UPD_USR_ID IS '更新ユーザID';
COMMENT ON COLUMN PJTM_PJ_ORGAN.UPD_PGM_ID IS '更新プログラムID';
COMMENT ON COLUMN PJTM_PJ_ORGAN.UPD_TS IS '更新タイムスタンプ';
COMMENT ON COLUMN PJTM_PJ_ORGAN.VER_NO IS 'バージョン番号';

-- ユニークインデックス用DDL

-- インデックス用DDL
CREATE INDEX IX1_PJTM_PJ_ORGAN ON PJTM_PJ_ORGAN (
    DEPT_CD ,
    VLD_STR_DT ,
    VLD_END_DT 
);

