-- テーブル用DDL
DROP TABLE PJTM_PJ_SUPP CASCADE CONSTRAINTS;

CREATE TABLE PJTM_PJ_SUPP
(
    SUPP_ID                        NUMBER(15) NOT NULL ,
    SUPP_NO                        VARCHAR2(30) NOT NULL ,
    REG_USE_DISA_FLG               CHAR(1) NOT NULL ,
    SUPP_FM_NM                     VARCHAR2(450) ,
    SUPP_KANA                      VARCHAR2(480) ,
    SUPP_SNM                       VARCHAR2(450) ,
    SUPP_MO_ADDR                   VARCHAR2(450) ,
    DEL_FLG                        CHAR(1) DEFAULT '0' NOT NULL ,
    REG_USR_ID                     NUMBER(10) NOT NULL ,
    REG_PGM_ID                     CHAR(11) NOT NULL ,
    REG_TS                         TIMESTAMP(3) NOT NULL ,
    UPD_USR_ID                     NUMBER(10) NOT NULL ,
    UPD_PGM_ID                     CHAR(11) NOT NULL ,
    UPD_TS                         TIMESTAMP(3) NOT NULL ,
    VER_NO                         NUMBER(10) DEFAULT 0 NOT NULL
);
ALTER TABLE PJTM_PJ_SUPP ADD CONSTRAINT PK_PJTM_PJ_SUPP PRIMARY KEY (SUPP_ID ) ;

COMMENT ON TABLE PJTM_PJ_SUPP IS '仕入先マスタ(ver.0.7)';
COMMENT ON COLUMN PJTM_PJ_SUPP.SUPP_ID IS '仕入先ID';
COMMENT ON COLUMN PJTM_PJ_SUPP.SUPP_NO IS '仕入先番号';
COMMENT ON COLUMN PJTM_PJ_SUPP.REG_USE_DISA_FLG IS '登録使用不可フラグ';
COMMENT ON COLUMN PJTM_PJ_SUPP.SUPP_FM_NM IS '仕入先正式名称';
COMMENT ON COLUMN PJTM_PJ_SUPP.SUPP_KANA IS '仕入先フリガナ';
COMMENT ON COLUMN PJTM_PJ_SUPP.SUPP_SNM IS '仕入先略称';
COMMENT ON COLUMN PJTM_PJ_SUPP.SUPP_MO_ADDR IS '仕入先本社住所';
COMMENT ON COLUMN PJTM_PJ_SUPP.DEL_FLG IS '削除フラグ';
COMMENT ON COLUMN PJTM_PJ_SUPP.REG_USR_ID IS '登録ユーザID';
COMMENT ON COLUMN PJTM_PJ_SUPP.REG_PGM_ID IS '登録プログラムID';
COMMENT ON COLUMN PJTM_PJ_SUPP.REG_TS IS '登録タイムスタンプ';
COMMENT ON COLUMN PJTM_PJ_SUPP.UPD_USR_ID IS '更新ユーザID';
COMMENT ON COLUMN PJTM_PJ_SUPP.UPD_PGM_ID IS '更新プログラムID';
COMMENT ON COLUMN PJTM_PJ_SUPP.UPD_TS IS '更新タイムスタンプ';
COMMENT ON COLUMN PJTM_PJ_SUPP.VER_NO IS 'バージョン番号';

-- ユニークインデックス用DDL

-- インデックス用DDL
CREATE INDEX IX1_PJTM_PJ_SUPP ON PJTM_PJ_SUPP (
    SUPP_NO 
);

