-- テーブル用DDL
DROP TABLE PJTM_PJ_SPD_TYP_MAP CASCADE CONSTRAINTS;

CREATE TABLE PJTM_PJ_SPD_TYP_MAP
(
    TPL_ID                         NUMBER(15) NOT NULL ,
    SPD_TYP_ID                     NUMBER(15) NOT NULL ,
    FBS_TSK_SEG                    CHAR(1) DEFAULT '0' NOT NULL ,
    BILL_POS_FLG                   CHAR(1) DEFAULT '0' NOT NULL ,
    DEL_FLG                        CHAR(1) DEFAULT '0' NOT NULL ,
    REG_USR_ID                     NUMBER(10) NOT NULL ,
    REG_PGM_ID                     CHAR(11) NOT NULL ,
    REG_TS                         TIMESTAMP(3) NOT NULL ,
    UPD_USR_ID                     NUMBER(10) NOT NULL ,
    UPD_PGM_ID                     CHAR(11) NOT NULL ,
    UPD_TS                         TIMESTAMP(3) NOT NULL ,
    VER_NO                         NUMBER(10) DEFAULT 0 NOT NULL
);
ALTER TABLE PJTM_PJ_SPD_TYP_MAP ADD CONSTRAINT PK_PJTM_PJ_SPD_TYP_MAP PRIMARY KEY (TPL_ID, SPD_TYP_ID ) ;

COMMENT ON TABLE PJTM_PJ_SPD_TYP_MAP IS '支出タイプマッピングマスタ(ver.0.3)';
COMMENT ON COLUMN PJTM_PJ_SPD_TYP_MAP.TPL_ID IS 'テンプレートID';
COMMENT ON COLUMN PJTM_PJ_SPD_TYP_MAP.SPD_TYP_ID IS '支出タイプID';
COMMENT ON COLUMN PJTM_PJ_SPD_TYP_MAP.FBS_TSK_SEG IS 'FBSタスク区分';
COMMENT ON COLUMN PJTM_PJ_SPD_TYP_MAP.BILL_POS_FLG IS '請求可能フラグ';
COMMENT ON COLUMN PJTM_PJ_SPD_TYP_MAP.DEL_FLG IS '削除フラグ';
COMMENT ON COLUMN PJTM_PJ_SPD_TYP_MAP.REG_USR_ID IS '登録ユーザID';
COMMENT ON COLUMN PJTM_PJ_SPD_TYP_MAP.REG_PGM_ID IS '登録プログラムID';
COMMENT ON COLUMN PJTM_PJ_SPD_TYP_MAP.REG_TS IS '登録タイムスタンプ';
COMMENT ON COLUMN PJTM_PJ_SPD_TYP_MAP.UPD_USR_ID IS '更新ユーザID';
COMMENT ON COLUMN PJTM_PJ_SPD_TYP_MAP.UPD_PGM_ID IS '更新プログラムID';
COMMENT ON COLUMN PJTM_PJ_SPD_TYP_MAP.UPD_TS IS '更新タイムスタンプ';
COMMENT ON COLUMN PJTM_PJ_SPD_TYP_MAP.VER_NO IS 'バージョン番号';

-- ユニークインデックス用DDL

-- インデックス用DDL
