-- テーブル用DDL
DROP TABLE PJTM_PJ_EMP CASCADE CONSTRAINTS;

CREATE TABLE PJTM_PJ_EMP
(
    EMP_ID                         NUMBER(10) NOT NULL ,
    VLD_STR_DT                     DATE NOT NULL ,
    VLD_END_DT                     DATE NOT NULL ,
    EMP_CD                         VARCHAR2(30) NOT NULL ,
    NAME                           VARCHAR2(225) NOT NULL ,
    NAME_KANA                      VARCHAR2(225) NOT NULL ,
    EMP_TYP_SEG                    NUMBER(15) NOT NULL ,
    PSNL_SYS_STF_SEG               VARCHAR2(150) ,
    EMP_TEL_NO                     VARCHAR2(45) ,
    EMP_EMAIL                      VARCHAR2(240) ,
    DEL_FLG                        CHAR(1) DEFAULT '0' NOT NULL ,
    REG_USR_ID                     NUMBER(10) NOT NULL ,
    REG_PGM_ID                     CHAR(11) NOT NULL ,
    REG_TS                         TIMESTAMP(3) NOT NULL ,
    UPD_USR_ID                     NUMBER(10) NOT NULL ,
    UPD_PGM_ID                     CHAR(11) NOT NULL ,
    UPD_TS                         TIMESTAMP(3) NOT NULL ,
    VER_NO                         NUMBER(10) DEFAULT 0 NOT NULL
);
ALTER TABLE PJTM_PJ_EMP ADD CONSTRAINT PK_PJTM_PJ_EMP PRIMARY KEY (EMP_ID, VLD_STR_DT, VLD_END_DT ) ;

COMMENT ON TABLE PJTM_PJ_EMP IS '従業員マスタ(ver.0.7)';
COMMENT ON COLUMN PJTM_PJ_EMP.EMP_ID IS '従業員ID';
COMMENT ON COLUMN PJTM_PJ_EMP.VLD_STR_DT IS '有効開始日';
COMMENT ON COLUMN PJTM_PJ_EMP.VLD_END_DT IS '有効終了日';
COMMENT ON COLUMN PJTM_PJ_EMP.EMP_CD IS '従業員コード';
COMMENT ON COLUMN PJTM_PJ_EMP.NAME IS '氏名';
COMMENT ON COLUMN PJTM_PJ_EMP.NAME_KANA IS '氏名カナ';
COMMENT ON COLUMN PJTM_PJ_EMP.EMP_TYP_SEG IS '従業員タイプ区分';
COMMENT ON COLUMN PJTM_PJ_EMP.PSNL_SYS_STF_SEG IS '人事システム社員区分';
COMMENT ON COLUMN PJTM_PJ_EMP.EMP_TEL_NO IS '従業員電話番号';
COMMENT ON COLUMN PJTM_PJ_EMP.EMP_EMAIL IS '従業員メールアドレス';
COMMENT ON COLUMN PJTM_PJ_EMP.DEL_FLG IS '削除フラグ';
COMMENT ON COLUMN PJTM_PJ_EMP.REG_USR_ID IS '登録ユーザID';
COMMENT ON COLUMN PJTM_PJ_EMP.REG_PGM_ID IS '登録プログラムID';
COMMENT ON COLUMN PJTM_PJ_EMP.REG_TS IS '登録タイムスタンプ';
COMMENT ON COLUMN PJTM_PJ_EMP.UPD_USR_ID IS '更新ユーザID';
COMMENT ON COLUMN PJTM_PJ_EMP.UPD_PGM_ID IS '更新プログラムID';
COMMENT ON COLUMN PJTM_PJ_EMP.UPD_TS IS '更新タイムスタンプ';
COMMENT ON COLUMN PJTM_PJ_EMP.VER_NO IS 'バージョン番号';

-- ユニークインデックス用DDL

-- インデックス用DDL
CREATE INDEX IX1_PJTM_PJ_EMP ON PJTM_PJ_EMP (
    VLD_STR_DT ,
    VLD_END_DT 
);

CREATE INDEX IX2_PJTM_PJ_EMP ON PJTM_PJ_EMP (
    EMP_CD 
);

