-- テーブル用DDL
DROP TABLE PJTM_PJ_SECT_GD_UNTPRICE CASCADE CONSTRAINTS;

CREATE TABLE PJTM_PJ_SECT_GD_UNTPRICE
(
    HR_ORGAN_ID                    NUMBER(15) NOT NULL ,
    PST_ID                         NUMBER(15) NOT NULL ,
    VLD_STR_DT                     DATE NOT NULL ,
    VLD_END_DT                     DATE NOT NULL ,
    EXP_SELL_TMPRICE               NUMBER(10) NOT NULL ,
    RATE_PLN_LST_NM                VARCHAR2(60) NOT NULL ,
    RATE_PLN_LST_PST_NM            VARCHAR2(1050) NOT NULL ,
    DP_GD_UNTPRICE_FLG             CHAR(1) DEFAULT '0' NOT NULL ,
    DEL_FLG                        CHAR(1) DEFAULT '0' NOT NULL ,
    REG_USR_ID                     NUMBER(10) NOT NULL ,
    REG_PGM_ID                     CHAR(11) NOT NULL ,
    REG_TS                         TIMESTAMP(3) NOT NULL ,
    UPD_USR_ID                     NUMBER(10) NOT NULL ,
    UPD_PGM_ID                     CHAR(11) NOT NULL ,
    UPD_TS                         TIMESTAMP(3) NOT NULL ,
    VER_NO                         NUMBER(10) DEFAULT 0 NOT NULL
);
ALTER TABLE PJTM_PJ_SECT_GD_UNTPRICE ADD CONSTRAINT PK_PJTM_PJ_SECT_GD_UNTPRICE PRIMARY KEY (HR_ORGAN_ID, PST_ID, VLD_STR_DT, VLD_END_DT ) ;

COMMENT ON TABLE PJTM_PJ_SECT_GD_UNTPRICE IS '部門別グレード別単価マスタ(ver.0.6)';
COMMENT ON COLUMN PJTM_PJ_SECT_GD_UNTPRICE.HR_ORGAN_ID IS 'HR組織ID';
COMMENT ON COLUMN PJTM_PJ_SECT_GD_UNTPRICE.PST_ID IS '役職ID';
COMMENT ON COLUMN PJTM_PJ_SECT_GD_UNTPRICE.VLD_STR_DT IS '有効開始日';
COMMENT ON COLUMN PJTM_PJ_SECT_GD_UNTPRICE.VLD_END_DT IS '有効終了日';
COMMENT ON COLUMN PJTM_PJ_SECT_GD_UNTPRICE.EXP_SELL_TMPRICE IS '経費込時間単価';
COMMENT ON COLUMN PJTM_PJ_SECT_GD_UNTPRICE.RATE_PLN_LST_NM IS 'レート予定表名';
COMMENT ON COLUMN PJTM_PJ_SECT_GD_UNTPRICE.RATE_PLN_LST_PST_NM IS 'レート予定表役職名';
COMMENT ON COLUMN PJTM_PJ_SECT_GD_UNTPRICE.DP_GD_UNTPRICE_FLG IS '派遣グレード単価フラグ';
COMMENT ON COLUMN PJTM_PJ_SECT_GD_UNTPRICE.DEL_FLG IS '削除フラグ';
COMMENT ON COLUMN PJTM_PJ_SECT_GD_UNTPRICE.REG_USR_ID IS '登録ユーザID';
COMMENT ON COLUMN PJTM_PJ_SECT_GD_UNTPRICE.REG_PGM_ID IS '登録プログラムID';
COMMENT ON COLUMN PJTM_PJ_SECT_GD_UNTPRICE.REG_TS IS '登録タイムスタンプ';
COMMENT ON COLUMN PJTM_PJ_SECT_GD_UNTPRICE.UPD_USR_ID IS '更新ユーザID';
COMMENT ON COLUMN PJTM_PJ_SECT_GD_UNTPRICE.UPD_PGM_ID IS '更新プログラムID';
COMMENT ON COLUMN PJTM_PJ_SECT_GD_UNTPRICE.UPD_TS IS '更新タイムスタンプ';
COMMENT ON COLUMN PJTM_PJ_SECT_GD_UNTPRICE.VER_NO IS 'バージョン番号';

-- ユニークインデックス用DDL

-- インデックス用DDL
