-- テーブル用DDL
DROP TABLE PJTM_PJ_DTCL_INFO CASCADE CONSTRAINTS;

CREATE TABLE PJTM_PJ_DTCL_INFO
(
    SI_DEAL_SCALE                  NUMBER(12) NOT NULL ,
    SAVE_DAYS                      NUMBER(4) NOT NULL ,
    DEL_FLG                        CHAR(1) DEFAULT '0' NOT NULL ,
    REG_USR_ID                     NUMBER(10) NOT NULL ,
    REG_PGM_ID                     CHAR(11) NOT NULL ,
    REG_TS                         TIMESTAMP(3) NOT NULL ,
    UPD_USR_ID                     NUMBER(10) NOT NULL ,
    UPD_PGM_ID                     CHAR(11) NOT NULL ,
    UPD_TS                         TIMESTAMP(3) NOT NULL ,
    VER_NO                         NUMBER(10) DEFAULT 0 NOT NULL
);
ALTER TABLE PJTM_PJ_DTCL_INFO ADD CONSTRAINT PK_PJTM_PJ_DTCL_INFO PRIMARY KEY (SI_DEAL_SCALE ) ;

COMMENT ON TABLE PJTM_PJ_DTCL_INFO IS 'データクリーニング情報マスタ(ver.0.2)';
COMMENT ON COLUMN PJTM_PJ_DTCL_INFO.SI_DEAL_SCALE IS 'SI案件規模';
COMMENT ON COLUMN PJTM_PJ_DTCL_INFO.SAVE_DAYS IS '保存日数';
COMMENT ON COLUMN PJTM_PJ_DTCL_INFO.DEL_FLG IS '削除フラグ';
COMMENT ON COLUMN PJTM_PJ_DTCL_INFO.REG_USR_ID IS '登録ユーザID';
COMMENT ON COLUMN PJTM_PJ_DTCL_INFO.REG_PGM_ID IS '登録プログラムID';
COMMENT ON COLUMN PJTM_PJ_DTCL_INFO.REG_TS IS '登録タイムスタンプ';
COMMENT ON COLUMN PJTM_PJ_DTCL_INFO.UPD_USR_ID IS '更新ユーザID';
COMMENT ON COLUMN PJTM_PJ_DTCL_INFO.UPD_PGM_ID IS '更新プログラムID';
COMMENT ON COLUMN PJTM_PJ_DTCL_INFO.UPD_TS IS '更新タイムスタンプ';
COMMENT ON COLUMN PJTM_PJ_DTCL_INFO.VER_NO IS 'バージョン番号';

-- ユニークインデックス用DDL

-- インデックス用DDL
