-- テーブル用DDL
DROP TABLE PJTM_PJ_PA_FORM_SEG CASCADE CONSTRAINTS;

CREATE TABLE PJTM_PJ_PA_FORM_SEG
(
    TPL_ID                         NUMBER(15) NOT NULL ,
    PA_FORM_SEG                    VARCHAR2(90) NOT NULL ,
    PA_FORM_SEG_NM                 VARCHAR2(375) ,
    PROG_BS_TAR_FLG                CHAR(1) DEFAULT '0' NOT NULL ,
    REG_USE_DISA_FLG               CHAR(1) ,
    ITEM_NM                        VARCHAR2(315) ,
    ITEM_DT_NM                     VARCHAR2(360) ,
    DEL_FLG                        CHAR(1) DEFAULT '0' NOT NULL ,
    REG_USR_ID                     NUMBER(10) NOT NULL ,
    REG_PGM_ID                     CHAR(11) NOT NULL ,
    REG_TS                         TIMESTAMP(3) NOT NULL ,
    UPD_USR_ID                     NUMBER(10) NOT NULL ,
    UPD_PGM_ID                     CHAR(11) NOT NULL ,
    UPD_TS                         TIMESTAMP(3) NOT NULL ,
    VER_NO                         NUMBER(10) DEFAULT 0 NOT NULL
);
ALTER TABLE PJTM_PJ_PA_FORM_SEG ADD CONSTRAINT PK_PJTM_PJ_PA_FORM_SEG PRIMARY KEY (TPL_ID, PA_FORM_SEG ) ;

COMMENT ON TABLE PJTM_PJ_PA_FORM_SEG IS 'PA形態別区分マスタ(ver.0.7)';
COMMENT ON COLUMN PJTM_PJ_PA_FORM_SEG.TPL_ID IS 'テンプレートID';
COMMENT ON COLUMN PJTM_PJ_PA_FORM_SEG.PA_FORM_SEG IS 'PA形態別区分';
COMMENT ON COLUMN PJTM_PJ_PA_FORM_SEG.PA_FORM_SEG_NM IS 'PA形態別区分名称';
COMMENT ON COLUMN PJTM_PJ_PA_FORM_SEG.PROG_BS_TAR_FLG IS '進行基準対象フラグ';
COMMENT ON COLUMN PJTM_PJ_PA_FORM_SEG.REG_USE_DISA_FLG IS '登録使用不可フラグ';
COMMENT ON COLUMN PJTM_PJ_PA_FORM_SEG.ITEM_NM IS '品目名';
COMMENT ON COLUMN PJTM_PJ_PA_FORM_SEG.ITEM_DT_NM IS '品目詳細名';
COMMENT ON COLUMN PJTM_PJ_PA_FORM_SEG.DEL_FLG IS '削除フラグ';
COMMENT ON COLUMN PJTM_PJ_PA_FORM_SEG.REG_USR_ID IS '登録ユーザID';
COMMENT ON COLUMN PJTM_PJ_PA_FORM_SEG.REG_PGM_ID IS '登録プログラムID';
COMMENT ON COLUMN PJTM_PJ_PA_FORM_SEG.REG_TS IS '登録タイムスタンプ';
COMMENT ON COLUMN PJTM_PJ_PA_FORM_SEG.UPD_USR_ID IS '更新ユーザID';
COMMENT ON COLUMN PJTM_PJ_PA_FORM_SEG.UPD_PGM_ID IS '更新プログラムID';
COMMENT ON COLUMN PJTM_PJ_PA_FORM_SEG.UPD_TS IS '更新タイムスタンプ';
COMMENT ON COLUMN PJTM_PJ_PA_FORM_SEG.VER_NO IS 'バージョン番号';

-- ユニークインデックス用DDL

-- インデックス用DDL
