-- テーブル用DDL
DROP TABLE PJTM_PJ_BIZDAY_CAL CASCADE CONSTRAINTS;

CREATE TABLE PJTM_PJ_BIZDAY_CAL
(
    CAL_DT                         DATE NOT NULL ,
    BIZDAY_SN                      NUMBER(15) ,
    NEXT_BIZDAY_SN                 NUMBER(15) NOT NULL ,
    BF_BIZDAY_SN                   NUMBER(15) NOT NULL ,
    NEXT_BIZDAY_DT                 DATE NOT NULL ,
    BF_BIZDAY_DT                   DATE NOT NULL ,
    DEL_FLG                        CHAR(1) DEFAULT '0' NOT NULL ,
    REG_USR_ID                     NUMBER(10) NOT NULL ,
    REG_PGM_ID                     CHAR(11) NOT NULL ,
    REG_TS                         TIMESTAMP(3) NOT NULL ,
    UPD_USR_ID                     NUMBER(10) NOT NULL ,
    UPD_PGM_ID                     CHAR(11) NOT NULL ,
    UPD_TS                         TIMESTAMP(3) NOT NULL ,
    VER_NO                         NUMBER(10) DEFAULT 0 NOT NULL
);
ALTER TABLE PJTM_PJ_BIZDAY_CAL ADD CONSTRAINT PK_PJTM_PJ_BIZDAY_CAL PRIMARY KEY (CAL_DT ) ;

COMMENT ON TABLE PJTM_PJ_BIZDAY_CAL IS '営業日カレンダーマスタ(ver.0.4)';
COMMENT ON COLUMN PJTM_PJ_BIZDAY_CAL.CAL_DT IS 'カレンダー日付';
COMMENT ON COLUMN PJTM_PJ_BIZDAY_CAL.BIZDAY_SN IS '営業日通番';
COMMENT ON COLUMN PJTM_PJ_BIZDAY_CAL.NEXT_BIZDAY_SN IS '翌営業日通番';
COMMENT ON COLUMN PJTM_PJ_BIZDAY_CAL.BF_BIZDAY_SN IS '前営業日通番';
COMMENT ON COLUMN PJTM_PJ_BIZDAY_CAL.NEXT_BIZDAY_DT IS '翌営業日日付';
COMMENT ON COLUMN PJTM_PJ_BIZDAY_CAL.BF_BIZDAY_DT IS '前営業日日付';
COMMENT ON COLUMN PJTM_PJ_BIZDAY_CAL.DEL_FLG IS '削除フラグ';
COMMENT ON COLUMN PJTM_PJ_BIZDAY_CAL.REG_USR_ID IS '登録ユーザID';
COMMENT ON COLUMN PJTM_PJ_BIZDAY_CAL.REG_PGM_ID IS '登録プログラムID';
COMMENT ON COLUMN PJTM_PJ_BIZDAY_CAL.REG_TS IS '登録タイムスタンプ';
COMMENT ON COLUMN PJTM_PJ_BIZDAY_CAL.UPD_USR_ID IS '更新ユーザID';
COMMENT ON COLUMN PJTM_PJ_BIZDAY_CAL.UPD_PGM_ID IS '更新プログラムID';
COMMENT ON COLUMN PJTM_PJ_BIZDAY_CAL.UPD_TS IS '更新タイムスタンプ';
COMMENT ON COLUMN PJTM_PJ_BIZDAY_CAL.VER_NO IS 'バージョン番号';

-- ユニークインデックス用DDL

-- インデックス用DDL
CREATE INDEX IX1_PJTM_PJ_BIZDAY_CAL ON PJTM_PJ_BIZDAY_CAL (
    BIZDAY_SN 
);

