-- テーブル用DDL
DROP TABLE PJTM_PJ_HNYO_PST_ALERT CASCADE CONSTRAINTS;

CREATE TABLE PJTM_PJ_HNYO_PST_ALERT
(
    HNYO_ALERT_NO                  CHAR(3) NOT NULL ,
    PSNL_SYS_PST_CD                VARCHAR2(150) NOT NULL ,
    MIN_SCALE                      NUMBER(12) NOT NULL ,
    MAX_SCALE                      NUMBER(12) NOT NULL ,
    BS_PRICE                       NUMBER(12) DEFAULT 0 NOT NULL ,
    DEL_FLG                        CHAR(1) DEFAULT '0' NOT NULL ,
    REG_USR_ID                     NUMBER(10) NOT NULL ,
    REG_PGM_ID                     CHAR(11) NOT NULL ,
    REG_TS                         TIMESTAMP(3) NOT NULL ,
    UPD_USR_ID                     NUMBER(10) NOT NULL ,
    UPD_PGM_ID                     CHAR(11) NOT NULL ,
    UPD_TS                         TIMESTAMP(3) NOT NULL ,
    VER_NO                         NUMBER(10) DEFAULT 0 NOT NULL
);
ALTER TABLE PJTM_PJ_HNYO_PST_ALERT ADD CONSTRAINT PK_PJTM_PJ_HNYO_PST_ALERT PRIMARY KEY (HNYO_ALERT_NO, PSNL_SYS_PST_CD, MIN_SCALE, MAX_SCALE ) ;

COMMENT ON TABLE PJTM_PJ_HNYO_PST_ALERT IS '汎用役職別アラート基準マスタ(ver.1.0)';
COMMENT ON COLUMN PJTM_PJ_HNYO_PST_ALERT.HNYO_ALERT_NO IS '汎用アラート番号';
COMMENT ON COLUMN PJTM_PJ_HNYO_PST_ALERT.PSNL_SYS_PST_CD IS '人事システム役職コード';
COMMENT ON COLUMN PJTM_PJ_HNYO_PST_ALERT.MIN_SCALE IS '下限規模';
COMMENT ON COLUMN PJTM_PJ_HNYO_PST_ALERT.MAX_SCALE IS '上限規模';
COMMENT ON COLUMN PJTM_PJ_HNYO_PST_ALERT.BS_PRICE IS '基準金額';
COMMENT ON COLUMN PJTM_PJ_HNYO_PST_ALERT.DEL_FLG IS '削除フラグ';
COMMENT ON COLUMN PJTM_PJ_HNYO_PST_ALERT.REG_USR_ID IS '登録ユーザID';
COMMENT ON COLUMN PJTM_PJ_HNYO_PST_ALERT.REG_PGM_ID IS '登録プログラムID';
COMMENT ON COLUMN PJTM_PJ_HNYO_PST_ALERT.REG_TS IS '登録タイムスタンプ';
COMMENT ON COLUMN PJTM_PJ_HNYO_PST_ALERT.UPD_USR_ID IS '更新ユーザID';
COMMENT ON COLUMN PJTM_PJ_HNYO_PST_ALERT.UPD_PGM_ID IS '更新プログラムID';
COMMENT ON COLUMN PJTM_PJ_HNYO_PST_ALERT.UPD_TS IS '更新タイムスタンプ';
COMMENT ON COLUMN PJTM_PJ_HNYO_PST_ALERT.VER_NO IS 'バージョン番号';

-- ユニークインデックス用DDL

-- インデックス用DDL
