-- テーブル用DDL
DROP TABLE PJTM_PJ_ASSIGN CASCADE CONSTRAINTS;

CREATE TABLE PJTM_PJ_ASSIGN
(
    ASSIGN_ID                      NUMBER(10) NOT NULL ,
    VLD_STR_DT                     DATE NOT NULL ,
    VLD_END_DT                     DATE NOT NULL ,
    EMP_ID                         NUMBER(10) NOT NULL ,
    HR_ORGAN_ID                    NUMBER(15) NOT NULL ,
    COMPE_FLG                      CHAR(1) DEFAULT '0' NOT NULL ,
    PST_ID                         NUMBER(15) ,
    PSNL_SYS_PST_SEG               VARCHAR2(150) ,
    PSNL_SYS_PST_CD                VARCHAR2(150) ,
    ASSIGN_STATS_SEG               NUMBER(9) NOT NULL ,
    PSNL_SYS_SPIR_ID               NUMBER(10) ,
    DEL_FLG                        CHAR(1) DEFAULT '0' NOT NULL ,
    REG_USR_ID                     NUMBER(10) NOT NULL ,
    REG_PGM_ID                     CHAR(11) NOT NULL ,
    REG_TS                         TIMESTAMP(3) NOT NULL ,
    UPD_USR_ID                     NUMBER(10) NOT NULL ,
    UPD_PGM_ID                     CHAR(11) NOT NULL ,
    UPD_TS                         TIMESTAMP(3) NOT NULL ,
    VER_NO                         NUMBER(10) DEFAULT 0 NOT NULL
);
ALTER TABLE PJTM_PJ_ASSIGN ADD CONSTRAINT PK_PJTM_PJ_ASSIGN PRIMARY KEY (ASSIGN_ID, VLD_STR_DT, VLD_END_DT ) ;

COMMENT ON TABLE PJTM_PJ_ASSIGN IS 'アサインメントマスタ(ver.0.8)';
COMMENT ON COLUMN PJTM_PJ_ASSIGN.ASSIGN_ID IS 'アサインメントID';
COMMENT ON COLUMN PJTM_PJ_ASSIGN.VLD_STR_DT IS '有効開始日';
COMMENT ON COLUMN PJTM_PJ_ASSIGN.VLD_END_DT IS '有効終了日';
COMMENT ON COLUMN PJTM_PJ_ASSIGN.EMP_ID IS '従業員ID';
COMMENT ON COLUMN PJTM_PJ_ASSIGN.HR_ORGAN_ID IS 'HR組織ID';
COMMENT ON COLUMN PJTM_PJ_ASSIGN.COMPE_FLG IS '主務フラグ';
COMMENT ON COLUMN PJTM_PJ_ASSIGN.PST_ID IS '役職ID';
COMMENT ON COLUMN PJTM_PJ_ASSIGN.PSNL_SYS_PST_SEG IS '人事システム役職区分';
COMMENT ON COLUMN PJTM_PJ_ASSIGN.PSNL_SYS_PST_CD IS '人事システム役職コード';
COMMENT ON COLUMN PJTM_PJ_ASSIGN.ASSIGN_STATS_SEG IS 'アサインメントステータス区分';
COMMENT ON COLUMN PJTM_PJ_ASSIGN.PSNL_SYS_SPIR_ID IS '人事システム上長ID';
COMMENT ON COLUMN PJTM_PJ_ASSIGN.DEL_FLG IS '削除フラグ';
COMMENT ON COLUMN PJTM_PJ_ASSIGN.REG_USR_ID IS '登録ユーザID';
COMMENT ON COLUMN PJTM_PJ_ASSIGN.REG_PGM_ID IS '登録プログラムID';
COMMENT ON COLUMN PJTM_PJ_ASSIGN.REG_TS IS '登録タイムスタンプ';
COMMENT ON COLUMN PJTM_PJ_ASSIGN.UPD_USR_ID IS '更新ユーザID';
COMMENT ON COLUMN PJTM_PJ_ASSIGN.UPD_PGM_ID IS '更新プログラムID';
COMMENT ON COLUMN PJTM_PJ_ASSIGN.UPD_TS IS '更新タイムスタンプ';
COMMENT ON COLUMN PJTM_PJ_ASSIGN.VER_NO IS 'バージョン番号';

-- ユニークインデックス用DDL

-- インデックス用DDL
CREATE INDEX IX1_PJTM_PJ_ASSIGN ON PJTM_PJ_ASSIGN (
    VLD_STR_DT ,
    VLD_END_DT ,
    COMPE_FLG ,
    ASSIGN_STATS_SEG 
);

CREATE INDEX IX2_PJTM_PJ_ASSIGN ON PJTM_PJ_ASSIGN (
    EMP_ID 
);

CREATE INDEX IX3_PJTM_PJ_ASSIGN ON PJTM_PJ_ASSIGN (
    HR_ORGAN_ID 
);

CREATE INDEX IX4_PJTM_PJ_ASSIGN ON PJTM_PJ_ASSIGN (
    PSNL_SYS_PST_CD 
);

