-- テーブル用DDL
DROP TABLE PJTM_PJ_CUST CASCADE CONSTRAINTS;

CREATE TABLE PJTM_PJ_CUST
(
    CUST_ID                        NUMBER(15) NOT NULL ,
    CUST_CD                        VARCHAR2(30) NOT NULL ,
    REG_USE_DISA_FLG               CHAR(1) NOT NULL ,
    CUST_NM                        VARCHAR2(450) NOT NULL ,
    CUST_KANA                      VARCHAR2(480) ,
    CUST_SNM                       VARCHAR2(540) ,
    MO_ADDR                        VARCHAR2(450) ,
    BILLDEST_FLG                   CHAR(1) NOT NULL ,
    DEL_FLG                        CHAR(1) DEFAULT '0' NOT NULL ,
    REG_USR_ID                     NUMBER(10) NOT NULL ,
    REG_PGM_ID                     CHAR(11) NOT NULL ,
    REG_TS                         TIMESTAMP(3) NOT NULL ,
    UPD_USR_ID                     NUMBER(10) NOT NULL ,
    UPD_PGM_ID                     CHAR(11) NOT NULL ,
    UPD_TS                         TIMESTAMP(3) NOT NULL ,
    VER_NO                         NUMBER(10) DEFAULT 0 NOT NULL
);
ALTER TABLE PJTM_PJ_CUST ADD CONSTRAINT PK_PJTM_PJ_CUST PRIMARY KEY (CUST_ID ) ;

COMMENT ON TABLE PJTM_PJ_CUST IS '顧客マスタ(ver.0.7)';
COMMENT ON COLUMN PJTM_PJ_CUST.CUST_ID IS '顧客ID';
COMMENT ON COLUMN PJTM_PJ_CUST.CUST_CD IS '顧客コード';
COMMENT ON COLUMN PJTM_PJ_CUST.REG_USE_DISA_FLG IS '登録利用不可フラグ';
COMMENT ON COLUMN PJTM_PJ_CUST.CUST_NM IS '顧客名';
COMMENT ON COLUMN PJTM_PJ_CUST.CUST_KANA IS '顧客フリガナ';
COMMENT ON COLUMN PJTM_PJ_CUST.CUST_SNM IS '顧客略称';
COMMENT ON COLUMN PJTM_PJ_CUST.MO_ADDR IS '本社住所';
COMMENT ON COLUMN PJTM_PJ_CUST.BILLDEST_FLG IS '請求先フラグ';
COMMENT ON COLUMN PJTM_PJ_CUST.DEL_FLG IS '削除フラグ';
COMMENT ON COLUMN PJTM_PJ_CUST.REG_USR_ID IS '登録ユーザID';
COMMENT ON COLUMN PJTM_PJ_CUST.REG_PGM_ID IS '登録プログラムID';
COMMENT ON COLUMN PJTM_PJ_CUST.REG_TS IS '登録タイムスタンプ';
COMMENT ON COLUMN PJTM_PJ_CUST.UPD_USR_ID IS '更新ユーザID';
COMMENT ON COLUMN PJTM_PJ_CUST.UPD_PGM_ID IS '更新プログラムID';
COMMENT ON COLUMN PJTM_PJ_CUST.UPD_TS IS '更新タイムスタンプ';
COMMENT ON COLUMN PJTM_PJ_CUST.VER_NO IS 'バージョン番号';

-- ユニークインデックス用DDL

-- インデックス用DDL
CREATE INDEX IX1_PJTM_PJ_CUST ON PJTM_PJ_CUST (
    CUST_CD 
);

