-- テーブル用DDL
DROP TABLE PJTM_PJ_SPD_TYP CASCADE CONSTRAINTS;

CREATE TABLE PJTM_PJ_SPD_TYP
(
    SPD_TYP_ID                     NUMBER(15) NOT NULL ,
    SPD_TYP_NM                     VARCHAR2(90) ,
    VLD_STR_DT                     DATE ,
    VLD_END_DT                     DATE ,
    SPD_CTGRY                      VARCHAR2(90) ,
    DEL_FLG                        CHAR(1) DEFAULT '0' NOT NULL ,
    REG_USR_ID                     NUMBER(10) NOT NULL ,
    REG_PGM_ID                     CHAR(11) NOT NULL ,
    REG_TS                         TIMESTAMP(3) NOT NULL ,
    UPD_USR_ID                     NUMBER(10) NOT NULL ,
    UPD_PGM_ID                     CHAR(11) NOT NULL ,
    UPD_TS                         TIMESTAMP(3) NOT NULL ,
    VER_NO                         NUMBER(10) DEFAULT 0 NOT NULL
);
ALTER TABLE PJTM_PJ_SPD_TYP ADD CONSTRAINT PK_PJTM_PJ_SPD_TYP PRIMARY KEY (SPD_TYP_ID ) ;

COMMENT ON TABLE PJTM_PJ_SPD_TYP IS '支出タイプマスタ(ver.0.5)';
COMMENT ON COLUMN PJTM_PJ_SPD_TYP.SPD_TYP_ID IS '支出タイプID';
COMMENT ON COLUMN PJTM_PJ_SPD_TYP.SPD_TYP_NM IS '支出タイプ名';
COMMENT ON COLUMN PJTM_PJ_SPD_TYP.VLD_STR_DT IS '有効開始日';
COMMENT ON COLUMN PJTM_PJ_SPD_TYP.VLD_END_DT IS '有効終了日';
COMMENT ON COLUMN PJTM_PJ_SPD_TYP.SPD_CTGRY IS '支出カテゴリ';
COMMENT ON COLUMN PJTM_PJ_SPD_TYP.DEL_FLG IS '削除フラグ';
COMMENT ON COLUMN PJTM_PJ_SPD_TYP.REG_USR_ID IS '登録ユーザID';
COMMENT ON COLUMN PJTM_PJ_SPD_TYP.REG_PGM_ID IS '登録プログラムID';
COMMENT ON COLUMN PJTM_PJ_SPD_TYP.REG_TS IS '登録タイムスタンプ';
COMMENT ON COLUMN PJTM_PJ_SPD_TYP.UPD_USR_ID IS '更新ユーザID';
COMMENT ON COLUMN PJTM_PJ_SPD_TYP.UPD_PGM_ID IS '更新プログラムID';
COMMENT ON COLUMN PJTM_PJ_SPD_TYP.UPD_TS IS '更新タイムスタンプ';
COMMENT ON COLUMN PJTM_PJ_SPD_TYP.VER_NO IS 'バージョン番号';

-- ユニークインデックス用DDL

-- インデックス用DDL
