-- テーブル用DDL
DROP TABLE PJTR_PJ_SHIP_REQ CASCADE CONSTRAINTS;

CREATE TABLE PJTR_PJ_SHIP_REQ
(
    PRJ_CD                         CHAR(10) NOT NULL ,
    SHIP_MNG_NO                    CHAR(3) NOT NULL ,
    SHIP_REQ_DONE_FLG              CHAR(1) NOT NULL ,
    DEL_FLG                        CHAR(1) DEFAULT '0' NOT NULL ,
    REG_USR_ID                     NUMBER(10) NOT NULL ,
    REG_PGM_ID                     CHAR(11) NOT NULL ,
    REG_TS                         TIMESTAMP(3) NOT NULL ,
    UPD_USR_ID                     NUMBER(10) NOT NULL ,
    UPD_PGM_ID                     CHAR(11) NOT NULL ,
    UPD_TS                         TIMESTAMP(3) NOT NULL ,
    VER_NO                         NUMBER(10) DEFAULT 0 NOT NULL
);
ALTER TABLE PJTR_PJ_SHIP_REQ ADD CONSTRAINT PK_PJTR_PJ_SHIP_REQ PRIMARY KEY (PRJ_CD, SHIP_MNG_NO ) ;

COMMENT ON TABLE PJTR_PJ_SHIP_REQ IS '発注依頼トラン(ver.0.1)';
COMMENT ON COLUMN PJTR_PJ_SHIP_REQ.PRJ_CD IS 'プロジェクトコード';
COMMENT ON COLUMN PJTR_PJ_SHIP_REQ.SHIP_MNG_NO IS '発注管理番号';
COMMENT ON COLUMN PJTR_PJ_SHIP_REQ.SHIP_REQ_DONE_FLG IS '発注依頼済フラグ';
COMMENT ON COLUMN PJTR_PJ_SHIP_REQ.DEL_FLG IS '削除フラグ';
COMMENT ON COLUMN PJTR_PJ_SHIP_REQ.REG_USR_ID IS '登録ユーザID';
COMMENT ON COLUMN PJTR_PJ_SHIP_REQ.REG_PGM_ID IS '登録プログラムID';
COMMENT ON COLUMN PJTR_PJ_SHIP_REQ.REG_TS IS '登録タイムスタンプ';
COMMENT ON COLUMN PJTR_PJ_SHIP_REQ.UPD_USR_ID IS '更新ユーザID';
COMMENT ON COLUMN PJTR_PJ_SHIP_REQ.UPD_PGM_ID IS '更新プログラムID';
COMMENT ON COLUMN PJTR_PJ_SHIP_REQ.UPD_TS IS '更新タイムスタンプ';
COMMENT ON COLUMN PJTR_PJ_SHIP_REQ.VER_NO IS 'バージョン番号';

-- ユニークインデックス用DDL

-- インデックス用DDL
