-- テーブル用DDL
DROP TABLE PJTR_PJ_PROSC_EST_INDEV_DT CASCADE CONSTRAINTS;

CREATE TABLE PJTR_PJ_PROSC_EST_INDEV_DT
(
    PRJ_CD                         CHAR(10) NOT NULL ,
    PROSC_VER                      NUMBER(3) NOT NULL ,
    TSK_UID                        NUMBER(15) NOT NULL ,
    EMP_CD                         VARCHAR2(30) NOT NULL ,
    PLN_MNHOUR                     NUMBER(10,2) NOT NULL ,
    TMPRICE                        NUMBER(12) NOT NULL ,
    NEXTMI_FLNK_TSK_ID             NUMBER(15) NOT NULL ,
    PROC_SEG                       CHAR(1) NOT NULL ,
    TBA_FLG                        CHAR(1) NOT NULL ,
    DEL_FLG                        CHAR(1) DEFAULT '0' NOT NULL ,
    REG_USR_ID                     NUMBER(10) NOT NULL ,
    REG_PGM_ID                     CHAR(11) NOT NULL ,
    REG_TS                         TIMESTAMP(3) NOT NULL ,
    UPD_USR_ID                     NUMBER(10) NOT NULL ,
    UPD_PGM_ID                     CHAR(11) NOT NULL ,
    UPD_TS                         TIMESTAMP(3) NOT NULL ,
    VER_NO                         NUMBER(10) DEFAULT 0 NOT NULL
);
ALTER TABLE PJTR_PJ_PROSC_EST_INDEV_DT ADD CONSTRAINT PK_PJTR_PJ_PROSC_EST_INDEV_DT PRIMARY KEY (PRJ_CD, PROSC_VER, TSK_UID, EMP_CD ) ;

COMMENT ON TABLE PJTR_PJ_PROSC_EST_INDEV_DT IS '採算原価見積書内部開発明細トラン(ver.0.4)';
COMMENT ON COLUMN PJTR_PJ_PROSC_EST_INDEV_DT.PRJ_CD IS 'プロジェクトコード';
COMMENT ON COLUMN PJTR_PJ_PROSC_EST_INDEV_DT.PROSC_VER IS '採算原価バージョン';
COMMENT ON COLUMN PJTR_PJ_PROSC_EST_INDEV_DT.TSK_UID IS 'タスクUID';
COMMENT ON COLUMN PJTR_PJ_PROSC_EST_INDEV_DT.EMP_CD IS '従業員コード';
COMMENT ON COLUMN PJTR_PJ_PROSC_EST_INDEV_DT.PLN_MNHOUR IS '計画工数';
COMMENT ON COLUMN PJTR_PJ_PROSC_EST_INDEV_DT.TMPRICE IS '時間単価';
COMMENT ON COLUMN PJTR_PJ_PROSC_EST_INDEV_DT.NEXTMI_FLNK_TSK_ID IS 'NextMI連携用タスクID';
COMMENT ON COLUMN PJTR_PJ_PROSC_EST_INDEV_DT.PROC_SEG IS '処理区分';
COMMENT ON COLUMN PJTR_PJ_PROSC_EST_INDEV_DT.TBA_FLG IS 'TBAフラグ';
COMMENT ON COLUMN PJTR_PJ_PROSC_EST_INDEV_DT.DEL_FLG IS '削除フラグ';
COMMENT ON COLUMN PJTR_PJ_PROSC_EST_INDEV_DT.REG_USR_ID IS '登録ユーザID';
COMMENT ON COLUMN PJTR_PJ_PROSC_EST_INDEV_DT.REG_PGM_ID IS '登録プログラムID';
COMMENT ON COLUMN PJTR_PJ_PROSC_EST_INDEV_DT.REG_TS IS '登録タイムスタンプ';
COMMENT ON COLUMN PJTR_PJ_PROSC_EST_INDEV_DT.UPD_USR_ID IS '更新ユーザID';
COMMENT ON COLUMN PJTR_PJ_PROSC_EST_INDEV_DT.UPD_PGM_ID IS '更新プログラムID';
COMMENT ON COLUMN PJTR_PJ_PROSC_EST_INDEV_DT.UPD_TS IS '更新タイムスタンプ';
COMMENT ON COLUMN PJTR_PJ_PROSC_EST_INDEV_DT.VER_NO IS 'バージョン番号';

-- ユニークインデックス用DDL

-- インデックス用DDL
