-- テーブル用DDL
DROP TABLE PJTR_PJ_WBS_TPL CASCADE CONSTRAINTS;

CREATE TABLE PJTR_PJ_WBS_TPL
(
    WBS_ID                         NUMBER(15) NOT NULL ,
    EMP_CD                         VARCHAR2(30) NOT NULL ,
    WBS_CD                         VARCHAR2(30) NOT NULL ,
    WBS_NM                         VARCHAR2(150) NOT NULL ,
    PARENT_WBS_ID                  NUMBER(15) ,
    WBS_KND                        CHAR(2) DEFAULT '0' NOT NULL ,
    RES_ITEM                       VARCHAR2(150) ,
    DEL_FLG                        CHAR(1) DEFAULT '0' NOT NULL ,
    REG_USR_ID                     NUMBER(10) NOT NULL ,
    REG_PGM_ID                     CHAR(11) NOT NULL ,
    REG_TS                         TIMESTAMP(3) NOT NULL ,
    UPD_USR_ID                     NUMBER(10) NOT NULL ,
    UPD_PGM_ID                     CHAR(11) NOT NULL ,
    UPD_TS                         TIMESTAMP(3) NOT NULL ,
    VER_NO                         NUMBER(10) DEFAULT 0 NOT NULL
);
ALTER TABLE PJTR_PJ_WBS_TPL ADD CONSTRAINT PK_PJTR_PJ_WBS_TPL PRIMARY KEY (WBS_ID, EMP_CD ) ;

COMMENT ON TABLE PJTR_PJ_WBS_TPL IS 'WBSテンプレートトラン(ver.0.9)';
COMMENT ON COLUMN PJTR_PJ_WBS_TPL.WBS_ID IS 'WBS_ID';
COMMENT ON COLUMN PJTR_PJ_WBS_TPL.EMP_CD IS '従業員コード';
COMMENT ON COLUMN PJTR_PJ_WBS_TPL.WBS_CD IS 'WBSコード';
COMMENT ON COLUMN PJTR_PJ_WBS_TPL.WBS_NM IS 'WBS名';
COMMENT ON COLUMN PJTR_PJ_WBS_TPL.PARENT_WBS_ID IS '親WBS_ID';
COMMENT ON COLUMN PJTR_PJ_WBS_TPL.WBS_KND IS 'WBS種別';
COMMENT ON COLUMN PJTR_PJ_WBS_TPL.RES_ITEM IS '予備項目';
COMMENT ON COLUMN PJTR_PJ_WBS_TPL.DEL_FLG IS '削除フラグ';
COMMENT ON COLUMN PJTR_PJ_WBS_TPL.REG_USR_ID IS '登録ユーザID';
COMMENT ON COLUMN PJTR_PJ_WBS_TPL.REG_PGM_ID IS '登録プログラムID';
COMMENT ON COLUMN PJTR_PJ_WBS_TPL.REG_TS IS '登録タイムスタンプ';
COMMENT ON COLUMN PJTR_PJ_WBS_TPL.UPD_USR_ID IS '更新ユーザID';
COMMENT ON COLUMN PJTR_PJ_WBS_TPL.UPD_PGM_ID IS '更新プログラムID';
COMMENT ON COLUMN PJTR_PJ_WBS_TPL.UPD_TS IS '更新タイムスタンプ';
COMMENT ON COLUMN PJTR_PJ_WBS_TPL.VER_NO IS 'バージョン番号';

-- ユニークインデックス用DDL

-- インデックス用DDL
CREATE INDEX IX1_PJTR_PJ_WBS_TPL ON PJTR_PJ_WBS_TPL (
    PARENT_WBS_ID 
);

CREATE INDEX IX2_PJTR_PJ_WBS_TPL ON PJTR_PJ_WBS_TPL (
    EMP_CD 
);

