-- テーブル用DDL
DROP TABLE PJTR_PJ_WBS_TSK_TPL CASCADE CONSTRAINTS;

CREATE TABLE PJTR_PJ_WBS_TSK_TPL
(
    TPL_TSK_UID                    NUMBER(15) NOT NULL ,
    EMP_CD                         VARCHAR2(30) NOT NULL ,
    TSK_NM                         VARCHAR2(150) NOT NULL ,
    TYP                            CHAR(2) NOT NULL ,
    PARENT_TSK_UID                 NUMBER(15) ,
    WBS_ID                         NUMBER(15) NOT NULL ,
    TSK_CD                         VARCHAR2(30) DEFAULT '0' NOT NULL ,
    DSP_SEQ                        NUMBER(4) DEFAULT 0 NOT NULL ,
    ACC_MES_KND_CD                 CHAR(2) ,
    PLN_PROD_QUAL                  NUMBER(10,2) ,
    PLN_MNHOUR                     NUMBER(10,2) ,
    CMT                            VARCHAR2(600) ,
    RES_ITEM_1                     VARCHAR2(150) ,
    RES_ITEM_2                     VARCHAR2(150) ,
    RES_ITEM_3                     VARCHAR2(150) ,
    RES_ITEM_4                     VARCHAR2(150) ,
    RES_ITEM_5                     VARCHAR2(150) ,
    DEL_FLG                        CHAR(1) DEFAULT '0' NOT NULL ,
    REG_USR_ID                     NUMBER(10) NOT NULL ,
    REG_PGM_ID                     CHAR(11) NOT NULL ,
    REG_TS                         TIMESTAMP(3) NOT NULL ,
    UPD_USR_ID                     NUMBER(10) NOT NULL ,
    UPD_PGM_ID                     CHAR(11) NOT NULL ,
    UPD_TS                         TIMESTAMP(3) NOT NULL ,
    VER_NO                         NUMBER(10) DEFAULT 0 NOT NULL
);
ALTER TABLE PJTR_PJ_WBS_TSK_TPL ADD CONSTRAINT PK_PJTR_PJ_WBS_TSK_TPL PRIMARY KEY (TPL_TSK_UID, EMP_CD ) ;

COMMENT ON TABLE PJTR_PJ_WBS_TSK_TPL IS 'WBSタスクテンプレートトラン(ver.0.92)';
COMMENT ON COLUMN PJTR_PJ_WBS_TSK_TPL.TPL_TSK_UID IS 'テンプレートタスクUID';
COMMENT ON COLUMN PJTR_PJ_WBS_TSK_TPL.EMP_CD IS '従業員コード';
COMMENT ON COLUMN PJTR_PJ_WBS_TSK_TPL.TSK_NM IS 'タスク名';
COMMENT ON COLUMN PJTR_PJ_WBS_TSK_TPL.TYP IS 'タイプ';
COMMENT ON COLUMN PJTR_PJ_WBS_TSK_TPL.PARENT_TSK_UID IS '親タスクUID';
COMMENT ON COLUMN PJTR_PJ_WBS_TSK_TPL.WBS_ID IS 'WBS_ID';
COMMENT ON COLUMN PJTR_PJ_WBS_TSK_TPL.TSK_CD IS 'タスクコード';
COMMENT ON COLUMN PJTR_PJ_WBS_TSK_TPL.DSP_SEQ IS '表示順';
COMMENT ON COLUMN PJTR_PJ_WBS_TSK_TPL.ACC_MES_KND_CD IS '達成計測種別コード';
COMMENT ON COLUMN PJTR_PJ_WBS_TSK_TPL.PLN_PROD_QUAL IS '予定成果物量';
COMMENT ON COLUMN PJTR_PJ_WBS_TSK_TPL.PLN_MNHOUR IS '予定工数';
COMMENT ON COLUMN PJTR_PJ_WBS_TSK_TPL.CMT IS 'コメント';
COMMENT ON COLUMN PJTR_PJ_WBS_TSK_TPL.RES_ITEM_1 IS '予備項目1';
COMMENT ON COLUMN PJTR_PJ_WBS_TSK_TPL.RES_ITEM_2 IS '予備項目2';
COMMENT ON COLUMN PJTR_PJ_WBS_TSK_TPL.RES_ITEM_3 IS '予備項目3';
COMMENT ON COLUMN PJTR_PJ_WBS_TSK_TPL.RES_ITEM_4 IS '予備項目4';
COMMENT ON COLUMN PJTR_PJ_WBS_TSK_TPL.RES_ITEM_5 IS '予備項目5';
COMMENT ON COLUMN PJTR_PJ_WBS_TSK_TPL.DEL_FLG IS '削除フラグ';
COMMENT ON COLUMN PJTR_PJ_WBS_TSK_TPL.REG_USR_ID IS '登録ユーザID';
COMMENT ON COLUMN PJTR_PJ_WBS_TSK_TPL.REG_PGM_ID IS '登録プログラムID';
COMMENT ON COLUMN PJTR_PJ_WBS_TSK_TPL.REG_TS IS '登録タイムスタンプ';
COMMENT ON COLUMN PJTR_PJ_WBS_TSK_TPL.UPD_USR_ID IS '更新ユーザID';
COMMENT ON COLUMN PJTR_PJ_WBS_TSK_TPL.UPD_PGM_ID IS '更新プログラムID';
COMMENT ON COLUMN PJTR_PJ_WBS_TSK_TPL.UPD_TS IS '更新タイムスタンプ';
COMMENT ON COLUMN PJTR_PJ_WBS_TSK_TPL.VER_NO IS 'バージョン番号';

-- ユニークインデックス用DDL

-- インデックス用DDL
CREATE INDEX IX1_PJTR_PJ_WBS_TSK_TPL ON PJTR_PJ_WBS_TSK_TPL (
    PARENT_TSK_UID 
);

CREATE INDEX IX2_PJTR_PJ_WBS_TSK_TPL ON PJTR_PJ_WBS_TSK_TPL (
    WBS_ID 
);

CREATE INDEX IX3_PJTR_PJ_WBS_TSK_TPL ON PJTR_PJ_WBS_TSK_TPL (
    EMP_CD 
);

