-- テーブル用DDL
DROP TABLE PJTR_PJ_WBS CASCADE CONSTRAINTS;

CREATE TABLE PJTR_PJ_WBS
(
    WBS_ID                         NUMBER(15) NOT NULL ,
    WBS_CD                         VARCHAR2(30) NOT NULL ,
    WBS_NM                         VARCHAR2(150) NOT NULL ,
    PRJ_CD                         CHAR(10) NOT NULL ,
    PARENT_WBS_ID                  NUMBER(15) ,
    DSP_SEQ                        NUMBER(4) DEFAULT 0 NOT NULL ,
    DEL_FLG                        CHAR(1) DEFAULT '0' NOT NULL ,
    REG_USR_ID                     NUMBER(10) NOT NULL ,
    REG_PGM_ID                     CHAR(11) NOT NULL ,
    REG_TS                         TIMESTAMP(3) NOT NULL ,
    UPD_USR_ID                     NUMBER(10) NOT NULL ,
    UPD_PGM_ID                     CHAR(11) NOT NULL ,
    UPD_TS                         TIMESTAMP(3) NOT NULL ,
    VER_NO                         NUMBER(10) DEFAULT 0 NOT NULL
);
ALTER TABLE PJTR_PJ_WBS ADD CONSTRAINT PK_PJTR_PJ_WBS PRIMARY KEY (WBS_ID ) ;

COMMENT ON TABLE PJTR_PJ_WBS IS 'WBSトラン(ver.0.93)';
COMMENT ON COLUMN PJTR_PJ_WBS.WBS_ID IS 'WBS_ID';
COMMENT ON COLUMN PJTR_PJ_WBS.WBS_CD IS 'WBSコード';
COMMENT ON COLUMN PJTR_PJ_WBS.WBS_NM IS 'WBS名';
COMMENT ON COLUMN PJTR_PJ_WBS.PRJ_CD IS 'プロジェクトコード';
COMMENT ON COLUMN PJTR_PJ_WBS.PARENT_WBS_ID IS '親WBS_ID';
COMMENT ON COLUMN PJTR_PJ_WBS.DSP_SEQ IS '表示順';
COMMENT ON COLUMN PJTR_PJ_WBS.DEL_FLG IS '削除フラグ';
COMMENT ON COLUMN PJTR_PJ_WBS.REG_USR_ID IS '登録ユーザID';
COMMENT ON COLUMN PJTR_PJ_WBS.REG_PGM_ID IS '登録プログラムID';
COMMENT ON COLUMN PJTR_PJ_WBS.REG_TS IS '登録タイムスタンプ';
COMMENT ON COLUMN PJTR_PJ_WBS.UPD_USR_ID IS '更新ユーザID';
COMMENT ON COLUMN PJTR_PJ_WBS.UPD_PGM_ID IS '更新プログラムID';
COMMENT ON COLUMN PJTR_PJ_WBS.UPD_TS IS '更新タイムスタンプ';
COMMENT ON COLUMN PJTR_PJ_WBS.VER_NO IS 'バージョン番号';

-- ユニークインデックス用DDL

-- インデックス用DDL
CREATE INDEX IX1_PJTR_PJ_WBS ON PJTR_PJ_WBS (
    PRJ_CD 
);

CREATE INDEX IX2_PJTR_PJ_WBS ON PJTR_PJ_WBS (
    PARENT_WBS_ID 
);

