-- テーブル用DDL
DROP TABLE PJTR_PJ_PRJ_CST CASCADE CONSTRAINTS;

CREATE TABLE PJTR_PJ_PRJ_CST
(
    PRJ_CD                         CHAR(10) NOT NULL ,
    OPE_YYMM                       CHAR(6) NOT NULL ,
    EMP_ID                         NUMBER(10) NOT NULL ,
    EMP_SEG                        CHAR(1) NOT NULL ,
    AC                             NUMBER(10,2) ,
    AC_PRICE                       NUMBER(12) ,
    ENT_CLOSE_DT                   DATE ,
    DEL_FLG                        CHAR(1) DEFAULT '0' NOT NULL ,
    REG_USR_ID                     NUMBER(10) NOT NULL ,
    REG_PGM_ID                     CHAR(11) NOT NULL ,
    REG_TS                         TIMESTAMP(3) NOT NULL ,
    UPD_USR_ID                     NUMBER(10) NOT NULL ,
    UPD_PGM_ID                     CHAR(11) NOT NULL ,
    UPD_TS                         TIMESTAMP(3) NOT NULL ,
    VER_NO                         NUMBER(10) DEFAULT 0 NOT NULL
);
ALTER TABLE PJTR_PJ_PRJ_CST ADD CONSTRAINT PK_PJTR_PJ_PRJ_CST PRIMARY KEY (PRJ_CD, OPE_YYMM, EMP_ID, EMP_SEG ) ;

COMMENT ON TABLE PJTR_PJ_PRJ_CST IS 'プロジェクトコストトラン(ver.0.3)';
COMMENT ON COLUMN PJTR_PJ_PRJ_CST.PRJ_CD IS 'プロジェクトコード';
COMMENT ON COLUMN PJTR_PJ_PRJ_CST.OPE_YYMM IS '稼働年月';
COMMENT ON COLUMN PJTR_PJ_PRJ_CST.EMP_ID IS '従業員ID';
COMMENT ON COLUMN PJTR_PJ_PRJ_CST.EMP_SEG IS '従業員区分';
COMMENT ON COLUMN PJTR_PJ_PRJ_CST.AC IS 'AC';
COMMENT ON COLUMN PJTR_PJ_PRJ_CST.AC_PRICE IS 'AC額';
COMMENT ON COLUMN PJTR_PJ_PRJ_CST.ENT_CLOSE_DT IS '入力締日';
COMMENT ON COLUMN PJTR_PJ_PRJ_CST.DEL_FLG IS '削除フラグ';
COMMENT ON COLUMN PJTR_PJ_PRJ_CST.REG_USR_ID IS '登録ユーザID';
COMMENT ON COLUMN PJTR_PJ_PRJ_CST.REG_PGM_ID IS '登録プログラムID';
COMMENT ON COLUMN PJTR_PJ_PRJ_CST.REG_TS IS '登録タイムスタンプ';
COMMENT ON COLUMN PJTR_PJ_PRJ_CST.UPD_USR_ID IS '更新ユーザID';
COMMENT ON COLUMN PJTR_PJ_PRJ_CST.UPD_PGM_ID IS '更新プログラムID';
COMMENT ON COLUMN PJTR_PJ_PRJ_CST.UPD_TS IS '更新タイムスタンプ';
COMMENT ON COLUMN PJTR_PJ_PRJ_CST.VER_NO IS 'バージョン番号';

-- ユニークインデックス用DDL

-- インデックス用DDL
