-- テーブル用DDL
DROP TABLE PJTR_PJ_THIS_WBS_TSK_SNAP CASCADE CONSTRAINTS;

CREATE TABLE PJTR_PJ_THIS_WBS_TSK_SNAP
(
    SI_DEAL_CD                     CHAR(10) NOT NULL ,
    PRJ_CD                         CHAR(10) NOT NULL ,
    WBS_ID                         NUMBER(15) NOT NULL ,
    TSK_UID                        NUMBER(15) NOT NULL ,
    TSK_NM                         VARCHAR2(150) NOT NULL ,
    EMP_ID                         NUMBER(10) DEFAULT 0 NOT NULL ,
    SHIP_MNG_NO                    CHAR(3) DEFAULT '000' NOT NULL ,
    RPT_BSDT                       DATE NOT NULL ,
    UNTPRICE                       NUMBER(10) DEFAULT 0 NOT NULL ,
    ACC_RATE                       NUMBER(6,4) DEFAULT 0.0 NOT NULL ,
    PLN_ACC_RATE                   NUMBER(6,4) DEFAULT 0.0 NOT NULL ,
    STR_PLN_DT                     DATE NOT NULL ,
    END_PLN_DT                     DATE NOT NULL ,
    STR_RSLT_DT                    DATE ,
    END_RSLT_DT                    DATE ,
    FCT_CMP_DT                     DATE ,
    DELAY_DAYS                     NUMBER(4) ,
    BAC                            NUMBER(10,2) DEFAULT 0.0 NOT NULL ,
    FCT_CMP_MNHOUR                 NUMBER(10,2) DEFAULT 0.0 NOT NULL ,
    FCT_CMP_DIF                    NUMBER(10,2) DEFAULT 0.0 NOT NULL ,
    PV                             NUMBER(10,2) DEFAULT 0.0 NOT NULL ,
    EV                             NUMBER(10,2) DEFAULT 0.0 NOT NULL ,
    AC                             NUMBER(10,2) DEFAULT 0.0 NOT NULL ,
    SPI                            NUMBER(6,4) DEFAULT 0.0 NOT NULL ,
    CPI                            NUMBER(6,4) DEFAULT 0.0 NOT NULL ,
    EAC                            NUMBER(10,2) DEFAULT 0.0 NOT NULL ,
    ETC                            NUMBER(10,2) DEFAULT 0.0 NOT NULL ,
    VAC                            NUMBER(10,2) DEFAULT 0.0 NOT NULL ,
    SV                             NUMBER(10,2) DEFAULT 0.0 NOT NULL ,
    CV                             NUMBER(10,2) DEFAULT 0.0 NOT NULL ,
    BAC_PRICE                      NUMBER(12) DEFAULT 0 NOT NULL ,
    FCT_CMP_PRICE                  NUMBER(12) DEFAULT 0 NOT NULL ,
    FCT_CMP_DIF_PRICE              NUMBER(12) DEFAULT 0 NOT NULL ,
    PV_PRICE                       NUMBER(12) DEFAULT 0 NOT NULL ,
    EV_PRICE                       NUMBER(12) DEFAULT 0 NOT NULL ,
    AC_PRICE                       NUMBER(12) DEFAULT 0 NOT NULL ,
    EAC_PRICE                      NUMBER(12) DEFAULT 0 NOT NULL ,
    ETC_PRICE                      NUMBER(12) DEFAULT 0 NOT NULL ,
    VAC_PRICE                      NUMBER(12) DEFAULT 0 NOT NULL ,
    SV_PRICE                       NUMBER(12) DEFAULT 0 NOT NULL ,
    CV_PRICE                       NUMBER(12) DEFAULT 0 NOT NULL ,
    ENT_CLOSE_DT                   DATE ,
    DEL_FLG                        CHAR(1) DEFAULT '0' NOT NULL ,
    REG_USR_ID                     NUMBER(10) NOT NULL ,
    REG_PGM_ID                     CHAR(11) NOT NULL ,
    REG_TS                         TIMESTAMP(3) NOT NULL ,
    UPD_USR_ID                     NUMBER(10) NOT NULL ,
    UPD_PGM_ID                     CHAR(11) NOT NULL ,
    UPD_TS                         TIMESTAMP(3) NOT NULL ,
    VER_NO                         NUMBER(10) DEFAULT 0 NOT NULL
);
ALTER TABLE PJTR_PJ_THIS_WBS_TSK_SNAP ADD CONSTRAINT PK_PJTR_PJ_THIS_WBS_TSK_SNAP PRIMARY KEY (TSK_UID, EMP_ID, SHIP_MNG_NO ) ;

COMMENT ON TABLE PJTR_PJ_THIS_WBS_TSK_SNAP IS '今回報告締WBSタスクSNAPトラン(ver.0.8)';
COMMENT ON COLUMN PJTR_PJ_THIS_WBS_TSK_SNAP.SI_DEAL_CD IS 'SI案件コード';
COMMENT ON COLUMN PJTR_PJ_THIS_WBS_TSK_SNAP.PRJ_CD IS 'プロジェクトコード';
COMMENT ON COLUMN PJTR_PJ_THIS_WBS_TSK_SNAP.WBS_ID IS 'WBS_ID';
COMMENT ON COLUMN PJTR_PJ_THIS_WBS_TSK_SNAP.TSK_UID IS 'タスクUID';
COMMENT ON COLUMN PJTR_PJ_THIS_WBS_TSK_SNAP.TSK_NM IS 'タスク名';
COMMENT ON COLUMN PJTR_PJ_THIS_WBS_TSK_SNAP.EMP_ID IS '従業員ID';
COMMENT ON COLUMN PJTR_PJ_THIS_WBS_TSK_SNAP.SHIP_MNG_NO IS '発注管理番号';
COMMENT ON COLUMN PJTR_PJ_THIS_WBS_TSK_SNAP.RPT_BSDT IS '報告基準日';
COMMENT ON COLUMN PJTR_PJ_THIS_WBS_TSK_SNAP.UNTPRICE IS '単価';
COMMENT ON COLUMN PJTR_PJ_THIS_WBS_TSK_SNAP.ACC_RATE IS '達成率';
COMMENT ON COLUMN PJTR_PJ_THIS_WBS_TSK_SNAP.PLN_ACC_RATE IS '計画達成率';
COMMENT ON COLUMN PJTR_PJ_THIS_WBS_TSK_SNAP.STR_PLN_DT IS '開始予定日';
COMMENT ON COLUMN PJTR_PJ_THIS_WBS_TSK_SNAP.END_PLN_DT IS '終了予定日';
COMMENT ON COLUMN PJTR_PJ_THIS_WBS_TSK_SNAP.STR_RSLT_DT IS '開始実績日';
COMMENT ON COLUMN PJTR_PJ_THIS_WBS_TSK_SNAP.END_RSLT_DT IS '終了実績日';
COMMENT ON COLUMN PJTR_PJ_THIS_WBS_TSK_SNAP.FCT_CMP_DT IS '予測完了日';
COMMENT ON COLUMN PJTR_PJ_THIS_WBS_TSK_SNAP.DELAY_DAYS IS '遅延日数';
COMMENT ON COLUMN PJTR_PJ_THIS_WBS_TSK_SNAP.BAC IS 'BAC';
COMMENT ON COLUMN PJTR_PJ_THIS_WBS_TSK_SNAP.FCT_CMP_MNHOUR IS '予測完了工数';
COMMENT ON COLUMN PJTR_PJ_THIS_WBS_TSK_SNAP.FCT_CMP_DIF IS '予測完了差異';
COMMENT ON COLUMN PJTR_PJ_THIS_WBS_TSK_SNAP.PV IS 'PV';
COMMENT ON COLUMN PJTR_PJ_THIS_WBS_TSK_SNAP.EV IS 'EV';
COMMENT ON COLUMN PJTR_PJ_THIS_WBS_TSK_SNAP.AC IS 'AC';
COMMENT ON COLUMN PJTR_PJ_THIS_WBS_TSK_SNAP.SPI IS 'SPI';
COMMENT ON COLUMN PJTR_PJ_THIS_WBS_TSK_SNAP.CPI IS 'CPI';
COMMENT ON COLUMN PJTR_PJ_THIS_WBS_TSK_SNAP.EAC IS 'EAC';
COMMENT ON COLUMN PJTR_PJ_THIS_WBS_TSK_SNAP.ETC IS 'ETC';
COMMENT ON COLUMN PJTR_PJ_THIS_WBS_TSK_SNAP.VAC IS 'VAC';
COMMENT ON COLUMN PJTR_PJ_THIS_WBS_TSK_SNAP.SV IS 'SV';
COMMENT ON COLUMN PJTR_PJ_THIS_WBS_TSK_SNAP.CV IS 'CV';
COMMENT ON COLUMN PJTR_PJ_THIS_WBS_TSK_SNAP.BAC_PRICE IS 'BAC額';
COMMENT ON COLUMN PJTR_PJ_THIS_WBS_TSK_SNAP.FCT_CMP_PRICE IS '予測完了額';
COMMENT ON COLUMN PJTR_PJ_THIS_WBS_TSK_SNAP.FCT_CMP_DIF_PRICE IS '予測完了差異額';
COMMENT ON COLUMN PJTR_PJ_THIS_WBS_TSK_SNAP.PV_PRICE IS 'PV額';
COMMENT ON COLUMN PJTR_PJ_THIS_WBS_TSK_SNAP.EV_PRICE IS 'EV額';
COMMENT ON COLUMN PJTR_PJ_THIS_WBS_TSK_SNAP.AC_PRICE IS 'AC額';
COMMENT ON COLUMN PJTR_PJ_THIS_WBS_TSK_SNAP.EAC_PRICE IS 'EAC額';
COMMENT ON COLUMN PJTR_PJ_THIS_WBS_TSK_SNAP.ETC_PRICE IS 'ETC額';
COMMENT ON COLUMN PJTR_PJ_THIS_WBS_TSK_SNAP.VAC_PRICE IS 'VAC額';
COMMENT ON COLUMN PJTR_PJ_THIS_WBS_TSK_SNAP.SV_PRICE IS 'SV額';
COMMENT ON COLUMN PJTR_PJ_THIS_WBS_TSK_SNAP.CV_PRICE IS 'CV額';
COMMENT ON COLUMN PJTR_PJ_THIS_WBS_TSK_SNAP.ENT_CLOSE_DT IS '入力締日';
COMMENT ON COLUMN PJTR_PJ_THIS_WBS_TSK_SNAP.DEL_FLG IS '削除フラグ';
COMMENT ON COLUMN PJTR_PJ_THIS_WBS_TSK_SNAP.REG_USR_ID IS '登録ユーザID';
COMMENT ON COLUMN PJTR_PJ_THIS_WBS_TSK_SNAP.REG_PGM_ID IS '登録プログラムID';
COMMENT ON COLUMN PJTR_PJ_THIS_WBS_TSK_SNAP.REG_TS IS '登録タイムスタンプ';
COMMENT ON COLUMN PJTR_PJ_THIS_WBS_TSK_SNAP.UPD_USR_ID IS '更新ユーザID';
COMMENT ON COLUMN PJTR_PJ_THIS_WBS_TSK_SNAP.UPD_PGM_ID IS '更新プログラムID';
COMMENT ON COLUMN PJTR_PJ_THIS_WBS_TSK_SNAP.UPD_TS IS '更新タイムスタンプ';
COMMENT ON COLUMN PJTR_PJ_THIS_WBS_TSK_SNAP.VER_NO IS 'バージョン番号';

-- ユニークインデックス用DDL

-- インデックス用DDL
CREATE INDEX IX1_PJTR_PJ_THIS_WBS_TSK_SNAP ON PJTR_PJ_THIS_WBS_TSK_SNAP (
    SI_DEAL_CD 
);

CREATE INDEX IX2_PJTR_PJ_THIS_WBS_TSK_SNAP ON PJTR_PJ_THIS_WBS_TSK_SNAP (
    TSK_UID ,
    RPT_BSDT 
);

CREATE INDEX IX3_PJTR_PJ_THIS_WBS_TSK_SNAP ON PJTR_PJ_THIS_WBS_TSK_SNAP (
    PRJ_CD 
);

CREATE INDEX IX4_PJTR_PJ_THIS_WBS_TSK_SNAP ON PJTR_PJ_THIS_WBS_TSK_SNAP (
    WBS_ID 
);

