-- テーブル用DDL
DROP TABLE PJTR_PJ_PROSC_EST_DP_DT CASCADE CONSTRAINTS;

CREATE TABLE PJTR_PJ_PROSC_EST_DP_DT
(
    PRJ_CD                         CHAR(10) NOT NULL ,
    PROSC_VER                      NUMBER(3) NOT NULL ,
    PROSC_YYMM                     CHAR(6) NOT NULL ,
    PROS_EMP_CD                    VARCHAR2(30) NOT NULL ,
    COST_PRICE                     NUMBER(12) NOT NULL ,
    TMPRICE                        NUMBER(12) NOT NULL ,
    MONTHLY_OPE_PLN_TM             NUMBER(5,2) NOT NULL ,
    DEL_FLG                        CHAR(1) DEFAULT '0' NOT NULL ,
    REG_USR_ID                     NUMBER(10) NOT NULL ,
    REG_PGM_ID                     CHAR(11) NOT NULL ,
    REG_TS                         TIMESTAMP(3) NOT NULL ,
    UPD_USR_ID                     NUMBER(10) NOT NULL ,
    UPD_PGM_ID                     CHAR(11) NOT NULL ,
    UPD_TS                         TIMESTAMP(3) NOT NULL ,
    VER_NO                         NUMBER(10) DEFAULT 0 NOT NULL
);
ALTER TABLE PJTR_PJ_PROSC_EST_DP_DT ADD CONSTRAINT PK_PJTR_PJ_PROSC_EST_DP_DT PRIMARY KEY (PRJ_CD, PROSC_VER, PROSC_YYMM, PROS_EMP_CD ) ;

COMMENT ON TABLE PJTR_PJ_PROSC_EST_DP_DT IS '採算原価見積派遣明細トラン(ver.0.6)';
COMMENT ON COLUMN PJTR_PJ_PROSC_EST_DP_DT.PRJ_CD IS 'プロジェクトコード';
COMMENT ON COLUMN PJTR_PJ_PROSC_EST_DP_DT.PROSC_VER IS '採算原価バージョン';
COMMENT ON COLUMN PJTR_PJ_PROSC_EST_DP_DT.PROSC_YYMM IS '採算原価年月';
COMMENT ON COLUMN PJTR_PJ_PROSC_EST_DP_DT.PROS_EMP_CD IS '採算従業員コード';
COMMENT ON COLUMN PJTR_PJ_PROSC_EST_DP_DT.COST_PRICE IS '原価額';
COMMENT ON COLUMN PJTR_PJ_PROSC_EST_DP_DT.TMPRICE IS '時間単価';
COMMENT ON COLUMN PJTR_PJ_PROSC_EST_DP_DT.MONTHLY_OPE_PLN_TM IS '月度稼働予定時間';
COMMENT ON COLUMN PJTR_PJ_PROSC_EST_DP_DT.DEL_FLG IS '削除フラグ';
COMMENT ON COLUMN PJTR_PJ_PROSC_EST_DP_DT.REG_USR_ID IS '登録ユーザID';
COMMENT ON COLUMN PJTR_PJ_PROSC_EST_DP_DT.REG_PGM_ID IS '登録プログラムID';
COMMENT ON COLUMN PJTR_PJ_PROSC_EST_DP_DT.REG_TS IS '登録タイムスタンプ';
COMMENT ON COLUMN PJTR_PJ_PROSC_EST_DP_DT.UPD_USR_ID IS '更新ユーザID';
COMMENT ON COLUMN PJTR_PJ_PROSC_EST_DP_DT.UPD_PGM_ID IS '更新プログラムID';
COMMENT ON COLUMN PJTR_PJ_PROSC_EST_DP_DT.UPD_TS IS '更新タイムスタンプ';
COMMENT ON COLUMN PJTR_PJ_PROSC_EST_DP_DT.VER_NO IS 'バージョン番号';

-- ユニークインデックス用DDL

-- インデックス用DDL
