-- テーブル用DDL
DROP TABLE PJTR_PJ_PRJ_RESRC CASCADE CONSTRAINTS;

CREATE TABLE PJTR_PJ_PRJ_RESRC
(
    PRJ_CD                         CHAR(10) NOT NULL ,
    PRJ_RESRC_EMP_CD               VARCHAR2(30) NOT NULL ,
    PRJ_RESRC_EMP_NM               VARCHAR2(60) ,
    PRJ_RESRC_STR_DT               DATE NOT NULL ,
    PRJ_RESRC_END_DT               DATE NOT NULL ,
    PRJ_RESRC_ROLE                 VARCHAR2(4) NOT NULL ,
    PRJ_RESRC_OPE_TM               NUMBER(4,2) ,
    PRJ_RESRC_TBA_FLG              CHAR(1) ,
    PRJ_RESRC_TBA_PST_ID           NUMBER(15) ,
    DEL_FLG                        CHAR(1) DEFAULT '0' NOT NULL ,
    REG_USR_ID                     NUMBER(10) NOT NULL ,
    REG_PGM_ID                     CHAR(11) NOT NULL ,
    REG_TS                         TIMESTAMP(3) NOT NULL ,
    UPD_USR_ID                     NUMBER(10) NOT NULL ,
    UPD_PGM_ID                     CHAR(11) NOT NULL ,
    UPD_TS                         TIMESTAMP(3) NOT NULL ,
    VER_NO                         NUMBER(10) DEFAULT 0 NOT NULL
);
ALTER TABLE PJTR_PJ_PRJ_RESRC ADD CONSTRAINT PK_PJTR_PJ_PRJ_RESRC PRIMARY KEY (PRJ_CD, PRJ_RESRC_EMP_CD, PRJ_RESRC_STR_DT, PRJ_RESRC_END_DT, PRJ_RESRC_ROLE ) ;

COMMENT ON TABLE PJTR_PJ_PRJ_RESRC IS 'プロジェクトリソーストラン(ver.0.6)';
COMMENT ON COLUMN PJTR_PJ_PRJ_RESRC.PRJ_CD IS 'プロジェクトコード';
COMMENT ON COLUMN PJTR_PJ_PRJ_RESRC.PRJ_RESRC_EMP_CD IS 'プロジェクトリソース従業員コード';
COMMENT ON COLUMN PJTR_PJ_PRJ_RESRC.PRJ_RESRC_EMP_NM IS 'プロジェクトリソース従業員名';
COMMENT ON COLUMN PJTR_PJ_PRJ_RESRC.PRJ_RESRC_STR_DT IS 'プロジェクトリソース開始日';
COMMENT ON COLUMN PJTR_PJ_PRJ_RESRC.PRJ_RESRC_END_DT IS 'プロジェクトリソース終了日';
COMMENT ON COLUMN PJTR_PJ_PRJ_RESRC.PRJ_RESRC_ROLE IS 'プロジェクトリソースロール';
COMMENT ON COLUMN PJTR_PJ_PRJ_RESRC.PRJ_RESRC_OPE_TM IS 'プロジェクトリソース稼働時間';
COMMENT ON COLUMN PJTR_PJ_PRJ_RESRC.PRJ_RESRC_TBA_FLG IS 'プロジェクトリソースTBAフラグ';
COMMENT ON COLUMN PJTR_PJ_PRJ_RESRC.PRJ_RESRC_TBA_PST_ID IS 'プロジェクトリソースTBA役職ID';
COMMENT ON COLUMN PJTR_PJ_PRJ_RESRC.DEL_FLG IS '削除フラグ';
COMMENT ON COLUMN PJTR_PJ_PRJ_RESRC.REG_USR_ID IS '登録ユーザID';
COMMENT ON COLUMN PJTR_PJ_PRJ_RESRC.REG_PGM_ID IS '登録プログラムID';
COMMENT ON COLUMN PJTR_PJ_PRJ_RESRC.REG_TS IS '登録タイムスタンプ';
COMMENT ON COLUMN PJTR_PJ_PRJ_RESRC.UPD_USR_ID IS '更新ユーザID';
COMMENT ON COLUMN PJTR_PJ_PRJ_RESRC.UPD_PGM_ID IS '更新プログラムID';
COMMENT ON COLUMN PJTR_PJ_PRJ_RESRC.UPD_TS IS '更新タイムスタンプ';
COMMENT ON COLUMN PJTR_PJ_PRJ_RESRC.VER_NO IS 'バージョン番号';

-- ユニークインデックス用DDL

-- インデックス用DDL
CREATE INDEX IX1_PJTR_PJ_PRJ_RESRC ON PJTR_PJ_PRJ_RESRC (
    PRJ_RESRC_EMP_CD 
);

CREATE INDEX IX2_PJTR_PJ_PRJ_RESRC ON PJTR_PJ_PRJ_RESRC (
    PRJ_RESRC_STR_DT ,
    PRJ_RESRC_END_DT ,
    PRJ_RESRC_ROLE 
);

