-- テーブル用DDL
DROP TABLE PJTR_PJ_GL_VOUC CASCADE CONSTRAINTS;

CREATE TABLE PJTR_PJ_GL_VOUC
(
    PRJ_CD                         CHAR(10) DEFAULT '0000000000' NOT NULL ,
    INCI_DT                        DATE NOT NULL ,
    INCI_TMS                       NUMBER(3) NOT NULL ,
    ENT_YYMM                       CHAR(6) NOT NULL ,
    ENT_SEG                        CHAR(1) NOT NULL ,
    GL_VOUC_RCD_PRICE              NUMBER(12) DEFAULT 0 NOT NULL ,
    DEL_FLG                        CHAR(1) DEFAULT '0' NOT NULL ,
    REG_USR_ID                     NUMBER(10) NOT NULL ,
    REG_PGM_ID                     CHAR(11) NOT NULL ,
    REG_TS                         TIMESTAMP(3) NOT NULL ,
    UPD_USR_ID                     NUMBER(10) NOT NULL ,
    UPD_PGM_ID                     CHAR(11) NOT NULL ,
    UPD_TS                         TIMESTAMP(3) NOT NULL ,
    VER_NO                         NUMBER(10) DEFAULT 0 NOT NULL
);
ALTER TABLE PJTR_PJ_GL_VOUC ADD CONSTRAINT PK_PJTR_PJ_GL_VOUC PRIMARY KEY (PRJ_CD, INCI_DT, INCI_TMS, ENT_YYMM, ENT_SEG ) ;

COMMENT ON TABLE PJTR_PJ_GL_VOUC IS 'GL伝票トラン(ver.0.6)';
COMMENT ON COLUMN PJTR_PJ_GL_VOUC.PRJ_CD IS 'プロジェクトコード';
COMMENT ON COLUMN PJTR_PJ_GL_VOUC.INCI_DT IS '発生日';
COMMENT ON COLUMN PJTR_PJ_GL_VOUC.INCI_TMS IS '発生回数';
COMMENT ON COLUMN PJTR_PJ_GL_VOUC.ENT_YYMM IS '算入年月';
COMMENT ON COLUMN PJTR_PJ_GL_VOUC.ENT_SEG IS '算入区分';
COMMENT ON COLUMN PJTR_PJ_GL_VOUC.GL_VOUC_RCD_PRICE IS 'GL伝票計上額';
COMMENT ON COLUMN PJTR_PJ_GL_VOUC.DEL_FLG IS '削除フラグ';
COMMENT ON COLUMN PJTR_PJ_GL_VOUC.REG_USR_ID IS '登録ユーザID';
COMMENT ON COLUMN PJTR_PJ_GL_VOUC.REG_PGM_ID IS '登録プログラムID';
COMMENT ON COLUMN PJTR_PJ_GL_VOUC.REG_TS IS '登録タイムスタンプ';
COMMENT ON COLUMN PJTR_PJ_GL_VOUC.UPD_USR_ID IS '更新ユーザID';
COMMENT ON COLUMN PJTR_PJ_GL_VOUC.UPD_PGM_ID IS '更新プログラムID';
COMMENT ON COLUMN PJTR_PJ_GL_VOUC.UPD_TS IS '更新タイムスタンプ';
COMMENT ON COLUMN PJTR_PJ_GL_VOUC.VER_NO IS 'バージョン番号';

-- ユニークインデックス用DDL

-- インデックス用DDL
