-- テーブル用DDL
DROP TABLE PJTR_PJ_SI_DEAL_CONT_LNK CASCADE CONSTRAINTS;

CREATE TABLE PJTR_PJ_SI_DEAL_CONT_LNK
(
    SI_DEAL_CD                     CHAR(10) NOT NULL ,
    ODR_NO                         CHAR(10) NOT NULL ,
    SAR_STATS                      CHAR(1) DEFAULT '0' NOT NULL ,
    BUSI_PROC_DT                   DATE NOT NULL ,
    DEL_FLG                        CHAR(1) DEFAULT '0' NOT NULL ,
    REG_USR_ID                     NUMBER(10) NOT NULL ,
    REG_PGM_ID                     CHAR(11) NOT NULL ,
    REG_TS                         TIMESTAMP(3) NOT NULL ,
    UPD_USR_ID                     NUMBER(10) NOT NULL ,
    UPD_PGM_ID                     CHAR(11) NOT NULL ,
    UPD_TS                         TIMESTAMP(3) NOT NULL ,
    VER_NO                         NUMBER(10) DEFAULT 0 NOT NULL
);
ALTER TABLE PJTR_PJ_SI_DEAL_CONT_LNK ADD CONSTRAINT PK_PJTR_PJ_SI_DEAL_CONT_LNK PRIMARY KEY (SI_DEAL_CD, ODR_NO ) ;

COMMENT ON TABLE PJTR_PJ_SI_DEAL_CONT_LNK IS 'SI案件成約紐付トラン(ver.0.6)';
COMMENT ON COLUMN PJTR_PJ_SI_DEAL_CONT_LNK.SI_DEAL_CD IS 'SI案件コード';
COMMENT ON COLUMN PJTR_PJ_SI_DEAL_CONT_LNK.ODR_NO IS '受注番号';
COMMENT ON COLUMN PJTR_PJ_SI_DEAL_CONT_LNK.SAR_STATS IS '送受信ステータス';
COMMENT ON COLUMN PJTR_PJ_SI_DEAL_CONT_LNK.BUSI_PROC_DT IS '業務処理日付';
COMMENT ON COLUMN PJTR_PJ_SI_DEAL_CONT_LNK.DEL_FLG IS '削除フラグ';
COMMENT ON COLUMN PJTR_PJ_SI_DEAL_CONT_LNK.REG_USR_ID IS '登録ユーザID';
COMMENT ON COLUMN PJTR_PJ_SI_DEAL_CONT_LNK.REG_PGM_ID IS '登録プログラムID';
COMMENT ON COLUMN PJTR_PJ_SI_DEAL_CONT_LNK.REG_TS IS '登録タイムスタンプ';
COMMENT ON COLUMN PJTR_PJ_SI_DEAL_CONT_LNK.UPD_USR_ID IS '更新ユーザID';
COMMENT ON COLUMN PJTR_PJ_SI_DEAL_CONT_LNK.UPD_PGM_ID IS '更新プログラムID';
COMMENT ON COLUMN PJTR_PJ_SI_DEAL_CONT_LNK.UPD_TS IS '更新タイムスタンプ';
COMMENT ON COLUMN PJTR_PJ_SI_DEAL_CONT_LNK.VER_NO IS 'バージョン番号';

-- ユニークインデックス用DDL

-- インデックス用DDL
CREATE INDEX IX1_PJTR_PJ_SI_DEAL_CONT_LNK ON PJTR_PJ_SI_DEAL_CONT_LNK (
    ODR_NO 
);

CREATE INDEX IX2_PJTR_PJ_SI_DEAL_CONT_LNK ON PJTR_PJ_SI_DEAL_CONT_LNK (
    SAR_STATS ,
    BUSI_PROC_DT 
);

