-- テーブル用DDL
DROP TABLE PJTR_PJ_PRJ CASCADE CONSTRAINTS;

CREATE TABLE PJTR_PJ_PRJ
(
    SI_DEAL_CD                     CHAR(10) NOT NULL ,
    PRJ_CD                         CHAR(10) NOT NULL ,
    WHCO_MNG_PRJ_NO                VARCHAR2(15) ,
    PRJ_NM                         VARCHAR2(90) NOT NULL ,
    PRJ_DT_NM                      VARCHAR2(720) NOT NULL ,
    PRJ_STR_DT                     DATE NOT NULL ,
    PRJ_END_DT                     DATE NOT NULL ,
    PRJ_STATS_SEG                  CHAR(3) NOT NULL ,
    PRJ_TPL                        VARCHAR2(25) NOT NULL ,
    PRJ_FORM_SEG                   VARCHAR2(90) NOT NULL ,
    PRJ_INCO_PSC_FLG               CHAR(1) DEFAULT '0' NOT NULL ,
    PROS_INCO_PRICE                NUMBER(12) ,
    PRJ_PROP_CST_LMT_PRICE         NUMBER(12) DEFAULT 0 NOT NULL ,
    PRJ_RPT_BS_YOUBI               CHAR(1) NOT NULL ,
    PRJ_PROG_ENT_CLOSE_YOUBI       CHAR(1) NOT NULL ,
    PRJ_BAS_OPE_TM                 NUMBER(4,2) NOT NULL ,
    PRJ_EGY_EMP_CD                 VARCHAR2(30) NOT NULL ,
    PRJ_EGY_EMP_AUTO_LNK_FLG       CHAR(1) DEFAULT '0' NOT NULL ,
    PRJ_SLS_COST_TRNS_DEPT_CD      VARCHAR2(150) ,
    PRJ_DEV_DEPT_CD                VARCHAR2(150) NOT NULL ,
    SI_DEAL_SYNC_REG_FLG           CHAR(1) DEFAULT '0' NOT NULL ,
    PRJ_CUST_CD                    VARCHAR2(30) NOT NULL ,
    PRJ_OPN_NOTICE_FLG             CHAR(1) DEFAULT '0' NOT NULL ,
    PRJ_SHIP_APP_NOTICE_FLG        CHAR(1) DEFAULT '0' NOT NULL ,
    PRJ_PROG_AUTO_SET_FLG          CHAR(1) DEFAULT '0' NOT NULL ,
    PRJ_OUTS_PROG_AUTO_SET_FLG     CHAR(1) DEFAULT '0' NOT NULL ,
    PROP_PRJ_FLG                   CHAR(1) DEFAULT '0' NOT NULL ,
    FLAW_PRJ_FLG                   CHAR(1) DEFAULT '0' NOT NULL ,
    FLAW_PRJ_CD                    CHAR(10) ,
    PRJ_STATS_RECV_DT              DATE ,
    SND_FLG                        CHAR(1) DEFAULT '0' NOT NULL ,
    BUSI_PROC_DT                   DATE NOT NULL ,
    ALERT_NOTICE_DEST_1            VARCHAR2(240) ,
    ALERT_NOTICE_DEST_2            VARCHAR2(240) ,
    ALERT_NOTICE_DEST_3            VARCHAR2(240) ,
    PRJ_CUST_CONT_ORGAN_NM         VARCHAR2(450) ,
    PRJ_CUST_CONT_CHG              VARCHAR2(450) ,
    PRJ_CUST_CONT_TEL              VARCHAR2(45) ,
    PRJ_CUST_CONT_FAX              VARCHAR2(45) ,
    PRJ_CUST_CONT_EMAIL            VARCHAR2(240) ,
    LAT_PROG_ENT_DT                DATE ,
    LAT_PROG_ENT_EMP_CD            VARCHAR2(30) ,
    DEL_FLG                        CHAR(1) DEFAULT '0' NOT NULL ,
    REG_USR_ID                     NUMBER(10) NOT NULL ,
    REG_PGM_ID                     CHAR(11) NOT NULL ,
    REG_TS                         TIMESTAMP(3) NOT NULL ,
    UPD_USR_ID                     NUMBER(10) NOT NULL ,
    UPD_PGM_ID                     CHAR(11) NOT NULL ,
    UPD_TS                         TIMESTAMP(3) NOT NULL ,
    VER_NO                         NUMBER(10) DEFAULT 0 NOT NULL
);
ALTER TABLE PJTR_PJ_PRJ ADD CONSTRAINT PK_PJTR_PJ_PRJ PRIMARY KEY (PRJ_CD ) ;

COMMENT ON TABLE PJTR_PJ_PRJ IS 'プロジェクトトラン(ver.1.03)';
COMMENT ON COLUMN PJTR_PJ_PRJ.SI_DEAL_CD IS 'SI案件コード';
COMMENT ON COLUMN PJTR_PJ_PRJ.PRJ_CD IS 'プロジェクトコード';
COMMENT ON COLUMN PJTR_PJ_PRJ.WHCO_MNG_PRJ_NO IS '全社管理プロジェクト番号';
COMMENT ON COLUMN PJTR_PJ_PRJ.PRJ_NM IS 'プロジェクト名';
COMMENT ON COLUMN PJTR_PJ_PRJ.PRJ_DT_NM IS 'プロジェクト詳細名';
COMMENT ON COLUMN PJTR_PJ_PRJ.PRJ_STR_DT IS 'プロジェクト開始日';
COMMENT ON COLUMN PJTR_PJ_PRJ.PRJ_END_DT IS 'プロジェクト終了日';
COMMENT ON COLUMN PJTR_PJ_PRJ.PRJ_STATS_SEG IS 'プロジェクトステータス区分';
COMMENT ON COLUMN PJTR_PJ_PRJ.PRJ_TPL IS 'プロジェクトテンプレート';
COMMENT ON COLUMN PJTR_PJ_PRJ.PRJ_FORM_SEG IS 'プロジェクト形態別区分';
COMMENT ON COLUMN PJTR_PJ_PRJ.PRJ_INCO_PSC_FLG IS 'プロジェクト社内売買有無フラグ';
COMMENT ON COLUMN PJTR_PJ_PRJ.PROS_INCO_PRICE IS '採算社内売買額';
COMMENT ON COLUMN PJTR_PJ_PRJ.PRJ_PROP_CST_LMT_PRICE IS 'プロジェクト提案コスト限度額';
COMMENT ON COLUMN PJTR_PJ_PRJ.PRJ_RPT_BS_YOUBI IS 'プロジェクト報告基準曜日';
COMMENT ON COLUMN PJTR_PJ_PRJ.PRJ_PROG_ENT_CLOSE_YOUBI IS 'プロジェクト進捗入力締曜日';
COMMENT ON COLUMN PJTR_PJ_PRJ.PRJ_BAS_OPE_TM IS 'プロジェクト基本稼働時間';
COMMENT ON COLUMN PJTR_PJ_PRJ.PRJ_EGY_EMP_CD IS 'プロジェクト営業従業員コード';
COMMENT ON COLUMN PJTR_PJ_PRJ.PRJ_EGY_EMP_AUTO_LNK_FLG IS 'プロジェクト営業従業員自動連携フラグ';
COMMENT ON COLUMN PJTR_PJ_PRJ.PRJ_SLS_COST_TRNS_DEPT_CD IS 'プロジェクト売上原価振替先部課コード';
COMMENT ON COLUMN PJTR_PJ_PRJ.PRJ_DEV_DEPT_CD IS 'プロジェクト開発部課コード';
COMMENT ON COLUMN PJTR_PJ_PRJ.SI_DEAL_SYNC_REG_FLG IS 'SI案件同時登録フラグ';
COMMENT ON COLUMN PJTR_PJ_PRJ.PRJ_CUST_CD IS 'プロジェクト顧客取引先コード';
COMMENT ON COLUMN PJTR_PJ_PRJ.PRJ_OPN_NOTICE_FLG IS 'プロジェクトオープン通知フラグ';
COMMENT ON COLUMN PJTR_PJ_PRJ.PRJ_SHIP_APP_NOTICE_FLG IS 'プロジェクト発注承認通知フラグ';
COMMENT ON COLUMN PJTR_PJ_PRJ.PRJ_PROG_AUTO_SET_FLG IS 'プロジェクト進捗自動設定フラグ';
COMMENT ON COLUMN PJTR_PJ_PRJ.PRJ_OUTS_PROG_AUTO_SET_FLG IS 'プロジェクト委託先進捗自動設定フラグ';
COMMENT ON COLUMN PJTR_PJ_PRJ.PROP_PRJ_FLG IS '提案プロジェクトフラグ';
COMMENT ON COLUMN PJTR_PJ_PRJ.FLAW_PRJ_FLG IS '瑕疵プロジェクトフラグ';
COMMENT ON COLUMN PJTR_PJ_PRJ.FLAW_PRJ_CD IS '瑕疵プロジェクトコード';
COMMENT ON COLUMN PJTR_PJ_PRJ.PRJ_STATS_RECV_DT IS 'プロジェクトステータス受信日';
COMMENT ON COLUMN PJTR_PJ_PRJ.SND_FLG IS '送信フラグ';
COMMENT ON COLUMN PJTR_PJ_PRJ.BUSI_PROC_DT IS '業務処理日付';
COMMENT ON COLUMN PJTR_PJ_PRJ.ALERT_NOTICE_DEST_1 IS 'アラート通知先１';
COMMENT ON COLUMN PJTR_PJ_PRJ.ALERT_NOTICE_DEST_2 IS 'アラート通知先２';
COMMENT ON COLUMN PJTR_PJ_PRJ.ALERT_NOTICE_DEST_3 IS 'アラート通知先３';
COMMENT ON COLUMN PJTR_PJ_PRJ.PRJ_CUST_CONT_ORGAN_NM IS 'プロジェクト顧客窓口組織名';
COMMENT ON COLUMN PJTR_PJ_PRJ.PRJ_CUST_CONT_CHG IS 'プロジェクト顧客窓口担当者';
COMMENT ON COLUMN PJTR_PJ_PRJ.PRJ_CUST_CONT_TEL IS 'プロジェクト顧客窓口TEL';
COMMENT ON COLUMN PJTR_PJ_PRJ.PRJ_CUST_CONT_FAX IS 'プロジェクト顧客窓口FAX';
COMMENT ON COLUMN PJTR_PJ_PRJ.PRJ_CUST_CONT_EMAIL IS 'プロジェクト顧客窓口E-MAIL';
COMMENT ON COLUMN PJTR_PJ_PRJ.LAT_PROG_ENT_DT IS '最新進捗入力日';
COMMENT ON COLUMN PJTR_PJ_PRJ.LAT_PROG_ENT_EMP_CD IS '最新進捗入力従業員コード';
COMMENT ON COLUMN PJTR_PJ_PRJ.DEL_FLG IS '削除フラグ';
COMMENT ON COLUMN PJTR_PJ_PRJ.REG_USR_ID IS '登録ユーザID';
COMMENT ON COLUMN PJTR_PJ_PRJ.REG_PGM_ID IS '登録プログラムID';
COMMENT ON COLUMN PJTR_PJ_PRJ.REG_TS IS '登録タイムスタンプ';
COMMENT ON COLUMN PJTR_PJ_PRJ.UPD_USR_ID IS '更新ユーザID';
COMMENT ON COLUMN PJTR_PJ_PRJ.UPD_PGM_ID IS '更新プログラムID';
COMMENT ON COLUMN PJTR_PJ_PRJ.UPD_TS IS '更新タイムスタンプ';
COMMENT ON COLUMN PJTR_PJ_PRJ.VER_NO IS 'バージョン番号';

-- ユニークインデックス用DDL

-- インデックス用DDL
CREATE INDEX IX1_PJTR_PJ_PRJ ON PJTR_PJ_PRJ (
    SI_DEAL_CD 
);

CREATE INDEX IX2_PJTR_PJ_PRJ ON PJTR_PJ_PRJ (
    PRJ_EGY_EMP_CD 
);

CREATE INDEX IX3_PJTR_PJ_PRJ ON PJTR_PJ_PRJ (
    PRJ_DEV_DEPT_CD 
);

CREATE INDEX IX4_PJTR_PJ_PRJ ON PJTR_PJ_PRJ (
    PRJ_CUST_CD 
);

CREATE INDEX IX5_PJTR_PJ_PRJ ON PJTR_PJ_PRJ (
    BUSI_PROC_DT 
);

CREATE INDEX IX6_PJTR_PJ_PRJ ON PJTR_PJ_PRJ (
    PRJ_STATS_SEG 
);


