-- テーブル用DDL
DROP TABLE PJTR_PJ_CONT_DT CASCADE CONSTRAINTS;

CREATE TABLE PJTR_PJ_CONT_DT
(
    ODR_NO                         CHAR(10) NOT NULL ,
    ODR_DT_TYP                     CHAR(1) NOT NULL ,
    PRJ_CD                         CHAR(10) DEFAULT '0000000000' NOT NULL ,
    SELLPRI_PRICE                  NUMBER(12) NOT NULL ,
    EGY_COST_PRICE                 NUMBER(12) NOT NULL ,
    PRJ_INCO_PSC_FLG               CHAR(1) NOT NULL ,
    EGY_EMP_CD                     VARCHAR2(30) NOT NULL ,
    DEL_FLG                        CHAR(1) DEFAULT '0' NOT NULL ,
    REG_USR_ID                     NUMBER(10) NOT NULL ,
    REG_PGM_ID                     CHAR(11) NOT NULL ,
    REG_TS                         TIMESTAMP(3) NOT NULL ,
    UPD_USR_ID                     NUMBER(10) NOT NULL ,
    UPD_PGM_ID                     CHAR(11) NOT NULL ,
    UPD_TS                         TIMESTAMP(3) NOT NULL ,
    VER_NO                         NUMBER(10) DEFAULT 0 NOT NULL
);
ALTER TABLE PJTR_PJ_CONT_DT ADD CONSTRAINT PK_PJTR_PJ_CONT_DT PRIMARY KEY (ODR_NO, ODR_DT_TYP, PRJ_CD ) ;

COMMENT ON TABLE PJTR_PJ_CONT_DT IS '成約明細トラン(ver.0.5)';
COMMENT ON COLUMN PJTR_PJ_CONT_DT.ODR_NO IS '受注番号';
COMMENT ON COLUMN PJTR_PJ_CONT_DT.ODR_DT_TYP IS '受注明細タイプ';
COMMENT ON COLUMN PJTR_PJ_CONT_DT.PRJ_CD IS 'プロジェクトコード';
COMMENT ON COLUMN PJTR_PJ_CONT_DT.SELLPRI_PRICE IS '売価額';
COMMENT ON COLUMN PJTR_PJ_CONT_DT.EGY_COST_PRICE IS '営業原価額';
COMMENT ON COLUMN PJTR_PJ_CONT_DT.PRJ_INCO_PSC_FLG IS 'プロジェクト社内売買有無フラグ';
COMMENT ON COLUMN PJTR_PJ_CONT_DT.EGY_EMP_CD IS '営業従業員コード';
COMMENT ON COLUMN PJTR_PJ_CONT_DT.DEL_FLG IS '削除フラグ';
COMMENT ON COLUMN PJTR_PJ_CONT_DT.REG_USR_ID IS '登録ユーザID';
COMMENT ON COLUMN PJTR_PJ_CONT_DT.REG_PGM_ID IS '登録プログラムID';
COMMENT ON COLUMN PJTR_PJ_CONT_DT.REG_TS IS '登録タイムスタンプ';
COMMENT ON COLUMN PJTR_PJ_CONT_DT.UPD_USR_ID IS '更新ユーザID';
COMMENT ON COLUMN PJTR_PJ_CONT_DT.UPD_PGM_ID IS '更新プログラムID';
COMMENT ON COLUMN PJTR_PJ_CONT_DT.UPD_TS IS '更新タイムスタンプ';
COMMENT ON COLUMN PJTR_PJ_CONT_DT.VER_NO IS 'バージョン番号';

-- ユニークインデックス用DDL

-- インデックス用DDL
CREATE INDEX IX1_PJTR_PJ_CONT_DT ON PJTR_PJ_CONT_DT (
    PRJ_CD 
);

