-- テーブル用DDL
DROP TABLE PJTR_PJ_WBS_TSK CASCADE CONSTRAINTS;

CREATE TABLE PJTR_PJ_WBS_TSK
(
    TSK_UID                        NUMBER(15) NOT NULL ,
    TSK_NM                         VARCHAR2(150) NOT NULL ,
    TYP                            CHAR(2) NOT NULL ,
    PARENT_TSK_UID                 NUMBER(15) ,
    WBS_ID                         NUMBER(15) NOT NULL ,
    TSK_CD                         VARCHAR2(30) DEFAULT '0' NOT NULL ,
    NEXTMI_FLNK_TSK_ID             NUMBER(15) ,
    DSP_SEQ                        NUMBER(4) DEFAULT 0 NOT NULL ,
    PRJ_CD                         CHAR(10) NOT NULL ,
    ACC_MES_KND_CD                 CHAR(2) DEFAULT '0' NOT NULL ,
    SHIP_TSK_FLG                   CHAR(1) DEFAULT '0' NOT NULL ,
    SHIP_MNG_NO                    CHAR(3) ,
    PLN_PROD_QUAL                  NUMBER(10,2) ,
    PLN_MNHOUR                     NUMBER(10,2) ,
    STR_PLN_DT                     DATE ,
    END_PLN_DT                     DATE ,
    HDAY_OPE_FLG                   CHAR(1) DEFAULT '0' NOT NULL ,
    STR_RSLT_DT                    DATE ,
    END_RSLT_DT                    DATE ,
    PRJ_EXCEPT_SEG                 CHAR(1) DEFAULT '0' NOT NULL ,
    PRJ_UND_FLG                    CHAR(1) DEFAULT '0' NOT NULL ,
    PREV_RSLT                      NUMBER(12,4) ,
    PREV_RSLT_REM                  NUMBER(12,4) ,
    THIS_RSLT                      NUMBER(12,4) ,
    THIS_RSLT_REM                  NUMBER(12,4) ,
    NEXT_RSLT                      NUMBER(12,4) ,
    NEXT_RSLT_REM                  NUMBER(12,4) ,
    AC                             NUMBER(10,2) ,
    AC_PRICE                       NUMBER(12) ,
    CMT                            VARCHAR2(600) ,
    RES_ITEM_1                     VARCHAR2(150) ,
    RES_ITEM_2                     VARCHAR2(150) ,
    RES_ITEM_3                     VARCHAR2(150) ,
    RES_ITEM_4                     VARCHAR2(150) ,
    RES_ITEM_5                     VARCHAR2(150) ,
    DEL_FLG                        CHAR(1) DEFAULT '0' NOT NULL ,
    REG_USR_ID                     NUMBER(10) NOT NULL ,
    REG_PGM_ID                     CHAR(11) NOT NULL ,
    REG_TS                         TIMESTAMP(3) NOT NULL ,
    UPD_USR_ID                     NUMBER(10) NOT NULL ,
    UPD_PGM_ID                     CHAR(11) NOT NULL ,
    UPD_TS                         TIMESTAMP(3) NOT NULL ,
    VER_NO                         NUMBER(10) DEFAULT 0 NOT NULL
);
ALTER TABLE PJTR_PJ_WBS_TSK ADD CONSTRAINT PK_PJTR_PJ_WBS_TSK PRIMARY KEY (TSK_UID ) ;

COMMENT ON TABLE PJTR_PJ_WBS_TSK IS 'WBSタスクトラン(ver.0.99)';
COMMENT ON COLUMN PJTR_PJ_WBS_TSK.TSK_UID IS 'タスクUID';
COMMENT ON COLUMN PJTR_PJ_WBS_TSK.TSK_NM IS 'タスク名';
COMMENT ON COLUMN PJTR_PJ_WBS_TSK.TYP IS 'タイプ';
COMMENT ON COLUMN PJTR_PJ_WBS_TSK.PARENT_TSK_UID IS '親タスクUID';
COMMENT ON COLUMN PJTR_PJ_WBS_TSK.WBS_ID IS 'WBS_ID';
COMMENT ON COLUMN PJTR_PJ_WBS_TSK.TSK_CD IS 'タスクコード';
COMMENT ON COLUMN PJTR_PJ_WBS_TSK.NEXTMI_FLNK_TSK_ID IS 'NextMI連携用タスクID';
COMMENT ON COLUMN PJTR_PJ_WBS_TSK.DSP_SEQ IS '表示順';
COMMENT ON COLUMN PJTR_PJ_WBS_TSK.PRJ_CD IS 'プロジェクトコード';
COMMENT ON COLUMN PJTR_PJ_WBS_TSK.ACC_MES_KND_CD IS '達成計測種別コード';
COMMENT ON COLUMN PJTR_PJ_WBS_TSK.SHIP_TSK_FLG IS '発注タスクフラグ';
COMMENT ON COLUMN PJTR_PJ_WBS_TSK.SHIP_MNG_NO IS '発注管理番号';
COMMENT ON COLUMN PJTR_PJ_WBS_TSK.PLN_PROD_QUAL IS '予定成果物量';
COMMENT ON COLUMN PJTR_PJ_WBS_TSK.PLN_MNHOUR IS '予定工数';
COMMENT ON COLUMN PJTR_PJ_WBS_TSK.STR_PLN_DT IS '開始予定日';
COMMENT ON COLUMN PJTR_PJ_WBS_TSK.END_PLN_DT IS '終了予定日';
COMMENT ON COLUMN PJTR_PJ_WBS_TSK.HDAY_OPE_FLG IS '休日稼働フラグ';
COMMENT ON COLUMN PJTR_PJ_WBS_TSK.STR_RSLT_DT IS '開始実績日';
COMMENT ON COLUMN PJTR_PJ_WBS_TSK.END_RSLT_DT IS '終了実績日';
COMMENT ON COLUMN PJTR_PJ_WBS_TSK.PRJ_EXCEPT_SEG IS 'プロジェクト対象外区分';
COMMENT ON COLUMN PJTR_PJ_WBS_TSK.PRJ_UND_FLG IS 'プロジェクト直下フラグ';
COMMENT ON COLUMN PJTR_PJ_WBS_TSK.PREV_RSLT IS '前回実績';
COMMENT ON COLUMN PJTR_PJ_WBS_TSK.PREV_RSLT_REM IS '前回実績残';
COMMENT ON COLUMN PJTR_PJ_WBS_TSK.THIS_RSLT IS '今回実績';
COMMENT ON COLUMN PJTR_PJ_WBS_TSK.THIS_RSLT_REM IS '今回実績残';
COMMENT ON COLUMN PJTR_PJ_WBS_TSK.NEXT_RSLT IS '次回実績';
COMMENT ON COLUMN PJTR_PJ_WBS_TSK.NEXT_RSLT_REM IS '次回実績残';
COMMENT ON COLUMN PJTR_PJ_WBS_TSK.AC IS 'AC';
COMMENT ON COLUMN PJTR_PJ_WBS_TSK.AC_PRICE IS 'AC額';
COMMENT ON COLUMN PJTR_PJ_WBS_TSK.CMT IS 'コメント';
COMMENT ON COLUMN PJTR_PJ_WBS_TSK.RES_ITEM_1 IS '予備項目1';
COMMENT ON COLUMN PJTR_PJ_WBS_TSK.RES_ITEM_2 IS '予備項目2';
COMMENT ON COLUMN PJTR_PJ_WBS_TSK.RES_ITEM_3 IS '予備項目3';
COMMENT ON COLUMN PJTR_PJ_WBS_TSK.RES_ITEM_4 IS '予備項目4';
COMMENT ON COLUMN PJTR_PJ_WBS_TSK.RES_ITEM_5 IS '予備項目5';
COMMENT ON COLUMN PJTR_PJ_WBS_TSK.DEL_FLG IS '削除フラグ';
COMMENT ON COLUMN PJTR_PJ_WBS_TSK.REG_USR_ID IS '登録ユーザID';
COMMENT ON COLUMN PJTR_PJ_WBS_TSK.REG_PGM_ID IS '登録プログラムID';
COMMENT ON COLUMN PJTR_PJ_WBS_TSK.REG_TS IS '登録タイムスタンプ';
COMMENT ON COLUMN PJTR_PJ_WBS_TSK.UPD_USR_ID IS '更新ユーザID';
COMMENT ON COLUMN PJTR_PJ_WBS_TSK.UPD_PGM_ID IS '更新プログラムID';
COMMENT ON COLUMN PJTR_PJ_WBS_TSK.UPD_TS IS '更新タイムスタンプ';
COMMENT ON COLUMN PJTR_PJ_WBS_TSK.VER_NO IS 'バージョン番号';

-- ユニークインデックス用DDL

-- インデックス用DDL
CREATE INDEX IX1_PJTR_PJ_WBS_TSK ON PJTR_PJ_WBS_TSK (
    WBS_ID 
);

CREATE INDEX IX2_PJTR_PJ_WBS_TSK ON PJTR_PJ_WBS_TSK (
    PRJ_CD 
);

CREATE INDEX IX3_PJTR_PJ_WBS_TSK ON PJTR_PJ_WBS_TSK (
    PRJ_CD ,
    SHIP_MNG_NO 
);

CREATE INDEX IX4_PJTR_PJ_WBS_TSK ON PJTR_PJ_WBS_TSK (
    PARENT_TSK_UID 
);

