-- テーブル用DDL
DROP TABLE PJTR_PJ_WBS_TSK_RESRC CASCADE CONSTRAINTS;

CREATE TABLE PJTR_PJ_WBS_TSK_RESRC
(
    TSK_UID                        NUMBER(15) NOT NULL ,
    EMP_CD                         VARCHAR2(30) NOT NULL ,
    DSP_SEQ                        NUMBER(4) DEFAULT 0 NOT NULL ,
    PLN_MNHOUR                     NUMBER(10,2) ,
    PRJ_CD                         CHAR(10) NOT NULL ,
    AC                             NUMBER(10,2) ,
    AC_PRICE                       NUMBER(12) ,
    CMT                            VARCHAR2(600) ,
    RES_ITEM                       VARCHAR2(150) ,
    DEL_FLG                        CHAR(1) DEFAULT '0' NOT NULL ,
    REG_USR_ID                     NUMBER(10) NOT NULL ,
    REG_PGM_ID                     CHAR(11) NOT NULL ,
    REG_TS                         TIMESTAMP(3) NOT NULL ,
    UPD_USR_ID                     NUMBER(10) NOT NULL ,
    UPD_PGM_ID                     CHAR(11) NOT NULL ,
    UPD_TS                         TIMESTAMP(3) NOT NULL ,
    VER_NO                         NUMBER(10) DEFAULT 0 NOT NULL
);
ALTER TABLE PJTR_PJ_WBS_TSK_RESRC ADD CONSTRAINT PK_PJTR_PJ_WBS_TSK_RESRC PRIMARY KEY (TSK_UID, EMP_CD ) ;

COMMENT ON TABLE PJTR_PJ_WBS_TSK_RESRC IS 'WBSタスクリソーストラン(ver.0.8)';
COMMENT ON COLUMN PJTR_PJ_WBS_TSK_RESRC.TSK_UID IS 'タスクUID';
COMMENT ON COLUMN PJTR_PJ_WBS_TSK_RESRC.EMP_CD IS '従業員コード';
COMMENT ON COLUMN PJTR_PJ_WBS_TSK_RESRC.DSP_SEQ IS '表示順';
COMMENT ON COLUMN PJTR_PJ_WBS_TSK_RESRC.PLN_MNHOUR IS '計画工数';
COMMENT ON COLUMN PJTR_PJ_WBS_TSK_RESRC.PRJ_CD IS 'プロジェクトコード';
COMMENT ON COLUMN PJTR_PJ_WBS_TSK_RESRC.AC IS 'AC';
COMMENT ON COLUMN PJTR_PJ_WBS_TSK_RESRC.AC_PRICE IS 'AC額';
COMMENT ON COLUMN PJTR_PJ_WBS_TSK_RESRC.CMT IS 'コメント';
COMMENT ON COLUMN PJTR_PJ_WBS_TSK_RESRC.RES_ITEM IS '予備項目';
COMMENT ON COLUMN PJTR_PJ_WBS_TSK_RESRC.DEL_FLG IS '削除フラグ';
COMMENT ON COLUMN PJTR_PJ_WBS_TSK_RESRC.REG_USR_ID IS '登録ユーザID';
COMMENT ON COLUMN PJTR_PJ_WBS_TSK_RESRC.REG_PGM_ID IS '登録プログラムID';
COMMENT ON COLUMN PJTR_PJ_WBS_TSK_RESRC.REG_TS IS '登録タイムスタンプ';
COMMENT ON COLUMN PJTR_PJ_WBS_TSK_RESRC.UPD_USR_ID IS '更新ユーザID';
COMMENT ON COLUMN PJTR_PJ_WBS_TSK_RESRC.UPD_PGM_ID IS '更新プログラムID';
COMMENT ON COLUMN PJTR_PJ_WBS_TSK_RESRC.UPD_TS IS '更新タイムスタンプ';
COMMENT ON COLUMN PJTR_PJ_WBS_TSK_RESRC.VER_NO IS 'バージョン番号';

-- ユニークインデックス用DDL

-- インデックス用DDL
CREATE INDEX IX1_PJTR_PJ_WBS_TSK_RESRC ON PJTR_PJ_WBS_TSK_RESRC (
    EMP_CD 
);

CREATE INDEX IX2_PJTR_PJ_WBS_TSK_RESRC ON PJTR_PJ_WBS_TSK_RESRC (
    PRJ_CD 
);

