-- テーブル用DDL
DROP TABLE PJTR_PJ_SUPP_MNHOUR_PRICE CASCADE CONSTRAINTS;

CREATE TABLE PJTR_PJ_SUPP_MNHOUR_PRICE
(
    PRJ_CD                         CHAR(10) NOT NULL ,
    SHIP_MNG_NO                    CHAR(3) NOT NULL ,
    BAC                            NUMBER(10,2) ,
    SHIP_PRICE                     NUMBER(12) ,
    DEL_FLG                        CHAR(1) DEFAULT '0' NOT NULL ,
    REG_USR_ID                     NUMBER(10) NOT NULL ,
    REG_PGM_ID                     CHAR(11) NOT NULL ,
    REG_TS                         TIMESTAMP(3) NOT NULL ,
    UPD_USR_ID                     NUMBER(10) NOT NULL ,
    UPD_PGM_ID                     CHAR(11) NOT NULL ,
    UPD_TS                         TIMESTAMP(3) NOT NULL ,
    VER_NO                         NUMBER(10) DEFAULT 0 NOT NULL
);
ALTER TABLE PJTR_PJ_SUPP_MNHOUR_PRICE ADD CONSTRAINT PK_PJTR_PJ_SUPP_MNHOUR_PRICE PRIMARY KEY (PRJ_CD, SHIP_MNG_NO ) ;

COMMENT ON TABLE PJTR_PJ_SUPP_MNHOUR_PRICE IS '発注先別工数・金額トラン(ver.0.3)';
COMMENT ON COLUMN PJTR_PJ_SUPP_MNHOUR_PRICE.PRJ_CD IS 'プロジェクトコード';
COMMENT ON COLUMN PJTR_PJ_SUPP_MNHOUR_PRICE.SHIP_MNG_NO IS '発注管理番号';
COMMENT ON COLUMN PJTR_PJ_SUPP_MNHOUR_PRICE.BAC IS 'BAC';
COMMENT ON COLUMN PJTR_PJ_SUPP_MNHOUR_PRICE.SHIP_PRICE IS '発注金額';
COMMENT ON COLUMN PJTR_PJ_SUPP_MNHOUR_PRICE.DEL_FLG IS '削除フラグ';
COMMENT ON COLUMN PJTR_PJ_SUPP_MNHOUR_PRICE.REG_USR_ID IS '登録ユーザID';
COMMENT ON COLUMN PJTR_PJ_SUPP_MNHOUR_PRICE.REG_PGM_ID IS '登録プログラムID';
COMMENT ON COLUMN PJTR_PJ_SUPP_MNHOUR_PRICE.REG_TS IS '登録タイムスタンプ';
COMMENT ON COLUMN PJTR_PJ_SUPP_MNHOUR_PRICE.UPD_USR_ID IS '更新ユーザID';
COMMENT ON COLUMN PJTR_PJ_SUPP_MNHOUR_PRICE.UPD_PGM_ID IS '更新プログラムID';
COMMENT ON COLUMN PJTR_PJ_SUPP_MNHOUR_PRICE.UPD_TS IS '更新タイムスタンプ';
COMMENT ON COLUMN PJTR_PJ_SUPP_MNHOUR_PRICE.VER_NO IS 'バージョン番号';

-- ユニークインデックス用DDL

-- インデックス用DDL
