-- テーブル用DDL
DROP TABLE PJTR_PJ_ACCEPT_SLS_HEAD CASCADE CONSTRAINTS;

CREATE TABLE PJTR_PJ_ACCEPT_SLS_HEAD
(
    ODR_NO                         CHAR(10) NOT NULL ,
    LNK_NO                         CHAR(10) NOT NULL ,
    REL_ODR_NO                     CHAR(10) NOT NULL ,
    EST_NO                         VARCHAR2(10) NOT NULL ,
    EST_NM                         VARCHAR2(240) ,
    ODR_DT                         DATE ,
    SELLPRI_PRICE                  NUMBER(12) NOT NULL ,
    EGY_COST_PRICE                 NUMBER(12) NOT NULL ,
    INOFFICE_SLS_PRICE             NUMBER(12) NOT NULL ,
    ACT_COST_PRICE                 NUMBER(12) NOT NULL ,
    PROG_BS_APPLY_SEG              VARCHAR2(10) NOT NULL ,
    PROG_BS_APPLY_SEG_NM           VARCHAR2(15) ,
    PROG_UNT_NO                    CHAR(10) NOT NULL ,
    DEL_FLG                        CHAR(1) DEFAULT '0' NOT NULL ,
    REG_USR_ID                     NUMBER(10) NOT NULL ,
    REG_PGM_ID                     CHAR(11) NOT NULL ,
    REG_TS                         TIMESTAMP(3) NOT NULL ,
    UPD_USR_ID                     NUMBER(10) NOT NULL ,
    UPD_PGM_ID                     CHAR(11) NOT NULL ,
    UPD_TS                         TIMESTAMP(3) NOT NULL ,
    VER_NO                         NUMBER(10) DEFAULT 0 NOT NULL
);
ALTER TABLE PJTR_PJ_ACCEPT_SLS_HEAD ADD CONSTRAINT PK_PJTR_PJ_ACCEPT_SLS_HEAD PRIMARY KEY (ODR_NO ) ;

COMMENT ON TABLE PJTR_PJ_ACCEPT_SLS_HEAD IS '検収売上ヘッダトラン(ver.0.6)';
COMMENT ON COLUMN PJTR_PJ_ACCEPT_SLS_HEAD.ODR_NO IS '受注番号';
COMMENT ON COLUMN PJTR_PJ_ACCEPT_SLS_HEAD.LNK_NO IS '紐付番号';
COMMENT ON COLUMN PJTR_PJ_ACCEPT_SLS_HEAD.REL_ODR_NO IS '関連受注番号';
COMMENT ON COLUMN PJTR_PJ_ACCEPT_SLS_HEAD.EST_NO IS '見積番号';
COMMENT ON COLUMN PJTR_PJ_ACCEPT_SLS_HEAD.EST_NM IS '見積名';
COMMENT ON COLUMN PJTR_PJ_ACCEPT_SLS_HEAD.ODR_DT IS '受注日';
COMMENT ON COLUMN PJTR_PJ_ACCEPT_SLS_HEAD.SELLPRI_PRICE IS '売価額';
COMMENT ON COLUMN PJTR_PJ_ACCEPT_SLS_HEAD.EGY_COST_PRICE IS '営業原価額';
COMMENT ON COLUMN PJTR_PJ_ACCEPT_SLS_HEAD.INOFFICE_SLS_PRICE IS '社内売上額';
COMMENT ON COLUMN PJTR_PJ_ACCEPT_SLS_HEAD.ACT_COST_PRICE IS '実原価額';
COMMENT ON COLUMN PJTR_PJ_ACCEPT_SLS_HEAD.PROG_BS_APPLY_SEG IS '進行基準適用区分';
COMMENT ON COLUMN PJTR_PJ_ACCEPT_SLS_HEAD.PROG_BS_APPLY_SEG_NM IS '進行基準適用区分名';
COMMENT ON COLUMN PJTR_PJ_ACCEPT_SLS_HEAD.PROG_UNT_NO IS '進行単位番号';
COMMENT ON COLUMN PJTR_PJ_ACCEPT_SLS_HEAD.DEL_FLG IS '削除フラグ';
COMMENT ON COLUMN PJTR_PJ_ACCEPT_SLS_HEAD.REG_USR_ID IS '登録ユーザID';
COMMENT ON COLUMN PJTR_PJ_ACCEPT_SLS_HEAD.REG_PGM_ID IS '登録プログラムID';
COMMENT ON COLUMN PJTR_PJ_ACCEPT_SLS_HEAD.REG_TS IS '登録タイムスタンプ';
COMMENT ON COLUMN PJTR_PJ_ACCEPT_SLS_HEAD.UPD_USR_ID IS '更新ユーザID';
COMMENT ON COLUMN PJTR_PJ_ACCEPT_SLS_HEAD.UPD_PGM_ID IS '更新プログラムID';
COMMENT ON COLUMN PJTR_PJ_ACCEPT_SLS_HEAD.UPD_TS IS '更新タイムスタンプ';
COMMENT ON COLUMN PJTR_PJ_ACCEPT_SLS_HEAD.VER_NO IS 'バージョン番号';

-- ユニークインデックス用DDL

-- インデックス用DDL
