-- テーブル用DDL
DROP TABLE PJTR_PJ_SI_DEAL_MY_DEAL CASCADE CONSTRAINTS;

CREATE TABLE PJTR_PJ_SI_DEAL_MY_DEAL
(
    EMP_CD                         VARCHAR2(30) NOT NULL ,
    SI_DEAL_CD                     CHAR(10) NOT NULL ,
    DEL_FLG                        CHAR(1) DEFAULT '0' NOT NULL ,
    REG_USR_ID                     NUMBER(10) NOT NULL ,
    REG_PGM_ID                     CHAR(11) NOT NULL ,
    REG_TS                         TIMESTAMP(3) NOT NULL ,
    UPD_USR_ID                     NUMBER(10) NOT NULL ,
    UPD_PGM_ID                     CHAR(11) NOT NULL ,
    UPD_TS                         TIMESTAMP(3) NOT NULL ,
    VER_NO                         NUMBER(10) DEFAULT 0 NOT NULL
);
ALTER TABLE PJTR_PJ_SI_DEAL_MY_DEAL ADD CONSTRAINT PK_PJTR_PJ_SI_DEAL_MY_DEAL PRIMARY KEY (EMP_CD, SI_DEAL_CD ) ;

COMMENT ON TABLE PJTR_PJ_SI_DEAL_MY_DEAL IS 'SI案件MY案件トラン(ver.0.6)';
COMMENT ON COLUMN PJTR_PJ_SI_DEAL_MY_DEAL.EMP_CD IS '従業員コード';
COMMENT ON COLUMN PJTR_PJ_SI_DEAL_MY_DEAL.SI_DEAL_CD IS 'SI案件コード';
COMMENT ON COLUMN PJTR_PJ_SI_DEAL_MY_DEAL.DEL_FLG IS '削除フラグ';
COMMENT ON COLUMN PJTR_PJ_SI_DEAL_MY_DEAL.REG_USR_ID IS '登録ユーザID';
COMMENT ON COLUMN PJTR_PJ_SI_DEAL_MY_DEAL.REG_PGM_ID IS '登録プログラムID';
COMMENT ON COLUMN PJTR_PJ_SI_DEAL_MY_DEAL.REG_TS IS '登録タイムスタンプ';
COMMENT ON COLUMN PJTR_PJ_SI_DEAL_MY_DEAL.UPD_USR_ID IS '更新ユーザID';
COMMENT ON COLUMN PJTR_PJ_SI_DEAL_MY_DEAL.UPD_PGM_ID IS '更新プログラムID';
COMMENT ON COLUMN PJTR_PJ_SI_DEAL_MY_DEAL.UPD_TS IS '更新タイムスタンプ';
COMMENT ON COLUMN PJTR_PJ_SI_DEAL_MY_DEAL.VER_NO IS 'バージョン番号';

-- ユニークインデックス用DDL

-- インデックス用DDL
CREATE INDEX IX1_PJTR_PJ_SI_DEAL_MY_DEAL ON PJTR_PJ_SI_DEAL_MY_DEAL (
    SI_DEAL_CD 
);

