-- テーブル用DDL
DROP TABLE PJTR_PJ_SI_DEAL CASCADE CONSTRAINTS;

CREATE TABLE PJTR_PJ_SI_DEAL
(
    SI_DEAL_CD                     CHAR(10) NOT NULL ,
    SI_DEAL_NM                     VARCHAR2(150) NOT NULL ,
    SI_DEAL_STATS                  CHAR(2) ,
    SI_DEAL_STATS_UPD_DT           DATE NOT NULL ,
    SI_DEAL_STR_DT                 DATE NOT NULL ,
    SI_DEAL_END_DT                 DATE NOT NULL ,
    SI_DEAL_CUST_CD                VARCHAR2(30) NOT NULL ,
    SI_DEAL_CUST_CONT_ORGAN_NM     VARCHAR2(450) ,
    SI_DEAL_CUST_CONT_CHG          VARCHAR2(450) ,
    SI_DEAL_CUST_CONT_TEL          VARCHAR2(45) ,
    SI_DEAL_CUST_CONT_FAX          VARCHAR2(45) ,
    SI_DEAL_CUST_CONT_EMAIL        VARCHAR2(240) ,
    SI_DEAL_EGY_DEPT_CD            VARCHAR2(150) NOT NULL ,
    SI_DEAL_EGY_EMP_CD             VARCHAR2(30) NOT NULL ,
    SI_DEAL_AUTO_MK_FLG            CHAR(1) NOT NULL ,
    PROP_CST_LMT_PRICE             NUMBER(12) DEFAULT 0 NOT NULL ,
    SI_REL_CONT_EST_PRICE          NUMBER(12) NOT NULL ,
    SI_REL_CONT_COST_EST_PRICE     NUMBER(12) NOT NULL ,
    SV_REL_CONT_EST_PRICE          NUMBER(12) NOT NULL ,
    SV_REL_CONT_COST_EST_PRICE     NUMBER(12) NOT NULL ,
    EQP_CONT_EST_PRICE             NUMBER(12) NOT NULL ,
    EQP_CONT_COST_EST_PRICE        NUMBER(12) NOT NULL ,
    INCO_FLG                       CHAR(1) DEFAULT '0' NOT NULL ,
    ALERT_NOTICE_DEST_1            VARCHAR2(240) ,
    ALERT_NOTICE_DEST_2            VARCHAR2(240) ,
    ALERT_NOTICE_DEST_3            VARCHAR2(240) ,
    DEL_FLG                        CHAR(1) DEFAULT '0' NOT NULL ,
    REG_USR_ID                     NUMBER(10) NOT NULL ,
    REG_PGM_ID                     CHAR(11) NOT NULL ,
    REG_TS                         TIMESTAMP(3) NOT NULL ,
    UPD_USR_ID                     NUMBER(10) NOT NULL ,
    UPD_PGM_ID                     CHAR(11) NOT NULL ,
    UPD_TS                         TIMESTAMP(3) NOT NULL ,
    VER_NO                         NUMBER(10) DEFAULT 0 NOT NULL
);
ALTER TABLE PJTR_PJ_SI_DEAL ADD CONSTRAINT PK_PJTR_PJ_SI_DEAL PRIMARY KEY (SI_DEAL_CD ) ;

COMMENT ON TABLE PJTR_PJ_SI_DEAL IS 'SI案件トラン(ver.0.9)';
COMMENT ON COLUMN PJTR_PJ_SI_DEAL.SI_DEAL_CD IS 'SI案件コード';
COMMENT ON COLUMN PJTR_PJ_SI_DEAL.SI_DEAL_NM IS 'SI案件名';
COMMENT ON COLUMN PJTR_PJ_SI_DEAL.SI_DEAL_STATS IS 'SI案件ステータス';
COMMENT ON COLUMN PJTR_PJ_SI_DEAL.SI_DEAL_STATS_UPD_DT IS 'SI案件ステータス更新日';
COMMENT ON COLUMN PJTR_PJ_SI_DEAL.SI_DEAL_STR_DT IS 'SI案件開始日';
COMMENT ON COLUMN PJTR_PJ_SI_DEAL.SI_DEAL_END_DT IS 'SI案件終了日';
COMMENT ON COLUMN PJTR_PJ_SI_DEAL.SI_DEAL_CUST_CD IS 'SI案件顧客コード';
COMMENT ON COLUMN PJTR_PJ_SI_DEAL.SI_DEAL_CUST_CONT_ORGAN_NM IS 'SI案件顧客窓口組織名';
COMMENT ON COLUMN PJTR_PJ_SI_DEAL.SI_DEAL_CUST_CONT_CHG IS 'SI案件顧客窓口担当者';
COMMENT ON COLUMN PJTR_PJ_SI_DEAL.SI_DEAL_CUST_CONT_TEL IS 'SI案件顧客窓口TEL';
COMMENT ON COLUMN PJTR_PJ_SI_DEAL.SI_DEAL_CUST_CONT_FAX IS 'SI案件顧客窓口FAX';
COMMENT ON COLUMN PJTR_PJ_SI_DEAL.SI_DEAL_CUST_CONT_EMAIL IS 'SI案件顧客窓口E-MAIL';
COMMENT ON COLUMN PJTR_PJ_SI_DEAL.SI_DEAL_EGY_DEPT_CD IS 'SI案件営業部課コード';
COMMENT ON COLUMN PJTR_PJ_SI_DEAL.SI_DEAL_EGY_EMP_CD IS 'SI案件営業従業員コード';
COMMENT ON COLUMN PJTR_PJ_SI_DEAL.SI_DEAL_AUTO_MK_FLG IS 'SI案件自動作成フラグ';
COMMENT ON COLUMN PJTR_PJ_SI_DEAL.PROP_CST_LMT_PRICE IS '提案コスト限度額';
COMMENT ON COLUMN PJTR_PJ_SI_DEAL.SI_REL_CONT_EST_PRICE IS 'SI関連成約見込額';
COMMENT ON COLUMN PJTR_PJ_SI_DEAL.SI_REL_CONT_COST_EST_PRICE IS 'SI関連成約原価見込額';
COMMENT ON COLUMN PJTR_PJ_SI_DEAL.SV_REL_CONT_EST_PRICE IS 'SV関連成約見込額';
COMMENT ON COLUMN PJTR_PJ_SI_DEAL.SV_REL_CONT_COST_EST_PRICE IS 'SV関連成約原価見込額';
COMMENT ON COLUMN PJTR_PJ_SI_DEAL.EQP_CONT_EST_PRICE IS '機器販売成約見込額';
COMMENT ON COLUMN PJTR_PJ_SI_DEAL.EQP_CONT_COST_EST_PRICE IS '機器販売成約原価見込額';
COMMENT ON COLUMN PJTR_PJ_SI_DEAL.INCO_FLG IS '社内売買フラグ';
COMMENT ON COLUMN PJTR_PJ_SI_DEAL.ALERT_NOTICE_DEST_1 IS 'アラート通知先１';
COMMENT ON COLUMN PJTR_PJ_SI_DEAL.ALERT_NOTICE_DEST_2 IS 'アラート通知先２';
COMMENT ON COLUMN PJTR_PJ_SI_DEAL.ALERT_NOTICE_DEST_3 IS 'アラート通知先３';
COMMENT ON COLUMN PJTR_PJ_SI_DEAL.DEL_FLG IS '削除フラグ';
COMMENT ON COLUMN PJTR_PJ_SI_DEAL.REG_USR_ID IS '登録ユーザID';
COMMENT ON COLUMN PJTR_PJ_SI_DEAL.REG_PGM_ID IS '登録プログラムID';
COMMENT ON COLUMN PJTR_PJ_SI_DEAL.REG_TS IS '登録タイムスタンプ';
COMMENT ON COLUMN PJTR_PJ_SI_DEAL.UPD_USR_ID IS '更新ユーザID';
COMMENT ON COLUMN PJTR_PJ_SI_DEAL.UPD_PGM_ID IS '更新プログラムID';
COMMENT ON COLUMN PJTR_PJ_SI_DEAL.UPD_TS IS '更新タイムスタンプ';
COMMENT ON COLUMN PJTR_PJ_SI_DEAL.VER_NO IS 'バージョン番号';

-- ユニークインデックス用DDL

-- インデックス用DDL
CREATE INDEX IX1_PJTR_PJ_SI_DEAL ON PJTR_PJ_SI_DEAL (
    SI_DEAL_CUST_CD 
);

CREATE INDEX IX2_PJTR_PJ_SI_DEAL ON PJTR_PJ_SI_DEAL (
    SI_DEAL_EGY_DEPT_CD 
);

CREATE INDEX IX3_PJTR_PJ_SI_DEAL ON PJTR_PJ_SI_DEAL (
    SI_DEAL_EGY_EMP_CD 
);

