-- テーブル用DDL
DROP TABLE PJTR_PJ_PROSC_EST_SHIP_DT CASCADE CONSTRAINTS;

CREATE TABLE PJTR_PJ_PROSC_EST_SHIP_DT
(
    PRJ_CD                         CHAR(10) NOT NULL ,
    PROSC_VER                      NUMBER(3) NOT NULL ,
    SHIP_MNG_NO                    CHAR(3) NOT NULL ,
    SUPP_CD                        VARCHAR2(30) NOT NULL ,
    ABS                            VARCHAR2(600) ,
    CUR                            VARCHAR2(15) NOT NULL ,
    INOFFICE_RATE                  NUMBER(5,2) NOT NULL ,
    SHIP_YYMM                      CHAR(6) NOT NULL ,
    PAY_YYMM                       CHAR(6) NOT NULL ,
    SHIP_MANMON                    NUMBER(6,2) NOT NULL ,
    SHIP_PLN_PRICE                 NUMBER(12) NOT NULL ,
    SHIP_PLN_PRICE_CUR             NUMBER(12) NOT NULL ,
    EST_ARI_FLG                    CHAR(1) DEFAULT '0' NOT NULL ,
    CONT_ARI_FLG                   CHAR(1) DEFAULT '0' NOT NULL ,
    DEL_FLG                        CHAR(1) DEFAULT '0' NOT NULL ,
    REG_USR_ID                     NUMBER(10) NOT NULL ,
    REG_PGM_ID                     CHAR(11) NOT NULL ,
    REG_TS                         TIMESTAMP(3) NOT NULL ,
    UPD_USR_ID                     NUMBER(10) NOT NULL ,
    UPD_PGM_ID                     CHAR(11) NOT NULL ,
    UPD_TS                         TIMESTAMP(3) NOT NULL ,
    VER_NO                         NUMBER(10) DEFAULT 0 NOT NULL
);
ALTER TABLE PJTR_PJ_PROSC_EST_SHIP_DT ADD CONSTRAINT PK_PJTR_PJ_PROSC_EST_SHIP_DT PRIMARY KEY (PRJ_CD, PROSC_VER, SHIP_MNG_NO ) ;

COMMENT ON TABLE PJTR_PJ_PROSC_EST_SHIP_DT IS '採算原価見積発注明細トラン(ver.0.7)';
COMMENT ON COLUMN PJTR_PJ_PROSC_EST_SHIP_DT.PRJ_CD IS 'プロジェクトコード';
COMMENT ON COLUMN PJTR_PJ_PROSC_EST_SHIP_DT.PROSC_VER IS '採算原価バージョン';
COMMENT ON COLUMN PJTR_PJ_PROSC_EST_SHIP_DT.SHIP_MNG_NO IS '発注管理番号';
COMMENT ON COLUMN PJTR_PJ_PROSC_EST_SHIP_DT.SUPP_CD IS '発注先コード';
COMMENT ON COLUMN PJTR_PJ_PROSC_EST_SHIP_DT.ABS IS '摘要';
COMMENT ON COLUMN PJTR_PJ_PROSC_EST_SHIP_DT.CUR IS '通貨';
COMMENT ON COLUMN PJTR_PJ_PROSC_EST_SHIP_DT.INOFFICE_RATE IS '社内レート';
COMMENT ON COLUMN PJTR_PJ_PROSC_EST_SHIP_DT.SHIP_YYMM IS '発注年月';
COMMENT ON COLUMN PJTR_PJ_PROSC_EST_SHIP_DT.PAY_YYMM IS '支払年月';
COMMENT ON COLUMN PJTR_PJ_PROSC_EST_SHIP_DT.SHIP_MANMON IS '発注人月';
COMMENT ON COLUMN PJTR_PJ_PROSC_EST_SHIP_DT.SHIP_PLN_PRICE IS '発注予定額';
COMMENT ON COLUMN PJTR_PJ_PROSC_EST_SHIP_DT.SHIP_PLN_PRICE_CUR IS '発注予定額通貨';
COMMENT ON COLUMN PJTR_PJ_PROSC_EST_SHIP_DT.EST_ARI_FLG IS '見積有フラグ';
COMMENT ON COLUMN PJTR_PJ_PROSC_EST_SHIP_DT.CONT_ARI_FLG IS '契約有フラグ';
COMMENT ON COLUMN PJTR_PJ_PROSC_EST_SHIP_DT.DEL_FLG IS '削除フラグ';
COMMENT ON COLUMN PJTR_PJ_PROSC_EST_SHIP_DT.REG_USR_ID IS '登録ユーザID';
COMMENT ON COLUMN PJTR_PJ_PROSC_EST_SHIP_DT.REG_PGM_ID IS '登録プログラムID';
COMMENT ON COLUMN PJTR_PJ_PROSC_EST_SHIP_DT.REG_TS IS '登録タイムスタンプ';
COMMENT ON COLUMN PJTR_PJ_PROSC_EST_SHIP_DT.UPD_USR_ID IS '更新ユーザID';
COMMENT ON COLUMN PJTR_PJ_PROSC_EST_SHIP_DT.UPD_PGM_ID IS '更新プログラムID';
COMMENT ON COLUMN PJTR_PJ_PROSC_EST_SHIP_DT.UPD_TS IS '更新タイムスタンプ';
COMMENT ON COLUMN PJTR_PJ_PROSC_EST_SHIP_DT.VER_NO IS 'バージョン番号';

-- ユニークインデックス用DDL

-- インデックス用DDL
CREATE INDEX IX1_PJTR_PJ_PROSC_EST_SHIP_DT ON PJTR_PJ_PROSC_EST_SHIP_DT (
    PRJ_CD ,
    SUPP_CD 
);

