-- テーブル用DDL
DROP TABLE PJTR_PJ_RPT_BSDT_MNG CASCADE CONSTRAINTS;

CREATE TABLE PJTR_PJ_RPT_BSDT_MNG
(
    PRJ_CD                         CHAR(10) NOT NULL ,
    PREV_RPT_BSDT                  DATE ,
    THIS_RPT_BSDT                  DATE ,
    SI_DEAL_CD                     CHAR(10) NOT NULL ,
    THIS_ENT_CLOSE_DT              DATE ,
    DEL_FLG                        CHAR(1) DEFAULT '0' NOT NULL ,
    REG_USR_ID                     NUMBER(10) NOT NULL ,
    REG_PGM_ID                     CHAR(11) NOT NULL ,
    REG_TS                         TIMESTAMP(3) NOT NULL ,
    UPD_USR_ID                     NUMBER(10) NOT NULL ,
    UPD_PGM_ID                     CHAR(11) NOT NULL ,
    UPD_TS                         TIMESTAMP(3) NOT NULL ,
    VER_NO                         NUMBER(10) DEFAULT 0 NOT NULL
);
ALTER TABLE PJTR_PJ_RPT_BSDT_MNG ADD CONSTRAINT PK_PJTR_PJ_RPT_BSDT_MNG PRIMARY KEY (PRJ_CD ) ;

COMMENT ON TABLE PJTR_PJ_RPT_BSDT_MNG IS '報告基準日管理トラン(ver.0.3)';
COMMENT ON COLUMN PJTR_PJ_RPT_BSDT_MNG.PRJ_CD IS 'プロジェクトコード';
COMMENT ON COLUMN PJTR_PJ_RPT_BSDT_MNG.PREV_RPT_BSDT IS '前回報告基準日';
COMMENT ON COLUMN PJTR_PJ_RPT_BSDT_MNG.THIS_RPT_BSDT IS '今回報告基準日';
COMMENT ON COLUMN PJTR_PJ_RPT_BSDT_MNG.SI_DEAL_CD IS 'SI案件コード';
COMMENT ON COLUMN PJTR_PJ_RPT_BSDT_MNG.THIS_ENT_CLOSE_DT IS '今回入力締日';
COMMENT ON COLUMN PJTR_PJ_RPT_BSDT_MNG.DEL_FLG IS '削除フラグ';
COMMENT ON COLUMN PJTR_PJ_RPT_BSDT_MNG.REG_USR_ID IS '登録ユーザID';
COMMENT ON COLUMN PJTR_PJ_RPT_BSDT_MNG.REG_PGM_ID IS '登録プログラムID';
COMMENT ON COLUMN PJTR_PJ_RPT_BSDT_MNG.REG_TS IS '登録タイムスタンプ';
COMMENT ON COLUMN PJTR_PJ_RPT_BSDT_MNG.UPD_USR_ID IS '更新ユーザID';
COMMENT ON COLUMN PJTR_PJ_RPT_BSDT_MNG.UPD_PGM_ID IS '更新プログラムID';
COMMENT ON COLUMN PJTR_PJ_RPT_BSDT_MNG.UPD_TS IS '更新タイムスタンプ';
COMMENT ON COLUMN PJTR_PJ_RPT_BSDT_MNG.VER_NO IS 'バージョン番号';

-- ユニークインデックス用DDL

-- インデックス用DDL
