-- テーブル用DDL
DROP TABLE PJTR_PJ_PROSC_EST_EXP_DT CASCADE CONSTRAINTS;

CREATE TABLE PJTR_PJ_PROSC_EST_EXP_DT
(
    PRJ_CD                         CHAR(10) NOT NULL ,
    PROSC_VER                      NUMBER(3) NOT NULL ,
    SPD_TYP_SEQ                    NUMBER(5) NOT NULL ,
    PROSC_YYMM                     CHAR(6) NOT NULL ,
    SPD_TYP_ID                     NUMBER(15) NOT NULL ,
    EXP_PRICE                      NUMBER(12) DEFAULT 0 NOT NULL ,
    DEL_FLG                        CHAR(1) DEFAULT '0' NOT NULL ,
    REG_USR_ID                     NUMBER(10) NOT NULL ,
    REG_PGM_ID                     CHAR(11) NOT NULL ,
    REG_TS                         TIMESTAMP(3) NOT NULL ,
    UPD_USR_ID                     NUMBER(10) NOT NULL ,
    UPD_PGM_ID                     CHAR(11) NOT NULL ,
    UPD_TS                         TIMESTAMP(3) NOT NULL ,
    VER_NO                         NUMBER(10) DEFAULT 0 NOT NULL
);
ALTER TABLE PJTR_PJ_PROSC_EST_EXP_DT ADD CONSTRAINT PK_PJTR_PJ_PROSC_EST_EXP_DT PRIMARY KEY (PRJ_CD, PROSC_VER, SPD_TYP_SEQ, PROSC_YYMM ) ;

COMMENT ON TABLE PJTR_PJ_PROSC_EST_EXP_DT IS '採算原価見積経費明細トラン(ver.0.7)';
COMMENT ON COLUMN PJTR_PJ_PROSC_EST_EXP_DT.PRJ_CD IS 'プロジェクトコード';
COMMENT ON COLUMN PJTR_PJ_PROSC_EST_EXP_DT.PROSC_VER IS '採算原価バージョン';
COMMENT ON COLUMN PJTR_PJ_PROSC_EST_EXP_DT.SPD_TYP_SEQ IS '支出タイプシーケンス';
COMMENT ON COLUMN PJTR_PJ_PROSC_EST_EXP_DT.PROSC_YYMM IS '採算原価年月';
COMMENT ON COLUMN PJTR_PJ_PROSC_EST_EXP_DT.SPD_TYP_ID IS '支出タイプID';
COMMENT ON COLUMN PJTR_PJ_PROSC_EST_EXP_DT.EXP_PRICE IS '経費額';
COMMENT ON COLUMN PJTR_PJ_PROSC_EST_EXP_DT.DEL_FLG IS '削除フラグ';
COMMENT ON COLUMN PJTR_PJ_PROSC_EST_EXP_DT.REG_USR_ID IS '登録ユーザID';
COMMENT ON COLUMN PJTR_PJ_PROSC_EST_EXP_DT.REG_PGM_ID IS '登録プログラムID';
COMMENT ON COLUMN PJTR_PJ_PROSC_EST_EXP_DT.REG_TS IS '登録タイムスタンプ';
COMMENT ON COLUMN PJTR_PJ_PROSC_EST_EXP_DT.UPD_USR_ID IS '更新ユーザID';
COMMENT ON COLUMN PJTR_PJ_PROSC_EST_EXP_DT.UPD_PGM_ID IS '更新プログラムID';
COMMENT ON COLUMN PJTR_PJ_PROSC_EST_EXP_DT.UPD_TS IS '更新タイムスタンプ';
COMMENT ON COLUMN PJTR_PJ_PROSC_EST_EXP_DT.VER_NO IS 'バージョン番号';

-- ユニークインデックス用DDL

-- インデックス用DDL
CREATE INDEX IX1_PJTR_PJ_PROSC_EST_EXP_DT ON PJTR_PJ_PROSC_EST_EXP_DT (
    PRJ_CD ,
    SPD_TYP_ID 
);

