-- テーブル用DDL
DROP TABLE PJTR_PJ_PROSC_EST CASCADE CONSTRAINTS;

CREATE TABLE PJTR_PJ_PROSC_EST
(
    PRJ_CD                         CHAR(10) NOT NULL ,
    PROSC_VER                      NUMBER(3) NOT NULL ,
    PROSC_VER_NM                   VARCHAR2(150) NOT NULL ,
    PROS_EST_SEG                   CHAR(2) NOT NULL ,
    PROS_EST_MK_DT                 DATE ,
    PROS_EST_EMP_CD                VARCHAR2(30) ,
    PROS_EST_VLD_DT                DATE ,
    PROS_BASELINE_VER              NUMBER(3) ,
    PROS_BASELINE_FLG              CHAR(1) DEFAULT '0' NOT NULL ,
    PROS_BASELINE_VLD_FLG          CHAR(1) DEFAULT '0' NOT NULL ,
    PROS_FXD_FLG                   CHAR(1) DEFAULT '0' NOT NULL ,
    PROS_LNK_FLG                   CHAR(1) DEFAULT '0' NOT NULL ,
    PROS_VLD_FLG                   CHAR(1) DEFAULT '0' NOT NULL ,
    PROS_SND_DT                    DATE ,
    PROS_PRT_NUM                   NUMBER(2) DEFAULT 0 NOT NULL ,
    PROS_LST_PRT_DT                DATE ,
    PROS_STF_COST_PRICE            NUMBER(12) DEFAULT 0 NOT NULL ,
    PROS_STF_OPE_PLN_TM            NUMBER(10,2) DEFAULT 0 NOT NULL ,
    PROS_DP_COST_PRICE             NUMBER(12) DEFAULT 0 NOT NULL ,
    PROS_DP_OPE_PLN_TM             NUMBER(10,2) DEFAULT 0 NOT NULL ,
    PROS_BLKODR_PRICE              NUMBER(12) DEFAULT 0 NOT NULL ,
    PROS_EXP_PRICE                 NUMBER(12) DEFAULT 0 NOT NULL ,
    PROS_CON_PRICE                 NUMBER(12) NOT NULL ,
    PRJ_PROSC_SUM_PRICE            NUMBER(12) ,
    PRJ_SYS_NM                     VARCHAR2(150) NOT NULL ,
    PRJ_SYS_SHORTNM                VARCHAR2(150) NOT NULL ,
    CUTOVR_OPE_PLN_DT              DATE NOT NULL ,
    PRJ_CONT_PLN_DT                DATE NOT NULL ,
    PRJ_SEG                        CHAR(3) NOT NULL ,
    PRJ_SPQLY_SEG                  CHAR(2) ,
    PRJ_IMPTT_FLG                  CHAR(1) DEFAULT '0' NOT NULL ,
    CUST_REQ_DEVTRM                DATE ,
    DEV_TRM                        VARCHAR2(150) ,
    PRJ_SYS_SMRY                   VARCHAR2(600) ,
    PRJ_DEV_TAR_RANGE              VARCHAR2(600) ,
    PRJ_EST_INDI_STMT_REQIM        VARCHAR2(600) ,
    PRJ_TMPEST_RSN                 VARCHAR2(600) ,
    PRJ_EST_COND_SEG               VARCHAR2(3) ,
    PRJ_EST_COND_OTHER             VARCHAR2(150) ,
    PRJ_ACCEPT_COND_SEG            VARCHAR2(3) ,
    PRJ_ACCEPT_COND_OTHER          VARCHAR2(150) ,
    PRJ_ACCEPT_LOC_SEG             VARCHAR2(3) ,
    PRJ_ACCEPT_LOC_OTHER           VARCHAR2(150) ,
    PRJ_ACCEPT_PSN_NM              VARCHAR2(150) ,
    PRJ_GRN_TRM                    VARCHAR2(3) ,
    PRJ_GRN_TRM_OTHER              VARCHAR2(150) ,
    PROD_RDD_FLG                   CHAR(1) DEFAULT '0' NOT NULL ,
    PROD_BDD_FLG                   CHAR(1) DEFAULT '0' NOT NULL ,
    SEIKA_DB_DOC_FLG               CHAR(1) DEFAULT '0' NOT NULL ,
    PROD_DT_DOC_FLG                CHAR(1) DEFAULT '0' NOT NULL ,
    SEIKA_PG_DOC_FLG               CHAR(1) DEFAULT '0' NOT NULL ,
    SEIKA_SRC_PG_FLG               CHAR(1) DEFAULT '0' NOT NULL ,
    SEIKA_OBJ_FLG                  CHAR(1) DEFAULT '0' NOT NULL ,
    PROD_UNT_TST_RES_RPT_FLG       CHAR(1) DEFAULT '0' NOT NULL ,
    PROD_INTEG_TST_RES_RPT_FLG     CHAR(1) DEFAULT '0' NOT NULL ,
    PROD_SYS_TST_RES_RPT_FLG       CHAR(1) DEFAULT '0' NOT NULL ,
    PROD_TUN_RES_RPT_FLG           CHAR(1) DEFAULT '0' NOT NULL ,
    SEIKA_SOSA_MNU_FLG             CHAR(1) DEFAULT '0' NOT NULL ,
    SEIKA_UNYO_MNU_FLG             CHAR(1) DEFAULT '0' NOT NULL ,
    PROD_OTHER_1                   VARCHAR2(150) ,
    PROD_OTHER_2                   VARCHAR2(150) ,
    USE_MDL_SERV_SEG               VARCHAR2(3) ,
    USE_MDL_SERV_SEG_OTHER         VARCHAR2(150) ,
    USE_MDL_CLI_SEG                VARCHAR2(3) ,
    USE_MDL_CLI_SEG_OTHER          VARCHAR2(150) ,
    USE_MDL_DBMS_SEG               VARCHAR2(4) ,
    USE_MDL_DBMS_SEG_OTHER         VARCHAR2(150) ,
    USE_MDL_DEV_LANG_SEG           VARCHAR2(4) ,
    USE_MDL_DEV_LANG_SEG_OTHER     VARCHAR2(150) ,
    USE_MDL_DEV_TOOL_SEG           VARCHAR2(4) ,
    USE_MDL_DEV_TOOL_SEG_OTHER     VARCHAR2(150) ,
    ATD_DEAL_ODRSK_ACL_FLG         CHAR(1) DEFAULT '0' NOT NULL ,
    ATD_EST_LST_BC_FLG             CHAR(1) DEFAULT '0' NOT NULL ,
    ATD_EST_A1A2A3_FLG             CHAR(1) DEFAULT '0' NOT NULL ,
    ATD_EST_SPEC_FLG               CHAR(1) DEFAULT '0' NOT NULL ,
    ATD_EST_WREQ_ADD_SHIP_SPEC     CHAR(1) DEFAULT '0' NOT NULL ,
    MSG_MTR_ETC_CMT                VARCHAR2(600) ,
    BUSI_PROC_DT                   DATE NOT NULL ,
    BUSI_PROC_HMS                  TIMESTAMP(3) NOT NULL ,
    DEL_FLG                        CHAR(1) DEFAULT '0' NOT NULL ,
    REG_USR_ID                     NUMBER(10) NOT NULL ,
    REG_PGM_ID                     CHAR(11) NOT NULL ,
    REG_TS                         TIMESTAMP(3) NOT NULL ,
    UPD_USR_ID                     NUMBER(10) NOT NULL ,
    UPD_PGM_ID                     CHAR(11) NOT NULL ,
    UPD_TS                         TIMESTAMP(3) NOT NULL ,
    VER_NO                         NUMBER(10) DEFAULT 0 NOT NULL
);
ALTER TABLE PJTR_PJ_PROSC_EST ADD CONSTRAINT PK_PJTR_PJ_PROSC_EST PRIMARY KEY (PRJ_CD, PROSC_VER ) ;

COMMENT ON TABLE PJTR_PJ_PROSC_EST IS '採算原価見積トラン(ver.1.01)';
COMMENT ON COLUMN PJTR_PJ_PROSC_EST.PRJ_CD IS 'プロジェクトコード';
COMMENT ON COLUMN PJTR_PJ_PROSC_EST.PROSC_VER IS '採算原価バージョン';
COMMENT ON COLUMN PJTR_PJ_PROSC_EST.PROSC_VER_NM IS '採算原価バージョン名';
COMMENT ON COLUMN PJTR_PJ_PROSC_EST.PROS_EST_SEG IS '採算見積区分';
COMMENT ON COLUMN PJTR_PJ_PROSC_EST.PROS_EST_MK_DT IS '採算見積作成日';
COMMENT ON COLUMN PJTR_PJ_PROSC_EST.PROS_EST_EMP_CD IS '採算見積従業員コード';
COMMENT ON COLUMN PJTR_PJ_PROSC_EST.PROS_EST_VLD_DT IS '採算見積有効日';
COMMENT ON COLUMN PJTR_PJ_PROSC_EST.PROS_BASELINE_VER IS '採算ベースラインバージョン';
COMMENT ON COLUMN PJTR_PJ_PROSC_EST.PROS_BASELINE_FLG IS '採算ベースラインフラグ';
COMMENT ON COLUMN PJTR_PJ_PROSC_EST.PROS_BASELINE_VLD_FLG IS '採算ベースライン有効フラグ';
COMMENT ON COLUMN PJTR_PJ_PROSC_EST.PROS_FXD_FLG IS '採算確定フラグ';
COMMENT ON COLUMN PJTR_PJ_PROSC_EST.PROS_LNK_FLG IS '採算連携フラグ';
COMMENT ON COLUMN PJTR_PJ_PROSC_EST.PROS_VLD_FLG IS '採算有効フラグ';
COMMENT ON COLUMN PJTR_PJ_PROSC_EST.PROS_SND_DT IS '採算送信日';
COMMENT ON COLUMN PJTR_PJ_PROSC_EST.PROS_PRT_NUM IS '採算印刷数';
COMMENT ON COLUMN PJTR_PJ_PROSC_EST.PROS_LST_PRT_DT IS '採算最終印刷日';
COMMENT ON COLUMN PJTR_PJ_PROSC_EST.PROS_STF_COST_PRICE IS '採算社員原価額';
COMMENT ON COLUMN PJTR_PJ_PROSC_EST.PROS_STF_OPE_PLN_TM IS '採算社員稼働予定時間';
COMMENT ON COLUMN PJTR_PJ_PROSC_EST.PROS_DP_COST_PRICE IS '採算派遣原価額';
COMMENT ON COLUMN PJTR_PJ_PROSC_EST.PROS_DP_OPE_PLN_TM IS '採算派遣稼働予定時間';
COMMENT ON COLUMN PJTR_PJ_PROSC_EST.PROS_BLKODR_PRICE IS '採算一括発注額';
COMMENT ON COLUMN PJTR_PJ_PROSC_EST.PROS_EXP_PRICE IS '採算経費額';
COMMENT ON COLUMN PJTR_PJ_PROSC_EST.PROS_CON_PRICE IS '採算コンティンジェンシー額';
COMMENT ON COLUMN PJTR_PJ_PROSC_EST.PRJ_PROSC_SUM_PRICE IS 'プロジェクト採算原価合計額';
COMMENT ON COLUMN PJTR_PJ_PROSC_EST.PRJ_SYS_NM IS 'プロジェクトシステム名';
COMMENT ON COLUMN PJTR_PJ_PROSC_EST.PRJ_SYS_SHORTNM IS 'プロジェクトシステム略名';
COMMENT ON COLUMN PJTR_PJ_PROSC_EST.CUTOVR_OPE_PLN_DT IS '本番稼働予定日';
COMMENT ON COLUMN PJTR_PJ_PROSC_EST.PRJ_CONT_PLN_DT IS 'プロジェクト成約予定日';
COMMENT ON COLUMN PJTR_PJ_PROSC_EST.PRJ_SEG IS 'プロジェクト区分';
COMMENT ON COLUMN PJTR_PJ_PROSC_EST.PRJ_SPQLY_SEG IS 'プロジェクト特性区分';
COMMENT ON COLUMN PJTR_PJ_PROSC_EST.PRJ_IMPTT_FLG IS 'プロジェクト重要フラグ';
COMMENT ON COLUMN PJTR_PJ_PROSC_EST.CUST_REQ_DEVTRM IS '顧客希望納期日';
COMMENT ON COLUMN PJTR_PJ_PROSC_EST.DEV_TRM IS '開発期間';
COMMENT ON COLUMN PJTR_PJ_PROSC_EST.PRJ_SYS_SMRY IS 'プロジェクトシステム概要';
COMMENT ON COLUMN PJTR_PJ_PROSC_EST.PRJ_DEV_TAR_RANGE IS 'プロジェクト開発対象範囲';
COMMENT ON COLUMN PJTR_PJ_PROSC_EST.PRJ_EST_INDI_STMT_REQIM IS 'プロジェクト見積必須記載要件';
COMMENT ON COLUMN PJTR_PJ_PROSC_EST.PRJ_TMPEST_RSN IS 'プロジェクト仮見積理由';
COMMENT ON COLUMN PJTR_PJ_PROSC_EST.PRJ_EST_COND_SEG IS 'プロジェクト見積条件区分';
COMMENT ON COLUMN PJTR_PJ_PROSC_EST.PRJ_EST_COND_OTHER IS 'プロジェクト見積条件その他';
COMMENT ON COLUMN PJTR_PJ_PROSC_EST.PRJ_ACCEPT_COND_SEG IS 'プロジェクト検収条件区分';
COMMENT ON COLUMN PJTR_PJ_PROSC_EST.PRJ_ACCEPT_COND_OTHER IS 'プロジェクト検収条件その他';
COMMENT ON COLUMN PJTR_PJ_PROSC_EST.PRJ_ACCEPT_LOC_SEG IS 'プロジェクト検収場所区分';
COMMENT ON COLUMN PJTR_PJ_PROSC_EST.PRJ_ACCEPT_LOC_OTHER IS 'プロジェクト検収場所その他';
COMMENT ON COLUMN PJTR_PJ_PROSC_EST.PRJ_ACCEPT_PSN_NM IS 'プロジェクト検収者名';
COMMENT ON COLUMN PJTR_PJ_PROSC_EST.PRJ_GRN_TRM IS 'プロジェクト瑕疵担保期間';
COMMENT ON COLUMN PJTR_PJ_PROSC_EST.PRJ_GRN_TRM_OTHER IS 'プロジェクト瑕疵担保期間その他';
COMMENT ON COLUMN PJTR_PJ_PROSC_EST.PROD_RDD_FLG IS '成果物要件定義書フラグ';
COMMENT ON COLUMN PJTR_PJ_PROSC_EST.PROD_BDD_FLG IS '成果物基本設計書フラグ';
COMMENT ON COLUMN PJTR_PJ_PROSC_EST.SEIKA_DB_DOC_FLG IS '成果物DB設計書フラグ';
COMMENT ON COLUMN PJTR_PJ_PROSC_EST.PROD_DT_DOC_FLG IS '成果物詳細設計書フラグ';
COMMENT ON COLUMN PJTR_PJ_PROSC_EST.SEIKA_PG_DOC_FLG IS '成果物プログラム設計書フラグ';
COMMENT ON COLUMN PJTR_PJ_PROSC_EST.SEIKA_SRC_PG_FLG IS '成果物ソースプログラムフラグ';
COMMENT ON COLUMN PJTR_PJ_PROSC_EST.SEIKA_OBJ_FLG IS '成果物オブジェクトフラグ';
COMMENT ON COLUMN PJTR_PJ_PROSC_EST.PROD_UNT_TST_RES_RPT_FLG IS '成果物単体テスト結果報告書フラグ';
COMMENT ON COLUMN PJTR_PJ_PROSC_EST.PROD_INTEG_TST_RES_RPT_FLG IS '成果物結合テスト結果報告書フラグ';
COMMENT ON COLUMN PJTR_PJ_PROSC_EST.PROD_SYS_TST_RES_RPT_FLG IS '成果物システムテスト結果報告書フラグ';
COMMENT ON COLUMN PJTR_PJ_PROSC_EST.PROD_TUN_RES_RPT_FLG IS '成果物チューニング結果報告書フラグ';
COMMENT ON COLUMN PJTR_PJ_PROSC_EST.SEIKA_SOSA_MNU_FLG IS '成果物操作マニュアルフラグ';
COMMENT ON COLUMN PJTR_PJ_PROSC_EST.SEIKA_UNYO_MNU_FLG IS '成果物運用マニュアルフラグ';
COMMENT ON COLUMN PJTR_PJ_PROSC_EST.PROD_OTHER_1 IS '成果物その他１';
COMMENT ON COLUMN PJTR_PJ_PROSC_EST.PROD_OTHER_2 IS '成果物その他２';
COMMENT ON COLUMN PJTR_PJ_PROSC_EST.USE_MDL_SERV_SEG IS '使用機種サーバ区分';
COMMENT ON COLUMN PJTR_PJ_PROSC_EST.USE_MDL_SERV_SEG_OTHER IS '使用機種サーバ区分その他';
COMMENT ON COLUMN PJTR_PJ_PROSC_EST.USE_MDL_CLI_SEG IS '使用機種クライアント区分';
COMMENT ON COLUMN PJTR_PJ_PROSC_EST.USE_MDL_CLI_SEG_OTHER IS '使用機種クライアント区分その他';
COMMENT ON COLUMN PJTR_PJ_PROSC_EST.USE_MDL_DBMS_SEG IS '使用機種DBMS区分';
COMMENT ON COLUMN PJTR_PJ_PROSC_EST.USE_MDL_DBMS_SEG_OTHER IS '使用機種DBMS区分その他';
COMMENT ON COLUMN PJTR_PJ_PROSC_EST.USE_MDL_DEV_LANG_SEG IS '使用機種開発言語区分';
COMMENT ON COLUMN PJTR_PJ_PROSC_EST.USE_MDL_DEV_LANG_SEG_OTHER IS '使用機種開発言語区分その他';
COMMENT ON COLUMN PJTR_PJ_PROSC_EST.USE_MDL_DEV_TOOL_SEG IS '使用機種開発ツール区分';
COMMENT ON COLUMN PJTR_PJ_PROSC_EST.USE_MDL_DEV_TOOL_SEG_OTHER IS '使用機種開発ツール区分その他';
COMMENT ON COLUMN PJTR_PJ_PROSC_EST.ATD_DEAL_ODRSK_ACL_FLG IS '添付資料案件別受注リスク評価チェックリストフラグ';
COMMENT ON COLUMN PJTR_PJ_PROSC_EST.ATD_EST_LST_BC_FLG IS '添付資料見積表BCフラグ';
COMMENT ON COLUMN PJTR_PJ_PROSC_EST.ATD_EST_A1A2A3_FLG IS '添付資料見積書A1A2A3フラグ';
COMMENT ON COLUMN PJTR_PJ_PROSC_EST.ATD_EST_SPEC_FLG IS '添付資料見積仕様書フラグ';
COMMENT ON COLUMN PJTR_PJ_PROSC_EST.ATD_EST_WREQ_ADD_SHIP_SPEC IS '添付資料見積依頼書兼発注仕様書';
COMMENT ON COLUMN PJTR_PJ_PROSC_EST.MSG_MTR_ETC_CMT IS '連絡事項等コメント';
COMMENT ON COLUMN PJTR_PJ_PROSC_EST.BUSI_PROC_DT IS '業務処理日付';
COMMENT ON COLUMN PJTR_PJ_PROSC_EST.BUSI_PROC_HMS IS '業務処理日時';
COMMENT ON COLUMN PJTR_PJ_PROSC_EST.DEL_FLG IS '削除フラグ';
COMMENT ON COLUMN PJTR_PJ_PROSC_EST.REG_USR_ID IS '登録ユーザID';
COMMENT ON COLUMN PJTR_PJ_PROSC_EST.REG_PGM_ID IS '登録プログラムID';
COMMENT ON COLUMN PJTR_PJ_PROSC_EST.REG_TS IS '登録タイムスタンプ';
COMMENT ON COLUMN PJTR_PJ_PROSC_EST.UPD_USR_ID IS '更新ユーザID';
COMMENT ON COLUMN PJTR_PJ_PROSC_EST.UPD_PGM_ID IS '更新プログラムID';
COMMENT ON COLUMN PJTR_PJ_PROSC_EST.UPD_TS IS '更新タイムスタンプ';
COMMENT ON COLUMN PJTR_PJ_PROSC_EST.VER_NO IS 'バージョン番号';

-- ユニークインデックス用DDL

-- インデックス用DDL
CREATE INDEX IX1_PJTR_PJ_PROSC_EST ON PJTR_PJ_PROSC_EST (
    PROS_EST_EMP_CD 
);

CREATE INDEX IX2_PJTR_PJ_PROSC_EST ON PJTR_PJ_PROSC_EST (
    PROS_LNK_FLG 
);

