-- テーブル用DDL
DROP TABLE PJTR_PJ_PROP_CA_SND_HIST CASCADE CONSTRAINTS;

CREATE TABLE PJTR_PJ_PROP_CA_SND_HIST
(
    PROP_PRJ_CD                    CHAR(10) NOT NULL ,
    PROP_CA_PRICE                  NUMBER(12) DEFAULT 0 NOT NULL ,
    PROP_CST_LMT_PRICE             NUMBER(12) DEFAULT 0 NOT NULL ,
    DEL_FLG                        CHAR(1) DEFAULT '0' NOT NULL ,
    REG_USR_ID                     NUMBER(10) NOT NULL ,
    REG_PGM_ID                     CHAR(11) NOT NULL ,
    REG_TS                         TIMESTAMP(3) NOT NULL ,
    UPD_USR_ID                     NUMBER(10) NOT NULL ,
    UPD_PGM_ID                     CHAR(11) NOT NULL ,
    UPD_TS                         TIMESTAMP(3) NOT NULL ,
    VER_NO                         NUMBER(10) DEFAULT 0 NOT NULL
);
ALTER TABLE PJTR_PJ_PROP_CA_SND_HIST ADD CONSTRAINT PK_PJTR_PJ_PROP_CA_SND_HIST PRIMARY KEY (PROP_PRJ_CD ) ;

COMMENT ON TABLE PJTR_PJ_PROP_CA_SND_HIST IS '提案コストアラート送信履歴トラン(ver.0.5)';
COMMENT ON COLUMN PJTR_PJ_PROP_CA_SND_HIST.PROP_PRJ_CD IS '提案プロジェクトコード';
COMMENT ON COLUMN PJTR_PJ_PROP_CA_SND_HIST.PROP_CA_PRICE IS '提案コストアラート額';
COMMENT ON COLUMN PJTR_PJ_PROP_CA_SND_HIST.PROP_CST_LMT_PRICE IS '提案コスト限度額';
COMMENT ON COLUMN PJTR_PJ_PROP_CA_SND_HIST.DEL_FLG IS '削除フラグ';
COMMENT ON COLUMN PJTR_PJ_PROP_CA_SND_HIST.REG_USR_ID IS '登録ユーザID';
COMMENT ON COLUMN PJTR_PJ_PROP_CA_SND_HIST.REG_PGM_ID IS '登録プログラムID';
COMMENT ON COLUMN PJTR_PJ_PROP_CA_SND_HIST.REG_TS IS '登録タイムスタンプ';
COMMENT ON COLUMN PJTR_PJ_PROP_CA_SND_HIST.UPD_USR_ID IS '更新ユーザID';
COMMENT ON COLUMN PJTR_PJ_PROP_CA_SND_HIST.UPD_PGM_ID IS '更新プログラムID';
COMMENT ON COLUMN PJTR_PJ_PROP_CA_SND_HIST.UPD_TS IS '更新タイムスタンプ';
COMMENT ON COLUMN PJTR_PJ_PROP_CA_SND_HIST.VER_NO IS 'バージョン番号';

-- ユニークインデックス用DDL

-- インデックス用DDL
