-- テーブル用DDL
DROP TABLE PJTR_PJ_SI_DEAL_RESRC CASCADE CONSTRAINTS;

CREATE TABLE PJTR_PJ_SI_DEAL_RESRC
(
    SI_DEAL_CD                     CHAR(10) NOT NULL ,
    SI_RESRC_EMP_CD                VARCHAR2(30) NOT NULL ,
    SI_RESRC_STR_DT                DATE NOT NULL ,
    SI_RESRC_END_DT                DATE NOT NULL ,
    SI_RESRC_ROLE                  CHAR(2) NOT NULL ,
    DEL_FLG                        CHAR(1) DEFAULT '0' NOT NULL ,
    REG_USR_ID                     NUMBER(10) NOT NULL ,
    REG_PGM_ID                     CHAR(11) NOT NULL ,
    REG_TS                         TIMESTAMP(3) NOT NULL ,
    UPD_USR_ID                     NUMBER(10) NOT NULL ,
    UPD_PGM_ID                     CHAR(11) NOT NULL ,
    UPD_TS                         TIMESTAMP(3) NOT NULL ,
    VER_NO                         NUMBER(10) DEFAULT 0 NOT NULL
);
ALTER TABLE PJTR_PJ_SI_DEAL_RESRC ADD CONSTRAINT PK_PJTR_PJ_SI_DEAL_RESRC PRIMARY KEY (SI_DEAL_CD, SI_RESRC_EMP_CD, SI_RESRC_STR_DT, SI_RESRC_END_DT, SI_RESRC_ROLE ) ;

COMMENT ON TABLE PJTR_PJ_SI_DEAL_RESRC IS 'SI案件リソーストラン(ver.0.6)';
COMMENT ON COLUMN PJTR_PJ_SI_DEAL_RESRC.SI_DEAL_CD IS 'SI案件コード';
COMMENT ON COLUMN PJTR_PJ_SI_DEAL_RESRC.SI_RESRC_EMP_CD IS 'SIリソース従業員コード';
COMMENT ON COLUMN PJTR_PJ_SI_DEAL_RESRC.SI_RESRC_STR_DT IS 'SIリソース開始日';
COMMENT ON COLUMN PJTR_PJ_SI_DEAL_RESRC.SI_RESRC_END_DT IS 'SIリソース終了日';
COMMENT ON COLUMN PJTR_PJ_SI_DEAL_RESRC.SI_RESRC_ROLE IS 'SIリソースロール';
COMMENT ON COLUMN PJTR_PJ_SI_DEAL_RESRC.DEL_FLG IS '削除フラグ';
COMMENT ON COLUMN PJTR_PJ_SI_DEAL_RESRC.REG_USR_ID IS '登録ユーザID';
COMMENT ON COLUMN PJTR_PJ_SI_DEAL_RESRC.REG_PGM_ID IS '登録プログラムID';
COMMENT ON COLUMN PJTR_PJ_SI_DEAL_RESRC.REG_TS IS '登録タイムスタンプ';
COMMENT ON COLUMN PJTR_PJ_SI_DEAL_RESRC.UPD_USR_ID IS '更新ユーザID';
COMMENT ON COLUMN PJTR_PJ_SI_DEAL_RESRC.UPD_PGM_ID IS '更新プログラムID';
COMMENT ON COLUMN PJTR_PJ_SI_DEAL_RESRC.UPD_TS IS '更新タイムスタンプ';
COMMENT ON COLUMN PJTR_PJ_SI_DEAL_RESRC.VER_NO IS 'バージョン番号';

-- ユニークインデックス用DDL

-- インデックス用DDL
