-- テーブル用DDL
DROP TABLE PJTR_PJ_SHIP_RSLT CASCADE CONSTRAINTS;

CREATE TABLE PJTR_PJ_SHIP_RSLT
(
    PRJ_CD                         CHAR(10) NOT NULL ,
    SHIP_MNG_NO                    CHAR(3) NOT NULL ,
    INCI_DT                        DATE NOT NULL ,
    INCI_TMS                       NUMBER(3) NOT NULL ,
    ENT_YYMM                       CHAR(6) NOT NULL ,
    SUPP_CD                        VARCHAR2(30) ,
    SHIP_RSLT_PRICE                NUMBER(12) NOT NULL ,
    DEL_FLG                        CHAR(1) DEFAULT '0' NOT NULL ,
    REG_USR_ID                     NUMBER(10) NOT NULL ,
    REG_PGM_ID                     CHAR(11) NOT NULL ,
    REG_TS                         TIMESTAMP(3) NOT NULL ,
    UPD_USR_ID                     NUMBER(10) NOT NULL ,
    UPD_PGM_ID                     CHAR(11) NOT NULL ,
    UPD_TS                         TIMESTAMP(3) NOT NULL ,
    VER_NO                         NUMBER(10) DEFAULT 0 NOT NULL
);
ALTER TABLE PJTR_PJ_SHIP_RSLT ADD CONSTRAINT PK_PJTR_PJ_SHIP_RSLT PRIMARY KEY (PRJ_CD, SHIP_MNG_NO, INCI_DT, INCI_TMS, ENT_YYMM ) ;

COMMENT ON TABLE PJTR_PJ_SHIP_RSLT IS '発注実績トラン(ver.0.7)';
COMMENT ON COLUMN PJTR_PJ_SHIP_RSLT.PRJ_CD IS 'プロジェクトコード';
COMMENT ON COLUMN PJTR_PJ_SHIP_RSLT.SHIP_MNG_NO IS '発注管理番号';
COMMENT ON COLUMN PJTR_PJ_SHIP_RSLT.INCI_DT IS '発生日';
COMMENT ON COLUMN PJTR_PJ_SHIP_RSLT.INCI_TMS IS '発生回数';
COMMENT ON COLUMN PJTR_PJ_SHIP_RSLT.ENT_YYMM IS '算入年月';
COMMENT ON COLUMN PJTR_PJ_SHIP_RSLT.SUPP_CD IS '発注先コード';
COMMENT ON COLUMN PJTR_PJ_SHIP_RSLT.SHIP_RSLT_PRICE IS '発注実績額';
COMMENT ON COLUMN PJTR_PJ_SHIP_RSLT.DEL_FLG IS '削除フラグ';
COMMENT ON COLUMN PJTR_PJ_SHIP_RSLT.REG_USR_ID IS '登録ユーザID';
COMMENT ON COLUMN PJTR_PJ_SHIP_RSLT.REG_PGM_ID IS '登録プログラムID';
COMMENT ON COLUMN PJTR_PJ_SHIP_RSLT.REG_TS IS '登録タイムスタンプ';
COMMENT ON COLUMN PJTR_PJ_SHIP_RSLT.UPD_USR_ID IS '更新ユーザID';
COMMENT ON COLUMN PJTR_PJ_SHIP_RSLT.UPD_PGM_ID IS '更新プログラムID';
COMMENT ON COLUMN PJTR_PJ_SHIP_RSLT.UPD_TS IS '更新タイムスタンプ';
COMMENT ON COLUMN PJTR_PJ_SHIP_RSLT.VER_NO IS 'バージョン番号';

-- ユニークインデックス用DDL

-- インデックス用DDL
CREATE INDEX IX1_PJTR_PJ_SHIP_RSLT ON PJTR_PJ_SHIP_RSLT (
    SUPP_CD 
);

CREATE INDEX IX2_PJTR_PJ_SHIP_RSLT ON PJTR_PJ_SHIP_RSLT (
    SHIP_RSLT_PRICE 
);

