-- テーブル用DDL
DROP TABLE PJTR_PJ_PROG_SLS CASCADE CONSTRAINTS;

CREATE TABLE PJTR_PJ_PROG_SLS
(
    PROG_UNT_NO                    CHAR(10) NOT NULL ,
    RCD_YYMM                       CHAR(6) NOT NULL ,
    INCI_DT                        DATE NOT NULL ,
    INCI_TMS                       NUMBER(3) NOT NULL ,
    SELLPRI_PRICE                  NUMBER(12) NOT NULL ,
    DEL_FLG                        CHAR(1) DEFAULT '0' NOT NULL ,
    REG_USR_ID                     NUMBER(10) NOT NULL ,
    REG_PGM_ID                     CHAR(11) NOT NULL ,
    REG_TS                         TIMESTAMP(3) NOT NULL ,
    UPD_USR_ID                     NUMBER(10) NOT NULL ,
    UPD_PGM_ID                     CHAR(11) NOT NULL ,
    UPD_TS                         TIMESTAMP(3) NOT NULL ,
    VER_NO                         NUMBER(10) DEFAULT 0 NOT NULL
);
ALTER TABLE PJTR_PJ_PROG_SLS ADD CONSTRAINT PK_PJTR_PJ_PROG_SLS PRIMARY KEY (PROG_UNT_NO, RCD_YYMM, INCI_DT, INCI_TMS ) ;

COMMENT ON TABLE PJTR_PJ_PROG_SLS IS '進行売上トラン(ver.0.3)';
COMMENT ON COLUMN PJTR_PJ_PROG_SLS.PROG_UNT_NO IS '進行単位番号';
COMMENT ON COLUMN PJTR_PJ_PROG_SLS.RCD_YYMM IS '計上年月';
COMMENT ON COLUMN PJTR_PJ_PROG_SLS.INCI_DT IS '発生日';
COMMENT ON COLUMN PJTR_PJ_PROG_SLS.INCI_TMS IS '発生回数';
COMMENT ON COLUMN PJTR_PJ_PROG_SLS.SELLPRI_PRICE IS '売価額';
COMMENT ON COLUMN PJTR_PJ_PROG_SLS.DEL_FLG IS '削除フラグ';
COMMENT ON COLUMN PJTR_PJ_PROG_SLS.REG_USR_ID IS '登録ユーザID';
COMMENT ON COLUMN PJTR_PJ_PROG_SLS.REG_PGM_ID IS '登録プログラムID';
COMMENT ON COLUMN PJTR_PJ_PROG_SLS.REG_TS IS '登録タイムスタンプ';
COMMENT ON COLUMN PJTR_PJ_PROG_SLS.UPD_USR_ID IS '更新ユーザID';
COMMENT ON COLUMN PJTR_PJ_PROG_SLS.UPD_PGM_ID IS '更新プログラムID';
COMMENT ON COLUMN PJTR_PJ_PROG_SLS.UPD_TS IS '更新タイムスタンプ';
COMMENT ON COLUMN PJTR_PJ_PROG_SLS.VER_NO IS 'バージョン番号';

-- ユニークインデックス用DDL

-- インデックス用DDL
