-- テーブル用DDL
DROP TABLE PJTW_PJ_OAN_ORGAN_MAP CASCADE CONSTRAINTS;

CREATE TABLE PJTW_PJ_OAN_ORGAN_MAP
(
    CONV_TAR_YYMM                  CHAR(6) NOT NULL ,
    OLD_DEPT_CD                    VARCHAR2(150) NOT NULL ,
    NEW_DEPT_CD                    VARCHAR2(150) ,
    ORGAN_REP_REF_DT               DATE ,
    DEL_FLG                        CHAR(1) DEFAULT '0' NOT NULL ,
    REG_USR_ID                     NUMBER(10) NOT NULL ,
    REG_PGM_ID                     CHAR(11) NOT NULL ,
    REG_TS                         TIMESTAMP(3) NOT NULL ,
    UPD_USR_ID                     NUMBER(10) NOT NULL ,
    UPD_PGM_ID                     CHAR(11) NOT NULL ,
    UPD_TS                         TIMESTAMP(3) NOT NULL ,
    VER_NO                         NUMBER(10) DEFAULT 0 NOT NULL
);
ALTER TABLE PJTW_PJ_OAN_ORGAN_MAP ADD CONSTRAINT PK_PJTW_PJ_OAN_ORGAN_MAP PRIMARY KEY (CONV_TAR_YYMM, OLD_DEPT_CD ) ;

COMMENT ON TABLE PJTW_PJ_OAN_ORGAN_MAP IS '新旧組織マッピングワーク(ver.0.1)';
COMMENT ON COLUMN PJTW_PJ_OAN_ORGAN_MAP.CONV_TAR_YYMM IS '変換対象年月';
COMMENT ON COLUMN PJTW_PJ_OAN_ORGAN_MAP.OLD_DEPT_CD IS '旧部課コード';
COMMENT ON COLUMN PJTW_PJ_OAN_ORGAN_MAP.NEW_DEPT_CD IS '新部課コード';
COMMENT ON COLUMN PJTW_PJ_OAN_ORGAN_MAP.ORGAN_REP_REF_DT IS '組織付替反映日';
COMMENT ON COLUMN PJTW_PJ_OAN_ORGAN_MAP.DEL_FLG IS '削除フラグ';
COMMENT ON COLUMN PJTW_PJ_OAN_ORGAN_MAP.REG_USR_ID IS '登録ユーザID';
COMMENT ON COLUMN PJTW_PJ_OAN_ORGAN_MAP.REG_PGM_ID IS '登録プログラムID';
COMMENT ON COLUMN PJTW_PJ_OAN_ORGAN_MAP.REG_TS IS '登録タイムスタンプ';
COMMENT ON COLUMN PJTW_PJ_OAN_ORGAN_MAP.UPD_USR_ID IS '更新ユーザID';
COMMENT ON COLUMN PJTW_PJ_OAN_ORGAN_MAP.UPD_PGM_ID IS '更新プログラムID';
COMMENT ON COLUMN PJTW_PJ_OAN_ORGAN_MAP.UPD_TS IS '更新タイムスタンプ';
COMMENT ON COLUMN PJTW_PJ_OAN_ORGAN_MAP.VER_NO IS 'バージョン番号';

-- ユニークインデックス用DDL

-- インデックス用DDL
