-- テーブル用DDL
DROP TABLE PJTW_PJ_PRJ_ALNOT CASCADE CONSTRAINTS;

CREATE TABLE PJTW_PJ_PRJ_ALNOT
(
    ALERT_SEG                      CHAR(1) NOT NULL ,
    PRJ_CD                         CHAR(10) NOT NULL ,
    EMP_CD                         VARCHAR2(30) NOT NULL ,
    PRJ_NM                         VARCHAR2(90) NOT NULL ,
    EMP_EMAIL                      VARCHAR2(240) NOT NULL ,
    DELAY_DAYS                     NUMBER(4) ,
    SV                             NUMBER(10,2) DEFAULT 0 NOT NULL ,
    CV_PRICE                       NUMBER(12) DEFAULT 0 NOT NULL ,
    SPI                            NUMBER(6,4) DEFAULT 0 NOT NULL ,
    CPI                            NUMBER(6,4) DEFAULT 0 NOT NULL ,
    SI_DEAL_CD                     CHAR(10) ,
    SI_DEAL_NM                     VARCHAR2(150) ,
    PRJ_STR_DT                     DATE ,
    PRJ_END_DT                     DATE ,
    PROSC_EST_PRICE                NUMBER(12) DEFAULT 0 ,
    LST_EST_COST                   NUMBER(12) DEFAULT 0 ,
    EGY_CHG_NM                     VARCHAR2(225) ,
    PRJ_MNG_NM                     VARCHAR2(225) ,
    DEL_FLG                        CHAR(1) DEFAULT '0' NOT NULL ,
    REG_USR_ID                     NUMBER(10) NOT NULL ,
    REG_PGM_ID                     CHAR(11) NOT NULL ,
    REG_TS                         TIMESTAMP(3) NOT NULL ,
    UPD_USR_ID                     NUMBER(10) NOT NULL ,
    UPD_PGM_ID                     CHAR(11) NOT NULL ,
    UPD_TS                         TIMESTAMP(3) NOT NULL ,
    VER_NO                         NUMBER(10) DEFAULT 0 NOT NULL
);
ALTER TABLE PJTW_PJ_PRJ_ALNOT ADD CONSTRAINT PK_PJTW_PJ_PRJ_ALNOT PRIMARY KEY (ALERT_SEG, PRJ_CD, EMP_CD ) ;

COMMENT ON TABLE PJTW_PJ_PRJ_ALNOT IS 'プロジェクトアラート通知情報ワーク(ver.1.02)';
COMMENT ON COLUMN PJTW_PJ_PRJ_ALNOT.ALERT_SEG IS 'アラート区分';
COMMENT ON COLUMN PJTW_PJ_PRJ_ALNOT.PRJ_CD IS 'プロジェクトコード';
COMMENT ON COLUMN PJTW_PJ_PRJ_ALNOT.EMP_CD IS '従業員コード';
COMMENT ON COLUMN PJTW_PJ_PRJ_ALNOT.PRJ_NM IS 'プロジェクト名';
COMMENT ON COLUMN PJTW_PJ_PRJ_ALNOT.EMP_EMAIL IS '従業員メールアドレス';
COMMENT ON COLUMN PJTW_PJ_PRJ_ALNOT.DELAY_DAYS IS '遅延日数';
COMMENT ON COLUMN PJTW_PJ_PRJ_ALNOT.SV IS 'SV';
COMMENT ON COLUMN PJTW_PJ_PRJ_ALNOT.CV_PRICE IS 'CV額';
COMMENT ON COLUMN PJTW_PJ_PRJ_ALNOT.SPI IS 'SPI';
COMMENT ON COLUMN PJTW_PJ_PRJ_ALNOT.CPI IS 'CPI';
COMMENT ON COLUMN PJTW_PJ_PRJ_ALNOT.SI_DEAL_CD IS 'SI案件コード';
COMMENT ON COLUMN PJTW_PJ_PRJ_ALNOT.SI_DEAL_NM IS 'SI案件名';
COMMENT ON COLUMN PJTW_PJ_PRJ_ALNOT.PRJ_STR_DT IS 'プロジェクト開始日';
COMMENT ON COLUMN PJTW_PJ_PRJ_ALNOT.PRJ_END_DT IS 'プロジェクト終了日';
COMMENT ON COLUMN PJTW_PJ_PRJ_ALNOT.PROSC_EST_PRICE IS '採算原価見積額';
COMMENT ON COLUMN PJTW_PJ_PRJ_ALNOT.LST_EST_COST IS '最終見込原価';
COMMENT ON COLUMN PJTW_PJ_PRJ_ALNOT.EGY_CHG_NM IS '営業担当者名';
COMMENT ON COLUMN PJTW_PJ_PRJ_ALNOT.PRJ_MNG_NM IS 'プロジェクトマネージャ名';
COMMENT ON COLUMN PJTW_PJ_PRJ_ALNOT.DEL_FLG IS '削除フラグ';
COMMENT ON COLUMN PJTW_PJ_PRJ_ALNOT.REG_USR_ID IS '登録ユーザID';
COMMENT ON COLUMN PJTW_PJ_PRJ_ALNOT.REG_PGM_ID IS '登録プログラムID';
COMMENT ON COLUMN PJTW_PJ_PRJ_ALNOT.REG_TS IS '登録タイムスタンプ';
COMMENT ON COLUMN PJTW_PJ_PRJ_ALNOT.UPD_USR_ID IS '更新ユーザID';
COMMENT ON COLUMN PJTW_PJ_PRJ_ALNOT.UPD_PGM_ID IS '更新プログラムID';
COMMENT ON COLUMN PJTW_PJ_PRJ_ALNOT.UPD_TS IS '更新タイムスタンプ';
COMMENT ON COLUMN PJTW_PJ_PRJ_ALNOT.VER_NO IS 'バージョン番号';

-- ユニークインデックス用DDL

-- インデックス用DDL
