col now_time new_value v_now_time
SELECT TO_CHAR(SYSDATE,'YYYYMMDD_HH24MISS') NOW_TIME FROM DUAL ;
spool c:\spool_&v_now_time..log
set timing on
set echo on

PROMPT 汎用アラート基準マスタ < PJ_MOD.PJTM_PJ_HNYO_ALERT > シノニム再作成
CREATE OR REPLACE SYNONYM PJ_MOD.PJTM_PJ_HNYO_ALERT
                      FOR PJNAVI.PJTM_PJ_HNYO_ALERT
;
PROMPT 汎用役職別アラート基準マスタ < PJ_MOD.PJTM_PJ_HNYO_PST_ALERT > シノニム再作成
CREATE OR REPLACE SYNONYM PJ_MOD.PJTM_PJ_HNYO_PST_ALERT
                      FOR PJNAVI.PJTM_PJ_HNYO_PST_ALERT
;
PROMPT 汎用全社PMOアラート基準マスタ < PJ_MOD.PJTM_PJ_HNYO_PMO_ALERT > シノニム再作成
CREATE OR REPLACE SYNONYM PJ_MOD.PJTM_PJ_HNYO_PMO_ALERT
                      FOR PJNAVI.PJTM_PJ_HNYO_PMO_ALERT
;
PROMPT 採算原価見積アラート通知情報ワーク < PJ_MOD.PJTW_PJ_PROSC_EST_ALNOT > シノニム再作成
CREATE OR REPLACE SYNONYM PJ_MOD.PJTW_PJ_PROSC_EST_ALNOT
                      FOR PJNAVI.PJTW_PJ_PROSC_EST_ALNOT

PROMPT 汎用アラート基準マスタ < PJ_REF.PJTM_PJ_HNYO_ALERT > シノニム再作成
CREATE OR REPLACE SYNONYM PJ_REF.PJTM_PJ_HNYO_ALERT
                      FOR PJNAVI.PJTM_PJ_HNYO_ALERT
;
PROMPT 汎用役職別アラート基準マスタ < PJ_REF.PJTM_PJ_HNYO_PST_ALERT > シノニム再作成
CREATE OR REPLACE SYNONYM PJ_REF.PJTM_PJ_HNYO_PST_ALERT
                      FOR PJNAVI.PJTM_PJ_HNYO_PST_ALERT
;
PROMPT 汎用全社PMOアラート基準マスタ < PJ_REF.PJTM_PJ_HNYO_PMO_ALERT > シノニム再作成
CREATE OR REPLACE SYNONYM PJ_REF.PJTM_PJ_HNYO_PMO_ALERT
                      FOR PJNAVI.PJTM_PJ_HNYO_PMO_ALERT
;
PROMPT 採算原価見積アラート通知情報ワーク < PJ_REF.PJTW_PJ_PROSC_EST_ALNOT > シノニム再作成
CREATE OR REPLACE SYNONYM PJ_REF.PJTW_PJ_PROSC_EST_ALNOT
                      FOR PJNAVI.PJTW_PJ_PROSC_EST_ALNOT

spool off