col now_time new_value v_now_time
SELECT TO_CHAR(SYSDATE,'YYYYMMDD_HH24MISS') NOW_TIME FROM DUAL ;
spool c:\spool_&v_now_time..log
set timing on
set echo on

-- SI案件成約紐付トラン
-- 1. [ 自動紐付フラグ ]を追加

ALTER TABLE PJTR_PJ_SI_DEAL_CONT_LNK ADD ( AUTO_LNK_FLG   CHAR(1) DEFAULT 0);
ALTER TABLE PJTR_PJ_SI_DEAL_CONT_LNK MODIFY( AUTO_LNK_FLG NOT NULL);
COMMENT ON TABLE PJTR_PJ_SI_DEAL_CONT_LNK IS 'SI案件成約紐付トラン(ver.1.01)';
COMMENT ON COLUMN PJTR_PJ_SI_DEAL_CONT_LNK.AUTO_LNK_FLG IS '自動紐付フラグ';

-- ドロップインデックス
DROP INDEX IX1_PJTR_PJ_SI_DEAL_CONT_LNK;

DROP INDEX IX2_PJTR_PJ_SI_DEAL_CONT_LNK;


-- ユニークインデックス用DDL
CREATE UNIQUE INDEX UX_PJTR_PJ_SI_DEAL_CONT_LNK ON PJTR_PJ_SI_DEAL_CONT_LNK (
    ODR_NO 
);

-- インデックス用DDL
CREATE INDEX IX1_PJTR_PJ_SI_DEAL_CONT_LNK ON PJTR_PJ_SI_DEAL_CONT_LNK (
    SAR_STATS ,
    BUSI_PROC_DT 
);


spool off
