-- NextMIプロジェクトメンバトラン
DROP MATERIALIZED VIEW LOG ON PJTR_MI_NEXTMI_PRJ_MBR;

-- プロジェクトリソーストラン
DROP MATERIALIZED VIEW LOG ON PJTR_PJ_PRJ_RESRC;

-- NextMIプロジェクトトラン
DROP MATERIALIZED VIEW LOG ON PJTR_MI_NEXTMI_PRJ;

-- プロジェクトトラン
DROP MATERIALIZED VIEW LOG ON PJTR_PJ_PRJ;

-- プロジェクト付帯情報トラン
DROP MATERIALIZED VIEW LOG ON PJTR_MI_PRJ_ICDT_INFO;

-- プロジェクトテンプレートマスタ
DROP MATERIALIZED VIEW LOG ON PJTM_PJ_PRJ_TPL;

-- NextMIプロジェクトタスクトラン
DROP MATERIALIZED VIEW LOG ON PJTR_MI_NEXTMI_PRJ_TSK;

-- WBSタスクトラン
DROP MATERIALIZED VIEW LOG ON PJTR_PJ_WBS_TSK;

-- プロジェクトNext.MIタスクトラン
DROP MATERIALIZED VIEW LOG ON PJTR_PJ_PRJ_NEXTMI_TSK;

DROP MATERIALIZED VIEW PJVR_MI_PRJ_MBR_UNI;
DROP MATERIALIZED VIEW PJVR_MI_PRJ_UNI;
DROP MATERIALIZED VIEW PJVR_MI_TSK_UNI;

