-- NextMIプロジェクトメンバトラン
DROP MATERIALIZED VIEW LOG ON PJTR_MI_NEXTMI_PRJ_MBR;
CREATE MATERIALIZED VIEW LOG ON PJTR_MI_NEXTMI_PRJ_MBR WITH ROWID;

-- プロジェクトリソーストラン
DROP MATERIALIZED VIEW LOG ON PJTR_PJ_PRJ_RESRC;
CREATE MATERIALIZED VIEW LOG ON PJTR_PJ_PRJ_RESRC WITH ROWID;

-- NextMIプロジェクトトラン
DROP MATERIALIZED VIEW LOG ON PJTR_MI_NEXTMI_PRJ;
CREATE MATERIALIZED VIEW LOG ON PJTR_MI_NEXTMI_PRJ WITH ROWID;

-- プロジェクトトラン
DROP MATERIALIZED VIEW LOG ON PJTR_PJ_PRJ;
CREATE MATERIALIZED VIEW LOG ON PJTR_PJ_PRJ WITH ROWID;

-- プロジェクト付帯情報トラン
DROP MATERIALIZED VIEW LOG ON PJTR_MI_PRJ_ICDT_INFO;
CREATE MATERIALIZED VIEW LOG ON PJTR_MI_PRJ_ICDT_INFO WITH ROWID;

-- プロジェクトテンプレートマスタ
DROP MATERIALIZED VIEW LOG ON PJTM_PJ_PRJ_TPL;
CREATE MATERIALIZED VIEW LOG ON PJTM_PJ_PRJ_TPL WITH ROWID;

-- NextMIプロジェクトタスクトラン
DROP MATERIALIZED VIEW LOG ON PJTR_MI_NEXTMI_PRJ_TSK;
CREATE MATERIALIZED VIEW LOG ON PJTR_MI_NEXTMI_PRJ_TSK WITH ROWID;

-- WBSタスクトラン
DROP MATERIALIZED VIEW LOG ON PJTR_PJ_WBS_TSK;
CREATE MATERIALIZED VIEW LOG ON PJTR_PJ_WBS_TSK WITH ROWID;

-- プロジェクトNext.MIタスクトラン
DROP MATERIALIZED VIEW LOG ON PJTR_PJ_PRJ_NEXTMI_TSK;
CREATE MATERIALIZED VIEW LOG ON PJTR_PJ_PRJ_NEXTMI_TSK WITH ROWID;

