--DROP MATERIALIZED VIEW LOG ON PJTR_MI_NEXTMI_PRJ_MBR;
CREATE MATERIALIZED VIEW LOG ON PJTR_MI_NEXTMI_PRJ_MBR WITH ROWID;

--DROP MATERIALIZED VIEW LOG ON PJTR_PJ_PRJ_RESRC;
CREATE MATERIALIZED VIEW LOG ON PJTR_PJ_PRJ_RESRC WITH ROWID;

--DROP MATERIALIZED VIEW LOG ON PJTR_MI_NEXTMI_PRJ;
CREATE MATERIALIZED VIEW LOG ON PJTR_MI_NEXTMI_PRJ WITH ROWID;

--DROP MATERIALIZED VIEW LOG ON PJTR_PJ_PRJ;
CREATE MATERIALIZED VIEW LOG ON PJTR_PJ_PRJ WITH ROWID;

--DROP MATERIALIZED VIEW LOG ON PJTR_MI_PRJ_ICDT_INFO;
CREATE MATERIALIZED VIEW LOG ON PJTR_MI_PRJ_ICDT_INFO WITH ROWID;

--DROP MATERIALIZED VIEW LOG ON PJTM_PJ_PRJ_TPL;
CREATE MATERIALIZED VIEW LOG ON PJTM_PJ_PRJ_TPL WITH ROWID;

--DROP MATERIALIZED VIEW LOG ON PJTR_MI_NEXTMI_PRJ_TSK;
CREATE MATERIALIZED VIEW LOG ON PJTR_MI_NEXTMI_PRJ_TSK WITH ROWID;

--DROP MATERIALIZED VIEW LOG ON PJTR_PJ_WBS_TSK;
CREATE MATERIALIZED VIEW LOG ON PJTR_PJ_WBS_TSK WITH ROWID;

--DROP MATERIALIZED VIEW LOG ON PJTR_PJ_PRJ_NEXTMI_TSK;
CREATE MATERIALIZED VIEW LOG ON PJTR_PJ_PRJ_NEXTMI_TSK WITH ROWID;

