--NextMIプロジェクト(PJTR_MI_NEXTMI_PRJ)と
--PJNaviプロジェクト(PJTR_PJ_PRJ)の連結VIEW
--PK:プロジェクトコード

--DROP MATERIALIZED VIEW LOG ON PJTR_MI_NEXTMI_PRJ;
--CREATE MATERIALIZED VIEW LOG ON PJTR_MI_NEXTMI_PRJ WITH ROWID;

--DROP MATERIALIZED VIEW LOG ON PJTR_PJ_PRJ;
--CREATE MATERIALIZED VIEW LOG ON PJTR_PJ_PRJ WITH ROWID;

--DROP MATERIALIZED VIEW LOG ON PJTR_MI_PRJ_ICDT_INFO;
--CREATE MATERIALIZED VIEW LOG ON PJTR_MI_PRJ_ICDT_INFO WITH ROWID;

--DROP MATERIALIZED VIEW LOG ON PJTM_PJ_PRJ_TPL;
--CREATE MATERIALIZED VIEW LOG ON PJTM_PJ_PRJ_TPL WITH ROWID;

DROP MATERIALIZED VIEW PJVR_MI_PRJ_UNI;
CREATE MATERIALIZED VIEW PJVR_MI_PRJ_UNI
REFRESH FAST ON COMMIT
AS
SELECT NEXTMI_PRJ.PRJ_CD                    AS PRJ_CD
     , NEXTMI_PRJ.PRJ_NM                    AS PRJ_NM
     , NEXTMI_PRJ.PRJ_TYP                   AS PRJ_TYP
     , NEXTMI_PRJ.PRJ_STATS                 AS PRJ_STATS
     , NULL                                 AS SI_DEAL_CD
     , NEXTMI_PRJ.PRJ_OWN_ORGAN_CD          AS PRJ_OWN_ORGAN_CD
     , NEXTMI_PRJ.PRJ_EGY_EMP_CD            AS PRJ_EGY_EMP_CD
     , '0'                                  AS PROP_PRJ_FLG
     , '0'                                  AS FLAW_PRJ_FLG
     , PRJ_ICDT_INFO.LEAD_STA_FLG           AS LEAD_STA_FLG
     , PRJ_ICDT_INFO.LEAD_STA_TRM_STR_DT    AS LEAD_STA_TRM_STR_DT
     , PRJ_ICDT_INFO.LEAD_STA_TRM_END_DT    AS LEAD_STA_TRM_END_DT
     , NEXTMI_PRJ.ROWID                     AS ROW_ID1
     , PRJ_ICDT_INFO.ROWID                  AS ROW_ID2
     , PRJ_ICDT_INFO.ROWID                  AS ROW_ID3
     , '1'                                  AS PRJ_MK_SYS_SEG  -- 0：PJNavi,1：NextMI
  FROM PJTR_MI_NEXTMI_PRJ       NEXTMI_PRJ
     , PJTR_MI_PRJ_ICDT_INFO    PRJ_ICDT_INFO
 WHERE NEXTMI_PRJ.PRJ_CD = PRJ_ICDT_INFO.PRJ_CD(+)
UNION ALL
SELECT PRJ.PRJ_CD                           AS PRJ_CD
     , PRJ.PRJ_NM                           AS PRJ_NM
     , PRJ_TPL.PRJ_TYP_NM                   AS PRJ_TYP
     , PRJ.PRJ_STATS_SEG                    AS PRJ_STATS
     , PRJ.SI_DEAL_CD                       AS SI_DEAL_CD
     , PRJ.PRJ_DEV_DEPT_CD                  AS PRJ_OWN_ORGAN_CD
     , PRJ.PRJ_EGY_EMP_CD                   AS PRJ_EGY_EMP_CD
     , PRJ.PROP_PRJ_FLG                     AS PROP_PRJ_FLG
     , PRJ.FLAW_PRJ_FLG                     AS FLAW_PRJ_FLG
     , PRJ_ICDT_INFO.LEAD_STA_FLG           AS LEAD_STA_FLG
     , PRJ_ICDT_INFO.LEAD_STA_TRM_STR_DT    AS LEAD_STA_TRM_STR_DT
     , PRJ_ICDT_INFO.LEAD_STA_TRM_END_DT    AS LEAD_STA_TRM_END_DT
     , PRJ.ROWID                            AS ROW_ID1
     , PRJ_ICDT_INFO.ROWID                  AS ROW_ID2
     , PRJ_TPL.ROWID                        AS ROW_ID3
     , '0'                                  AS PRJ_MK_SYS_SEG  -- 0：PJNavi,1：NextMI
  FROM PJTR_PJ_PRJ              PRJ
     , PJTR_MI_PRJ_ICDT_INFO    PRJ_ICDT_INFO
     , PJTM_PJ_PRJ_TPL          PRJ_TPL
 WHERE PRJ.PRJ_CD   = PRJ_ICDT_INFO.PRJ_CD(+)
   AND PRJ.PRJ_TPL  = PRJ_TPL.TPL_NO
;

ALTER MATERIALIZED VIEW PJVR_MI_PRJ_UNI ADD CONSTRAINT PK_PJVR_MI_PRJ_UNI PRIMARY KEY
    ( PRJ_CD );

COMMENT ON MATERIALIZED VIEW PJVR_MI_PRJ_UNI IS 'プロジェクトトラン連結ビュー(ver.0.1)';
COMMENT ON COLUMN PJVR_MI_PRJ_UNI.PRJ_CD IS 'プロジェクトコード';
COMMENT ON COLUMN PJVR_MI_PRJ_UNI.PRJ_NM IS 'プロジェクト名';
COMMENT ON COLUMN PJVR_MI_PRJ_UNI.PRJ_TYP IS 'プロジェクトタイプ';
COMMENT ON COLUMN PJVR_MI_PRJ_UNI.PRJ_STATS IS 'プロジェクトステータス';
COMMENT ON COLUMN PJVR_MI_PRJ_UNI.SI_DEAL_CD IS 'SI案件コード';
COMMENT ON COLUMN PJVR_MI_PRJ_UNI.PRJ_OWN_ORGAN_CD IS 'プロジェクト所有組織コード';
COMMENT ON COLUMN PJVR_MI_PRJ_UNI.PRJ_EGY_EMP_CD IS 'プロジェクト営業従業員コード';
COMMENT ON COLUMN PJVR_MI_PRJ_UNI.PROP_PRJ_FLG IS '提案プロジェクトフラグ';
COMMENT ON COLUMN PJVR_MI_PRJ_UNI.FLAW_PRJ_FLG IS '瑕疵プロジェクトフラグ';
COMMENT ON COLUMN PJVR_MI_PRJ_UNI.LEAD_STA_FLG IS '先行着手フラグ';
COMMENT ON COLUMN PJVR_MI_PRJ_UNI.LEAD_STA_TRM_STR_DT IS '先行着手期間開始日';
COMMENT ON COLUMN PJVR_MI_PRJ_UNI.LEAD_STA_TRM_END_DT IS '先行着手期間終了日';
COMMENT ON COLUMN PJVR_MI_PRJ_UNI.ROW_ID1 IS 'ROW_ID1';
COMMENT ON COLUMN PJVR_MI_PRJ_UNI.ROW_ID2 IS 'ROW_ID2';
COMMENT ON COLUMN PJVR_MI_PRJ_UNI.ROW_ID3 IS 'ROW_ID3';
COMMENT ON COLUMN PJVR_MI_PRJ_UNI.PRJ_MK_SYS_SEG IS 'プロジェクト作成システム区分';

