-- 2013/7/10 カラム属性変更
-- WBS別EVM集計SNAPトラン [ 遅延日数 ]を必須から任意に変更
ALTER TABLE PJTR_PJ_WBS_EVM_SUM_SNAP	MODIFY(DELAY_DAYS DEFAULT NULL NULL);
COMMENT ON TABLE PJTR_PJ_WBS_EVM_SUM_SNAP IS 'WBS別EVM集計SNAPトラン(ver.0.91)';

-- プロジェクト別EVM集計SNAPトラン [ 遅延日数 ]を必須から任意に変更
ALTER TABLE PJTR_PJ_PRJ_EVM_SUM_SNAP	MODIFY(DELAY_DAYS DEFAULT NULL NULL);
COMMENT ON TABLE PJTR_PJ_PRJ_EVM_SUM_SNAP IS 'プロジェクト別EVM集計SNAPトラン(ver.0.91)';

-- 今回報告締WBSタスクSNAPトラン [ 遅延日数 ]を必須から任意に変更
ALTER TABLE PJTR_PJ_THIS_WBS_TSK_SNAP	MODIFY(DELAY_DAYS DEFAULT NULL NULL);
COMMENT ON TABLE PJTR_PJ_THIS_WBS_TSK_SNAP IS '今回報告締WBSタスクSNAPトラン(ver.0.8)';

-- 前回報告締WBSタスクSNAPトラン [ 遅延日数 ]を必須から任意に変更
ALTER TABLE PJTR_PJ_PREV_WBS_TSK_SNAP	MODIFY(DELAY_DAYS DEFAULT NULL NULL);
COMMENT ON TABLE PJTR_PJ_PREV_WBS_TSK_SNAP IS '前回報告締WBSタスクSNAPトラン(ver.0.8)';
