-- 2013/6/6 属性変更
-- 従業員割当職責マスタ PKを[従業員ID],[職責ID]に変更
COMMENT ON TABLE PJTM_SY_EMP_ASSIGN_RES IS '従業員割当職責マスタ(ver.0.4)';
ALTER TABLE PJTM_SY_EMP_ASSIGN_RES DROP PRIMARY KEY;
ALTER TABLE PJTM_SY_EMP_ASSIGN_RES ADD CONSTRAINT PK_PJTM_SY_EMP_ASSIGN_RES PRIMARY KEY (EMP_ID, RES_ID ) ;
