-- 2013/7/11 カラム属性変更
-- 成約ヘッダトラン [ 見積番号 ]の属性を[ VARCHAR2(10) ]に変更
ALTER TABLE PJTR_PJ_CONT_HEAD	MODIFY(EST_NO VARCHAR2(10));
COMMENT ON TABLE PJTR_PJ_CONT_HEAD IS '成約ヘッダトラン(ver.0.6)';

UPDATE	PJTR_PJ_CONT_HEAD
set		EST_NO = RTRIM(EST_NO)
;
COMMIT;

-- 検収売上ヘッダトラン [ 見積番号 ]の属性を[ VARCHAR2(10) ]に変更
ALTER TABLE PJTR_PJ_ACCEPT_SLS_HEAD	MODIFY(EST_NO VARCHAR2(10));
COMMENT ON TABLE PJTR_PJ_ACCEPT_SLS_HEAD IS '検収売上ヘッダトラン(ver.0.6)';

UPDATE	PJTR_PJ_ACCEPT_SLS_HEAD
set		EST_NO = RTRIM(EST_NO)
;
COMMIT;
