-- 2013/7/18 カラム追加
-- 提案コストアラート送信履歴トラン [ 提案コスト限度額 ]を追加
ALTER TABLE PJTR_PJ_PROP_CA_SND_HIST	ADD(PROP_CST_LMT_PRICE NUMBER(12,0) DEFAULT 0 NOT NULL);
COMMENT ON TABLE PJTR_PJ_PROP_CA_SND_HIST IS '提案コストアラート送信履歴トラン(ver.0.5)';
COMMENT ON COLUMN PJTR_PJ_PROP_CA_SND_HIST.PROP_CST_LMT_PRICE IS '提案コスト限度額';

-- 2013/7/19 カラム追加
-- PA形態別区分マスタ [ 進行基準対象フラグ ]を追加
ALTER TABLE PJTM_PJ_PA_FORM_SEG	ADD(PROG_BS_TAR_FLG CHAR(1) DEFAULT '0' NOT NULL);
COMMENT ON TABLE PJTM_PJ_PA_FORM_SEG IS 'PA形態別区分マスタ(ver.0.7)';
COMMENT ON COLUMN PJTM_PJ_PA_FORM_SEG.PROG_BS_TAR_FLG IS '進行基準対象フラグ';

