-- 2013/5/24 カラム属性変更
-- WBSタスクトラン 説明変更
COMMENT ON TABLE PJTR_PJ_WBS_TSK IS 'WBSタスクトラン(ver.0.99)';
-- WBS別EVM集計SNAPトラン [ 予測完了日 ]を必須から任意に変更
ALTER TABLE PJTR_PJ_WBS_EVM_SUM_SNAP	MODIFY(FCT_CMP_DT NULL);
COMMENT ON TABLE PJTR_PJ_WBS_EVM_SUM_SNAP IS 'WBS別EVM集計SNAPトラン(ver.0.9)';

-- プロジェクト別EVM集計SNAPトラン [ 予測完了日 ]を必須から任意に変更
ALTER TABLE PJTR_PJ_PRJ_EVM_SUM_SNAP	MODIFY(FCT_CMP_DT NULL);
COMMENT ON TABLE PJTR_PJ_PRJ_EVM_SUM_SNAP IS 'プロジェクト別EVM集計SNAPトラン(ver.0.9)';

-- 今回報告締WBSタスクSNAPトラン [ 予測完了日 ]を必須から任意に変更
ALTER TABLE PJTR_PJ_THIS_WBS_TSK_SNAP	MODIFY(FCT_CMP_DT NULL);
COMMENT ON TABLE PJTR_PJ_THIS_WBS_TSK_SNAP IS '今回報告締WBSタスクSNAPトラン(ver.0.7)';

-- 前回報告締WBSタスクSNAPトラン [ 予測完了日 ]を必須から任意に変更
ALTER TABLE PJTR_PJ_PREV_WBS_TSK_SNAP	MODIFY(FCT_CMP_DT NULL);
COMMENT ON TABLE PJTR_PJ_PREV_WBS_TSK_SNAP IS '前回報告締WBSタスクSNAPトラン(ver.0.7)';
