-- 2013/5/28 カラム属性変更
-- 採算原価見積トラン [ プロジェクト検収条件区分 ]の属性を[ VARCHAR2(3) ]に変更※2013/1/23対応漏れ
ALTER TABLE PJTR_PJ_PROSC_EST	MODIFY(PRJ_ACCEPT_COND_SEG VARCHAR2(3));
COMMENT ON TABLE PJTR_PJ_PROSC_EST IS '採算原価見積トラン(ver.0.91)';

UPDATE	PJTR_PJ_PROSC_EST
set		PRJ_ACCEPT_COND_SEG = RTRIM(PRJ_ACCEPT_COND_SEG)
;
COMMIT;
