-- 2013/5/29 カラム属性変更
-- NextMIプロジェクトメンバトラン [ ロール ]の属性を[ VARCHAR2(4) ]に変更
ALTER TABLE PJTR_MI_NEXTMI_PRJ_MBR	MODIFY(ROLE VARCHAR2(4));
COMMENT ON TABLE PJTR_MI_NEXTMI_PRJ_MBR IS 'NextMIプロジェクトメンバトラン(ver.0.5)';

UPDATE	PJTR_MI_NEXTMI_PRJ_MBR
set		ROLE = RTRIM(ROLE)
;
COMMIT;
