-- テーブル用DDL
DROP TABLE PJTR_MI_ETIME_WRKDT_INFO CASCADE CONSTRAINTS;

CREATE TABLE PJTR_MI_ETIME_WRKDT_INFO
(
    EMP_ID                         NUMBER(10) NOT NULL ,
    WK_DT                          DATE NOT NULL ,
    ATDC_PUN_TM                    CHAR(5) ,
    MOD_ATDC_TM                    CHAR(5) ,
    CLKO_PUN_TM                    CHAR(5) ,
    MOD_CLKO_TM                    CHAR(5) ,
    BEIN_TM                        NUMBER(5,2) ,
    ACTWRK_TM                      NUMBER(5,2) ,
    RCS_TM                         NUMBER(5,2) ,
    VAC_NM                         VARCHAR2(60) ,
    APP_STATS                      CHAR(1) DEFAULT '0' NOT NULL ,
    ICDT_INFO_1                    NUMBER(15) NOT NULL ,
    BAT_PROC_DONE_FLG              CHAR(1) DEFAULT '0' NOT NULL ,
    DEL_FLG                        CHAR(1) DEFAULT '0' NOT NULL ,
    REG_USR_ID                     NUMBER(10) NOT NULL ,
    REG_PGM_ID                     CHAR(11) NOT NULL ,
    REG_TS                         TIMESTAMP(3) NOT NULL ,
    UPD_USR_ID                     NUMBER(10) NOT NULL ,
    UPD_PGM_ID                     CHAR(11) NOT NULL ,
    UPD_TS                         TIMESTAMP(3) NOT NULL ,
    VER_NO                         NUMBER(10) DEFAULT 0 NOT NULL
);
ALTER TABLE PJTR_MI_ETIME_WRKDT_INFO ADD CONSTRAINT PK_PJTR_MI_ETIME_WRKDT_INFO PRIMARY KEY (EMP_ID, WK_DT ) ;

COMMENT ON TABLE PJTR_MI_ETIME_WRKDT_INFO IS 'eTime実働日情報トラン(ver.0.5)';
COMMENT ON COLUMN PJTR_MI_ETIME_WRKDT_INFO.EMP_ID IS '従業員ID';
COMMENT ON COLUMN PJTR_MI_ETIME_WRKDT_INFO.WK_DT IS '勤務日';
COMMENT ON COLUMN PJTR_MI_ETIME_WRKDT_INFO.ATDC_PUN_TM IS '出勤打刻時間';
COMMENT ON COLUMN PJTR_MI_ETIME_WRKDT_INFO.MOD_ATDC_TM IS '修正後出勤時間';
COMMENT ON COLUMN PJTR_MI_ETIME_WRKDT_INFO.CLKO_PUN_TM IS '退勤打刻時間';
COMMENT ON COLUMN PJTR_MI_ETIME_WRKDT_INFO.MOD_CLKO_TM IS '修正後退勤時間';
COMMENT ON COLUMN PJTR_MI_ETIME_WRKDT_INFO.BEIN_TM IS '在社時間';
COMMENT ON COLUMN PJTR_MI_ETIME_WRKDT_INFO.ACTWRK_TM IS '実働時間';
COMMENT ON COLUMN PJTR_MI_ETIME_WRKDT_INFO.RCS_TM IS '休憩時間';
COMMENT ON COLUMN PJTR_MI_ETIME_WRKDT_INFO.VAC_NM IS '休暇名称';
COMMENT ON COLUMN PJTR_MI_ETIME_WRKDT_INFO.APP_STATS IS '承認ステータス';
COMMENT ON COLUMN PJTR_MI_ETIME_WRKDT_INFO.ICDT_INFO_1 IS '付帯情報1';
COMMENT ON COLUMN PJTR_MI_ETIME_WRKDT_INFO.BAT_PROC_DONE_FLG IS 'バッチ処理済フラグ';
COMMENT ON COLUMN PJTR_MI_ETIME_WRKDT_INFO.DEL_FLG IS '削除フラグ';
COMMENT ON COLUMN PJTR_MI_ETIME_WRKDT_INFO.REG_USR_ID IS '登録ユーザID';
COMMENT ON COLUMN PJTR_MI_ETIME_WRKDT_INFO.REG_PGM_ID IS '登録プログラムID';
COMMENT ON COLUMN PJTR_MI_ETIME_WRKDT_INFO.REG_TS IS '登録タイムスタンプ';
COMMENT ON COLUMN PJTR_MI_ETIME_WRKDT_INFO.UPD_USR_ID IS '更新ユーザID';
COMMENT ON COLUMN PJTR_MI_ETIME_WRKDT_INFO.UPD_PGM_ID IS '更新プログラムID';
COMMENT ON COLUMN PJTR_MI_ETIME_WRKDT_INFO.UPD_TS IS '更新タイムスタンプ';
COMMENT ON COLUMN PJTR_MI_ETIME_WRKDT_INFO.VER_NO IS 'バージョン番号';

-- ユニークインデックス用DDL

-- インデックス用DDL
CREATE INDEX IX1_PJTR_MI_ETIME_WRKDT_INFO ON PJTR_MI_ETIME_WRKDT_INFO (
    BAT_PROC_DONE_FLG 
);

