-- テーブル用DDL
DROP TABLE PJTM_SY_HNYO_NUM_MNG CASCADE CONSTRAINTS;

CREATE TABLE PJTM_SY_HNYO_NUM_MNG
(
    NUM_KND                        VARCHAR2(30) NOT NULL ,
    NUM_KEY                        VARCHAR2(15) NOT NULL ,
    SEQ_NO                         NUMBER(18) DEFAULT 0 NOT NULL ,
    DEL_FLG                        CHAR(1) DEFAULT '0' NOT NULL ,
    REG_USR_ID                     NUMBER(10) NOT NULL ,
    REG_PGM_ID                     CHAR(11) NOT NULL ,
    REG_TS                         TIMESTAMP(3) NOT NULL ,
    UPD_USR_ID                     NUMBER(10) NOT NULL ,
    UPD_PGM_ID                     CHAR(11) NOT NULL ,
    UPD_TS                         TIMESTAMP(3) NOT NULL ,
    VER_NO                         NUMBER(10) DEFAULT 0 NOT NULL
);
ALTER TABLE PJTM_SY_HNYO_NUM_MNG ADD CONSTRAINT PK_PJTM_SY_HNYO_NUM_MNG PRIMARY KEY (NUM_KND, NUM_KEY ) ;

COMMENT ON TABLE PJTM_SY_HNYO_NUM_MNG IS '汎用採番管理マスタ(ver.0.6)';
COMMENT ON COLUMN PJTM_SY_HNYO_NUM_MNG.NUM_KND IS '採番種別';
COMMENT ON COLUMN PJTM_SY_HNYO_NUM_MNG.NUM_KEY IS '採番キー';
COMMENT ON COLUMN PJTM_SY_HNYO_NUM_MNG.SEQ_NO IS 'シーケンス番号';
COMMENT ON COLUMN PJTM_SY_HNYO_NUM_MNG.DEL_FLG IS '削除フラグ';
COMMENT ON COLUMN PJTM_SY_HNYO_NUM_MNG.REG_USR_ID IS '登録ユーザID';
COMMENT ON COLUMN PJTM_SY_HNYO_NUM_MNG.REG_PGM_ID IS '登録プログラムID';
COMMENT ON COLUMN PJTM_SY_HNYO_NUM_MNG.REG_TS IS '登録タイムスタンプ';
COMMENT ON COLUMN PJTM_SY_HNYO_NUM_MNG.UPD_USR_ID IS '更新ユーザID';
COMMENT ON COLUMN PJTM_SY_HNYO_NUM_MNG.UPD_PGM_ID IS '更新プログラムID';
COMMENT ON COLUMN PJTM_SY_HNYO_NUM_MNG.UPD_TS IS '更新タイムスタンプ';
COMMENT ON COLUMN PJTM_SY_HNYO_NUM_MNG.VER_NO IS 'バージョン番号';

-- ユニークインデックス用DDL

-- インデックス用DDL
