-- テーブル用DDL
DROP TABLE PJTM_SY_EMP_ASSIGN_RES CASCADE CONSTRAINTS;

CREATE TABLE PJTM_SY_EMP_ASSIGN_RES
(
    EMP_ID                         NUMBER(10) NOT NULL ,
    RES_ID                         VARCHAR2(18) NOT NULL ,
    VLD_STR_DT                     DATE NOT NULL ,
    VLD_END_DT                     DATE NOT NULL ,
    DEL_FLG                        CHAR(1) DEFAULT '0' NOT NULL ,
    REG_USR_ID                     NUMBER(10) NOT NULL ,
    REG_PGM_ID                     CHAR(11) NOT NULL ,
    REG_TS                         TIMESTAMP(3) NOT NULL ,
    UPD_USR_ID                     NUMBER(10) NOT NULL ,
    UPD_PGM_ID                     CHAR(11) NOT NULL ,
    UPD_TS                         TIMESTAMP(3) NOT NULL ,
    VER_NO                         NUMBER(10) DEFAULT 0 NOT NULL
);
ALTER TABLE PJTM_SY_EMP_ASSIGN_RES ADD CONSTRAINT PK_PJTM_SY_EMP_ASSIGN_RES PRIMARY KEY (EMP_ID, RES_ID ) ;

COMMENT ON TABLE PJTM_SY_EMP_ASSIGN_RES IS '従業員割当職責マスタ(ver.0.4)';
COMMENT ON COLUMN PJTM_SY_EMP_ASSIGN_RES.EMP_ID IS '従業員ID';
COMMENT ON COLUMN PJTM_SY_EMP_ASSIGN_RES.RES_ID IS '職責ID';
COMMENT ON COLUMN PJTM_SY_EMP_ASSIGN_RES.VLD_STR_DT IS '有効開始日';
COMMENT ON COLUMN PJTM_SY_EMP_ASSIGN_RES.VLD_END_DT IS '有効終了日';
COMMENT ON COLUMN PJTM_SY_EMP_ASSIGN_RES.DEL_FLG IS '削除フラグ';
COMMENT ON COLUMN PJTM_SY_EMP_ASSIGN_RES.REG_USR_ID IS '登録ユーザID';
COMMENT ON COLUMN PJTM_SY_EMP_ASSIGN_RES.REG_PGM_ID IS '登録プログラムID';
COMMENT ON COLUMN PJTM_SY_EMP_ASSIGN_RES.REG_TS IS '登録タイムスタンプ';
COMMENT ON COLUMN PJTM_SY_EMP_ASSIGN_RES.UPD_USR_ID IS '更新ユーザID';
COMMENT ON COLUMN PJTM_SY_EMP_ASSIGN_RES.UPD_PGM_ID IS '更新プログラムID';
COMMENT ON COLUMN PJTM_SY_EMP_ASSIGN_RES.UPD_TS IS '更新タイムスタンプ';
COMMENT ON COLUMN PJTM_SY_EMP_ASSIGN_RES.VER_NO IS 'バージョン番号';

-- ユニークインデックス用DDL

-- インデックス用DDL
