-- テーブル用DDL
DROP TABLE PJTM_SY_REF_AUTH CASCADE CONSTRAINTS;

CREATE TABLE PJTM_SY_REF_AUTH
(
    EMP_ID                         NUMBER(10) NOT NULL ,
    HR_ORGAN_ID                    NUMBER(15) NOT NULL ,
    REF_SEG                        CHAR(1) NOT NULL ,
    DEL_FLG                        CHAR(1) DEFAULT '0' NOT NULL ,
    REG_USR_ID                     NUMBER(10) NOT NULL ,
    REG_PGM_ID                     CHAR(11) NOT NULL ,
    REG_TS                         TIMESTAMP(3) NOT NULL ,
    UPD_USR_ID                     NUMBER(10) NOT NULL ,
    UPD_PGM_ID                     CHAR(11) NOT NULL ,
    UPD_TS                         TIMESTAMP(3) NOT NULL ,
    VER_NO                         NUMBER(10) DEFAULT 0 NOT NULL
);
ALTER TABLE PJTM_SY_REF_AUTH ADD CONSTRAINT PK_PJTM_SY_REF_AUTH PRIMARY KEY (EMP_ID, HR_ORGAN_ID, REF_SEG ) ;

COMMENT ON TABLE PJTM_SY_REF_AUTH IS '参照権限マスタ(ver.0.6)';
COMMENT ON COLUMN PJTM_SY_REF_AUTH.EMP_ID IS '従業員ID';
COMMENT ON COLUMN PJTM_SY_REF_AUTH.HR_ORGAN_ID IS 'HR組織ID';
COMMENT ON COLUMN PJTM_SY_REF_AUTH.REF_SEG IS '参照区分';
COMMENT ON COLUMN PJTM_SY_REF_AUTH.DEL_FLG IS '削除フラグ';
COMMENT ON COLUMN PJTM_SY_REF_AUTH.REG_USR_ID IS '登録ユーザID';
COMMENT ON COLUMN PJTM_SY_REF_AUTH.REG_PGM_ID IS '登録プログラムID';
COMMENT ON COLUMN PJTM_SY_REF_AUTH.REG_TS IS '登録タイムスタンプ';
COMMENT ON COLUMN PJTM_SY_REF_AUTH.UPD_USR_ID IS '更新ユーザID';
COMMENT ON COLUMN PJTM_SY_REF_AUTH.UPD_PGM_ID IS '更新プログラムID';
COMMENT ON COLUMN PJTM_SY_REF_AUTH.UPD_TS IS '更新タイムスタンプ';
COMMENT ON COLUMN PJTM_SY_REF_AUTH.VER_NO IS 'バージョン番号';

-- ユニークインデックス用DDL

-- インデックス用DDL
