-- テーブル用DDL
DROP TABLE PJTM_SY_RES CASCADE CONSTRAINTS;

CREATE TABLE PJTM_SY_RES
(
    RES_ID                         VARCHAR2(18) NOT NULL ,
    REF_AUTH_SEG                   CHAR(1) NOT NULL ,
    RES_NM                         VARCHAR2(150) NOT NULL ,
    REF_SEG                        CHAR(1) NOT NULL ,
    DEL_FLG                        CHAR(1) DEFAULT '0' NOT NULL ,
    REG_USR_ID                     NUMBER(10) NOT NULL ,
    REG_PGM_ID                     CHAR(11) NOT NULL ,
    REG_TS                         TIMESTAMP(3) NOT NULL ,
    UPD_USR_ID                     NUMBER(10) NOT NULL ,
    UPD_PGM_ID                     CHAR(11) NOT NULL ,
    UPD_TS                         TIMESTAMP(3) NOT NULL ,
    VER_NO                         NUMBER(10) DEFAULT 0 NOT NULL
);
ALTER TABLE PJTM_SY_RES ADD CONSTRAINT PK_PJTM_SY_RES PRIMARY KEY (RES_ID ) ;

COMMENT ON TABLE PJTM_SY_RES IS '職責マスタ(ver.0.7)';
COMMENT ON COLUMN PJTM_SY_RES.RES_ID IS '職責ID';
COMMENT ON COLUMN PJTM_SY_RES.REF_AUTH_SEG IS '参照権限区分';
COMMENT ON COLUMN PJTM_SY_RES.RES_NM IS '職責名';
COMMENT ON COLUMN PJTM_SY_RES.REF_SEG IS '参照区分';
COMMENT ON COLUMN PJTM_SY_RES.DEL_FLG IS '削除フラグ';
COMMENT ON COLUMN PJTM_SY_RES.REG_USR_ID IS '登録ユーザID';
COMMENT ON COLUMN PJTM_SY_RES.REG_PGM_ID IS '登録プログラムID';
COMMENT ON COLUMN PJTM_SY_RES.REG_TS IS '登録タイムスタンプ';
COMMENT ON COLUMN PJTM_SY_RES.UPD_USR_ID IS '更新ユーザID';
COMMENT ON COLUMN PJTM_SY_RES.UPD_PGM_ID IS '更新プログラムID';
COMMENT ON COLUMN PJTM_SY_RES.UPD_TS IS '更新タイムスタンプ';
COMMENT ON COLUMN PJTM_SY_RES.VER_NO IS 'バージョン番号';

-- ユニークインデックス用DDL

-- インデックス用DDL
