-- テーブル用DDL
DROP TABLE PJTW_SY_HNYO_LOCK CASCADE CONSTRAINTS;

CREATE TABLE PJTW_SY_HNYO_LOCK
(
    LOCK_KEY                       VARCHAR2(256) NOT NULL ,
    DEL_FLG                        CHAR(1) DEFAULT '0' NOT NULL ,
    REG_USR_ID                     NUMBER(10) NOT NULL ,
    REG_PGM_ID                     CHAR(11) NOT NULL ,
    REG_TS                         TIMESTAMP(3) NOT NULL ,
    UPD_USR_ID                     NUMBER(10) NOT NULL ,
    UPD_PGM_ID                     CHAR(11) NOT NULL ,
    UPD_TS                         TIMESTAMP(3) NOT NULL ,
    VER_NO                         NUMBER(10) DEFAULT 0 NOT NULL
);
ALTER TABLE PJTW_SY_HNYO_LOCK ADD CONSTRAINT PK_PJTW_SY_HNYO_LOCK PRIMARY KEY (LOCK_KEY ) ;

COMMENT ON TABLE PJTW_SY_HNYO_LOCK IS '汎用ロックワーク(ver.0.1)';
COMMENT ON COLUMN PJTW_SY_HNYO_LOCK.LOCK_KEY IS 'ロックキー';
COMMENT ON COLUMN PJTW_SY_HNYO_LOCK.DEL_FLG IS '削除フラグ';
COMMENT ON COLUMN PJTW_SY_HNYO_LOCK.REG_USR_ID IS '登録ユーザID';
COMMENT ON COLUMN PJTW_SY_HNYO_LOCK.REG_PGM_ID IS '登録プログラムID';
COMMENT ON COLUMN PJTW_SY_HNYO_LOCK.REG_TS IS '登録タイムスタンプ';
COMMENT ON COLUMN PJTW_SY_HNYO_LOCK.UPD_USR_ID IS '更新ユーザID';
COMMENT ON COLUMN PJTW_SY_HNYO_LOCK.UPD_PGM_ID IS '更新プログラムID';
COMMENT ON COLUMN PJTW_SY_HNYO_LOCK.UPD_TS IS '更新タイムスタンプ';
COMMENT ON COLUMN PJTW_SY_HNYO_LOCK.VER_NO IS 'バージョン番号';

-- ユニークインデックス用DDL

-- インデックス用DDL
