-- テーブルスペース用DDL
DEFINE tblsp  = PJNAVI_TBS
DEFINE dfile  = +DATA
DEFINE initsz = 384G
DEFINE nextsz = 100M
DEFINE blksz  = 8192

--DROP TABLESPACE &tblsp INCLUDING CONTSNTS
-- AND DATAFILES CASCADE CONSTRAINTS;

CREATE BIGFILE TABLESPACE &tblsp
DATAFILE '&dfile' SIZE &initsz
  AUTOEXTEND ON NEXT &nextsz MAXSIZE UNLIMITED
BLOCKSIZE &blksz
ONLINE PERMANENT
SEGMENT SPACE MANAGEMENT AUTO
;