-- テーブル用DDL
DROP TABLE PJTM_MI_OPENT_APP_PSN_SET CASCADE CONSTRAINTS;

CREATE TABLE PJTM_MI_OPENT_APP_PSN_SET
(
    ENT_PSN_ID                     NUMBER(10) NOT NULL ,
    APP_PSN_ID                     NUMBER(10) NOT NULL ,
    DEL_FLG                        CHAR(1) DEFAULT '0' NOT NULL ,
    REG_USR_ID                     NUMBER(10) NOT NULL ,
    REG_PGM_ID                     CHAR(11) NOT NULL ,
    REG_TS                         TIMESTAMP(3) NOT NULL ,
    UPD_USR_ID                     NUMBER(10) NOT NULL ,
    UPD_PGM_ID                     CHAR(11) NOT NULL ,
    UPD_TS                         TIMESTAMP(3) NOT NULL ,
    VER_NO                         NUMBER(10) DEFAULT 0 NOT NULL
);
ALTER TABLE PJTM_MI_OPENT_APP_PSN_SET ADD CONSTRAINT PK_PJTM_MI_OPENT_APP_PSN_SET PRIMARY KEY (ENT_PSN_ID ) ;

COMMENT ON TABLE PJTM_MI_OPENT_APP_PSN_SET IS '稼働入力承認者設定マスタ(ver.0.3)';
COMMENT ON COLUMN PJTM_MI_OPENT_APP_PSN_SET.ENT_PSN_ID IS '入力者ID';
COMMENT ON COLUMN PJTM_MI_OPENT_APP_PSN_SET.APP_PSN_ID IS '承認者ID';
COMMENT ON COLUMN PJTM_MI_OPENT_APP_PSN_SET.DEL_FLG IS '削除フラグ';
COMMENT ON COLUMN PJTM_MI_OPENT_APP_PSN_SET.REG_USR_ID IS '登録ユーザID';
COMMENT ON COLUMN PJTM_MI_OPENT_APP_PSN_SET.REG_PGM_ID IS '登録プログラムID';
COMMENT ON COLUMN PJTM_MI_OPENT_APP_PSN_SET.REG_TS IS '登録タイムスタンプ';
COMMENT ON COLUMN PJTM_MI_OPENT_APP_PSN_SET.UPD_USR_ID IS '更新ユーザID';
COMMENT ON COLUMN PJTM_MI_OPENT_APP_PSN_SET.UPD_PGM_ID IS '更新プログラムID';
COMMENT ON COLUMN PJTM_MI_OPENT_APP_PSN_SET.UPD_TS IS '更新タイムスタンプ';
COMMENT ON COLUMN PJTM_MI_OPENT_APP_PSN_SET.VER_NO IS 'バージョン番号';

-- ユニークインデックス用DDL

-- インデックス用DDL
