-- テーブル用DDL
DROP TABLE PJTM_MI_OPENT_LMT_RLS CASCADE CONSTRAINTS;

CREATE TABLE PJTM_MI_OPENT_LMT_RLS
(
    UNIQ_ID                        NUMBER(6) NOT NULL ,
    TAR_KND                        CHAR(1) DEFAULT '0' NOT NULL ,
    RLS_TAR_ID                     NUMBER(15) NOT NULL ,
    RLS_TRM_FROM                   DATE NOT NULL ,
    RLS_TRM_TO                     DATE NOT NULL ,
    RLS_SET_DT                     DATE NOT NULL ,
    VLD_DAYS                       NUMBER(2) NOT NULL ,
    MEMO                           VARCHAR2(150) ,
    INV_FLG                        CHAR(1) DEFAULT '0' NOT NULL ,
    DEL_FLG                        CHAR(1) DEFAULT '0' NOT NULL ,
    REG_USR_ID                     NUMBER(10) NOT NULL ,
    REG_PGM_ID                     CHAR(11) NOT NULL ,
    REG_TS                         TIMESTAMP(3) NOT NULL ,
    UPD_USR_ID                     NUMBER(10) NOT NULL ,
    UPD_PGM_ID                     CHAR(11) NOT NULL ,
    UPD_TS                         TIMESTAMP(3) NOT NULL ,
    VER_NO                         NUMBER(10) DEFAULT 0 NOT NULL
);
ALTER TABLE PJTM_MI_OPENT_LMT_RLS ADD CONSTRAINT PK_PJTM_MI_OPENT_LMT_RLS PRIMARY KEY (UNIQ_ID ) ;

COMMENT ON TABLE PJTM_MI_OPENT_LMT_RLS IS '稼働入力制限解除マスタ(ver.0.3)';
COMMENT ON COLUMN PJTM_MI_OPENT_LMT_RLS.UNIQ_ID IS 'ユニークID';
COMMENT ON COLUMN PJTM_MI_OPENT_LMT_RLS.TAR_KND IS '対象種別';
COMMENT ON COLUMN PJTM_MI_OPENT_LMT_RLS.RLS_TAR_ID IS '解除対象ID';
COMMENT ON COLUMN PJTM_MI_OPENT_LMT_RLS.RLS_TRM_FROM IS '解除期間From';
COMMENT ON COLUMN PJTM_MI_OPENT_LMT_RLS.RLS_TRM_TO IS '解除期間To';
COMMENT ON COLUMN PJTM_MI_OPENT_LMT_RLS.RLS_SET_DT IS '解除設定日';
COMMENT ON COLUMN PJTM_MI_OPENT_LMT_RLS.VLD_DAYS IS '有効日数';
COMMENT ON COLUMN PJTM_MI_OPENT_LMT_RLS.MEMO IS 'メモ';
COMMENT ON COLUMN PJTM_MI_OPENT_LMT_RLS.INV_FLG IS '無効フラグ';
COMMENT ON COLUMN PJTM_MI_OPENT_LMT_RLS.DEL_FLG IS '削除フラグ';
COMMENT ON COLUMN PJTM_MI_OPENT_LMT_RLS.REG_USR_ID IS '登録ユーザID';
COMMENT ON COLUMN PJTM_MI_OPENT_LMT_RLS.REG_PGM_ID IS '登録プログラムID';
COMMENT ON COLUMN PJTM_MI_OPENT_LMT_RLS.REG_TS IS '登録タイムスタンプ';
COMMENT ON COLUMN PJTM_MI_OPENT_LMT_RLS.UPD_USR_ID IS '更新ユーザID';
COMMENT ON COLUMN PJTM_MI_OPENT_LMT_RLS.UPD_PGM_ID IS '更新プログラムID';
COMMENT ON COLUMN PJTM_MI_OPENT_LMT_RLS.UPD_TS IS '更新タイムスタンプ';
COMMENT ON COLUMN PJTM_MI_OPENT_LMT_RLS.VER_NO IS 'バージョン番号';

-- ユニークインデックス用DDL

-- インデックス用DDL
