-- テーブル用DDL
DROP TABLE PJTM_MI_OPENT_LMT CASCADE CONSTRAINTS;

CREATE TABLE PJTM_MI_OPENT_LMT
(
    UNIQ_ID                        NUMBER(6) NOT NULL ,
    PST_ENT_POS_WEEK               NUMBER(2) NOT NULL ,
    FUTURE_ENT_POS_WEEK            NUMBER(2) NOT NULL ,
    FUTURE_RSLT_ENT_PMS_FLG        CHAR(1) DEFAULT '0' NOT NULL ,
    LAT_FLG                        CHAR(1) DEFAULT '0' NOT NULL ,
    DEL_FLG                        CHAR(1) DEFAULT '0' NOT NULL ,
    REG_USR_ID                     NUMBER(10) NOT NULL ,
    REG_PGM_ID                     CHAR(11) NOT NULL ,
    REG_TS                         TIMESTAMP(3) NOT NULL ,
    UPD_USR_ID                     NUMBER(10) NOT NULL ,
    UPD_PGM_ID                     CHAR(11) NOT NULL ,
    UPD_TS                         TIMESTAMP(3) NOT NULL ,
    VER_NO                         NUMBER(10) DEFAULT 0 NOT NULL
);
ALTER TABLE PJTM_MI_OPENT_LMT ADD CONSTRAINT PK_PJTM_MI_OPENT_LMT PRIMARY KEY (UNIQ_ID ) ;

COMMENT ON TABLE PJTM_MI_OPENT_LMT IS '稼働入力制限マスタ(ver.0.3)';
COMMENT ON COLUMN PJTM_MI_OPENT_LMT.UNIQ_ID IS 'ユニークID';
COMMENT ON COLUMN PJTM_MI_OPENT_LMT.PST_ENT_POS_WEEK IS '過去入力可能週';
COMMENT ON COLUMN PJTM_MI_OPENT_LMT.FUTURE_ENT_POS_WEEK IS '未来入力可能週';
COMMENT ON COLUMN PJTM_MI_OPENT_LMT.FUTURE_RSLT_ENT_PMS_FLG IS '未来実績入力許可フラグ';
COMMENT ON COLUMN PJTM_MI_OPENT_LMT.LAT_FLG IS '最新フラグ';
COMMENT ON COLUMN PJTM_MI_OPENT_LMT.DEL_FLG IS '削除フラグ';
COMMENT ON COLUMN PJTM_MI_OPENT_LMT.REG_USR_ID IS '登録ユーザID';
COMMENT ON COLUMN PJTM_MI_OPENT_LMT.REG_PGM_ID IS '登録プログラムID';
COMMENT ON COLUMN PJTM_MI_OPENT_LMT.REG_TS IS '登録タイムスタンプ';
COMMENT ON COLUMN PJTM_MI_OPENT_LMT.UPD_USR_ID IS '更新ユーザID';
COMMENT ON COLUMN PJTM_MI_OPENT_LMT.UPD_PGM_ID IS '更新プログラムID';
COMMENT ON COLUMN PJTM_MI_OPENT_LMT.UPD_TS IS '更新タイムスタンプ';
COMMENT ON COLUMN PJTM_MI_OPENT_LMT.VER_NO IS 'バージョン番号';

-- ユニークインデックス用DDL

-- インデックス用DDL
