-- テーブル用DDL
DROP TABLE PJTM_MI_OPENT_CAL CASCADE CONSTRAINTS;

CREATE TABLE PJTM_MI_OPENT_CAL
(
    ENT_TAR_MM                     CHAR(7) NOT NULL ,
    ENT_STR_DT                     DATE NOT NULL ,
    ENT_END_DT                     DATE NOT NULL ,
    DEL_FLG                        CHAR(1) DEFAULT '0' NOT NULL ,
    REG_USR_ID                     NUMBER(10) NOT NULL ,
    REG_PGM_ID                     CHAR(11) NOT NULL ,
    REG_TS                         TIMESTAMP(3) NOT NULL ,
    UPD_USR_ID                     NUMBER(10) NOT NULL ,
    UPD_PGM_ID                     CHAR(11) NOT NULL ,
    UPD_TS                         TIMESTAMP(3) NOT NULL ,
    VER_NO                         NUMBER(10) DEFAULT 0 NOT NULL
);
ALTER TABLE PJTM_MI_OPENT_CAL ADD CONSTRAINT PK_PJTM_MI_OPENT_CAL PRIMARY KEY (ENT_TAR_MM ) ;

COMMENT ON TABLE PJTM_MI_OPENT_CAL IS '稼働入力カレンダーマスタ(ver.0.3)';
COMMENT ON COLUMN PJTM_MI_OPENT_CAL.ENT_TAR_MM IS '入力対象月';
COMMENT ON COLUMN PJTM_MI_OPENT_CAL.ENT_STR_DT IS '入力開始日';
COMMENT ON COLUMN PJTM_MI_OPENT_CAL.ENT_END_DT IS '入力終了日';
COMMENT ON COLUMN PJTM_MI_OPENT_CAL.DEL_FLG IS '削除フラグ';
COMMENT ON COLUMN PJTM_MI_OPENT_CAL.REG_USR_ID IS '登録ユーザID';
COMMENT ON COLUMN PJTM_MI_OPENT_CAL.REG_PGM_ID IS '登録プログラムID';
COMMENT ON COLUMN PJTM_MI_OPENT_CAL.REG_TS IS '登録タイムスタンプ';
COMMENT ON COLUMN PJTM_MI_OPENT_CAL.UPD_USR_ID IS '更新ユーザID';
COMMENT ON COLUMN PJTM_MI_OPENT_CAL.UPD_PGM_ID IS '更新プログラムID';
COMMENT ON COLUMN PJTM_MI_OPENT_CAL.UPD_TS IS '更新タイムスタンプ';
COMMENT ON COLUMN PJTM_MI_OPENT_CAL.VER_NO IS 'バージョン番号';

-- ユニークインデックス用DDL

-- インデックス用DDL
