-- テーブル用DDL
DROP TABLE PJTR_MI_OPENT_TPL CASCADE CONSTRAINTS;

CREATE TABLE PJTR_MI_OPENT_TPL
(
    EMP_ID                         NUMBER(10) NOT NULL ,
    OPE_ENT_TPL_SEQ                NUMBER(4) NOT NULL ,
    OPE_ENT_TPL_NM                 VARCHAR2(180) ,
    MOB_USE_FLG                    CHAR(1) DEFAULT '0' NOT NULL ,
    OPENT_TPL_CMT                  VARCHAR2(3000) ,
    DEL_FLG                        CHAR(1) DEFAULT '0' NOT NULL ,
    REG_USR_ID                     NUMBER(10) NOT NULL ,
    REG_PGM_ID                     CHAR(11) NOT NULL ,
    REG_TS                         TIMESTAMP(3) NOT NULL ,
    UPD_USR_ID                     NUMBER(10) NOT NULL ,
    UPD_PGM_ID                     CHAR(11) NOT NULL ,
    UPD_TS                         TIMESTAMP(3) NOT NULL ,
    VER_NO                         NUMBER(10) DEFAULT 0 NOT NULL
);
ALTER TABLE PJTR_MI_OPENT_TPL ADD CONSTRAINT PK_PJTR_MI_OPENT_TPL PRIMARY KEY (EMP_ID, OPE_ENT_TPL_SEQ ) ;

COMMENT ON TABLE PJTR_MI_OPENT_TPL IS '稼働入力テンプレートトラン(ver.0.6)';
COMMENT ON COLUMN PJTR_MI_OPENT_TPL.EMP_ID IS '従業員ID';
COMMENT ON COLUMN PJTR_MI_OPENT_TPL.OPE_ENT_TPL_SEQ IS '稼働入力テンプレート連番';
COMMENT ON COLUMN PJTR_MI_OPENT_TPL.OPE_ENT_TPL_NM IS '稼働入力テンプレート名称';
COMMENT ON COLUMN PJTR_MI_OPENT_TPL.MOB_USE_FLG IS 'モバイル使用フラグ';
COMMENT ON COLUMN PJTR_MI_OPENT_TPL.OPENT_TPL_CMT IS '稼働入力テンプレートコメント';
COMMENT ON COLUMN PJTR_MI_OPENT_TPL.DEL_FLG IS '削除フラグ';
COMMENT ON COLUMN PJTR_MI_OPENT_TPL.REG_USR_ID IS '登録ユーザID';
COMMENT ON COLUMN PJTR_MI_OPENT_TPL.REG_PGM_ID IS '登録プログラムID';
COMMENT ON COLUMN PJTR_MI_OPENT_TPL.REG_TS IS '登録タイムスタンプ';
COMMENT ON COLUMN PJTR_MI_OPENT_TPL.UPD_USR_ID IS '更新ユーザID';
COMMENT ON COLUMN PJTR_MI_OPENT_TPL.UPD_PGM_ID IS '更新プログラムID';
COMMENT ON COLUMN PJTR_MI_OPENT_TPL.UPD_TS IS '更新タイムスタンプ';
COMMENT ON COLUMN PJTR_MI_OPENT_TPL.VER_NO IS 'バージョン番号';

-- ユニークインデックス用DDL

-- インデックス用DDL
