-- テーブル用DDL
DROP TABLE PJTR_MI_OPE_DT_INFO CASCADE CONSTRAINTS;

CREATE TABLE PJTR_MI_OPE_DT_INFO
(
    ENT_PSN_ID                     NUMBER(10) NOT NULL ,
    OPE_DT                         DATE NOT NULL ,
    OPE_STATS                      CHAR(1) DEFAULT '0' NOT NULL ,
    COST_DIV_DONE_FLG              CHAR(1) DEFAULT '0' NOT NULL ,
    BUSI_PROC_DT                   DATE NOT NULL ,
    DEL_FLG                        CHAR(1) DEFAULT '0' NOT NULL ,
    REG_USR_ID                     NUMBER(10) NOT NULL ,
    REG_PGM_ID                     CHAR(11) NOT NULL ,
    REG_TS                         TIMESTAMP(3) NOT NULL ,
    UPD_USR_ID                     NUMBER(10) NOT NULL ,
    UPD_PGM_ID                     CHAR(11) NOT NULL ,
    UPD_TS                         TIMESTAMP(3) NOT NULL ,
    VER_NO                         NUMBER(10) DEFAULT 0 NOT NULL
);
ALTER TABLE PJTR_MI_OPE_DT_INFO ADD CONSTRAINT PK_PJTR_MI_OPE_DT_INFO PRIMARY KEY (ENT_PSN_ID, OPE_DT ) ;

COMMENT ON TABLE PJTR_MI_OPE_DT_INFO IS '稼働日情報トラン(ver.0.4)';
COMMENT ON COLUMN PJTR_MI_OPE_DT_INFO.ENT_PSN_ID IS '入力者ID';
COMMENT ON COLUMN PJTR_MI_OPE_DT_INFO.OPE_DT IS '稼働日';
COMMENT ON COLUMN PJTR_MI_OPE_DT_INFO.OPE_STATS IS '稼働ステータス';
COMMENT ON COLUMN PJTR_MI_OPE_DT_INFO.COST_DIV_DONE_FLG IS '原価配分済フラグ';
COMMENT ON COLUMN PJTR_MI_OPE_DT_INFO.BUSI_PROC_DT IS '業務処理日付';
COMMENT ON COLUMN PJTR_MI_OPE_DT_INFO.DEL_FLG IS '削除フラグ';
COMMENT ON COLUMN PJTR_MI_OPE_DT_INFO.REG_USR_ID IS '登録ユーザID';
COMMENT ON COLUMN PJTR_MI_OPE_DT_INFO.REG_PGM_ID IS '登録プログラムID';
COMMENT ON COLUMN PJTR_MI_OPE_DT_INFO.REG_TS IS '登録タイムスタンプ';
COMMENT ON COLUMN PJTR_MI_OPE_DT_INFO.UPD_USR_ID IS '更新ユーザID';
COMMENT ON COLUMN PJTR_MI_OPE_DT_INFO.UPD_PGM_ID IS '更新プログラムID';
COMMENT ON COLUMN PJTR_MI_OPE_DT_INFO.UPD_TS IS '更新タイムスタンプ';
COMMENT ON COLUMN PJTR_MI_OPE_DT_INFO.VER_NO IS 'バージョン番号';

-- ユニークインデックス用DDL

-- インデックス用DDL
