-- テーブル用DDL
DROP TABLE PJTR_MI_OPENT_CMT CASCADE CONSTRAINTS;

CREATE TABLE PJTR_MI_OPENT_CMT
(
    ENT_PSN_ID                     NUMBER(10) NOT NULL ,
    OPE_DT                         DATE NOT NULL ,
    CMT_KND                        CHAR(1) DEFAULT '0' NOT NULL ,
    OPENT_CMT                      VARCHAR2(1500) ,
    DEL_FLG                        CHAR(1) DEFAULT '0' NOT NULL ,
    REG_USR_ID                     NUMBER(10) NOT NULL ,
    REG_PGM_ID                     CHAR(11) NOT NULL ,
    REG_TS                         TIMESTAMP(3) NOT NULL ,
    UPD_USR_ID                     NUMBER(10) NOT NULL ,
    UPD_PGM_ID                     CHAR(11) NOT NULL ,
    UPD_TS                         TIMESTAMP(3) NOT NULL ,
    VER_NO                         NUMBER(10) DEFAULT 0 NOT NULL
);
ALTER TABLE PJTR_MI_OPENT_CMT ADD CONSTRAINT PK_PJTR_MI_OPENT_CMT PRIMARY KEY (ENT_PSN_ID, OPE_DT, CMT_KND ) ;

COMMENT ON TABLE PJTR_MI_OPENT_CMT IS '稼働入力コメントトラン(ver.0.3)';
COMMENT ON COLUMN PJTR_MI_OPENT_CMT.ENT_PSN_ID IS '入力者ID';
COMMENT ON COLUMN PJTR_MI_OPENT_CMT.OPE_DT IS '稼働日';
COMMENT ON COLUMN PJTR_MI_OPENT_CMT.CMT_KND IS 'コメント種別';
COMMENT ON COLUMN PJTR_MI_OPENT_CMT.OPENT_CMT IS '稼働入力コメント';
COMMENT ON COLUMN PJTR_MI_OPENT_CMT.DEL_FLG IS '削除フラグ';
COMMENT ON COLUMN PJTR_MI_OPENT_CMT.REG_USR_ID IS '登録ユーザID';
COMMENT ON COLUMN PJTR_MI_OPENT_CMT.REG_PGM_ID IS '登録プログラムID';
COMMENT ON COLUMN PJTR_MI_OPENT_CMT.REG_TS IS '登録タイムスタンプ';
COMMENT ON COLUMN PJTR_MI_OPENT_CMT.UPD_USR_ID IS '更新ユーザID';
COMMENT ON COLUMN PJTR_MI_OPENT_CMT.UPD_PGM_ID IS '更新プログラムID';
COMMENT ON COLUMN PJTR_MI_OPENT_CMT.UPD_TS IS '更新タイムスタンプ';
COMMENT ON COLUMN PJTR_MI_OPENT_CMT.VER_NO IS 'バージョン番号';

-- ユニークインデックス用DDL

-- インデックス用DDL
