-- テーブル用DDL
DROP TABLE PJTR_MI_NEXTMI_PRJ_TSK CASCADE CONSTRAINTS;

CREATE TABLE PJTR_MI_NEXTMI_PRJ_TSK
(
    TSK_ID                         NUMBER(15) NOT NULL ,
    PRJ_CD                         CHAR(10) NOT NULL ,
    TSK_NO                         VARCHAR2(75) NOT NULL ,
    NEXTMI_TSK_NM                  VARCHAR2(60) NOT NULL ,
    TSK_VLD_STR_DT                 DATE ,
    TSK_VLD_END_DT                 DATE ,
    LEVY_POS_FLG                   CHAR(1) DEFAULT '0' NOT NULL ,
    SV_TYP_CD                      VARCHAR2(30) ,
    TSK_ENF_ORGAN_ID               NUMBER(15) NOT NULL ,
    TRAN_MNG_INFO_VLD_STR_DT       DATE NOT NULL ,
    TRAN_MNG_INFO_VLD_END_DT       DATE ,
    FORM_SEG                       CHAR(3) ,
    FORM_SEG_NM                    VARCHAR2(360) ,
    VAC_FLG                        CHAR(1) DEFAULT '0' NOT NULL ,
    DEL_FLG                        CHAR(1) DEFAULT '0' NOT NULL ,
    REG_USR_ID                     NUMBER(10) NOT NULL ,
    REG_PGM_ID                     CHAR(11) NOT NULL ,
    REG_TS                         TIMESTAMP(3) NOT NULL ,
    UPD_USR_ID                     NUMBER(10) NOT NULL ,
    UPD_PGM_ID                     CHAR(11) NOT NULL ,
    UPD_TS                         TIMESTAMP(3) NOT NULL ,
    VER_NO                         NUMBER(10) DEFAULT 0 NOT NULL
);
ALTER TABLE PJTR_MI_NEXTMI_PRJ_TSK ADD CONSTRAINT PK_PJTR_MI_NEXTMI_PRJ_TSK PRIMARY KEY (TSK_ID ) ;

COMMENT ON TABLE PJTR_MI_NEXTMI_PRJ_TSK IS 'NextMIプロジェクトタスクトラン(ver.0.7)';
COMMENT ON COLUMN PJTR_MI_NEXTMI_PRJ_TSK.TSK_ID IS 'タスクID';
COMMENT ON COLUMN PJTR_MI_NEXTMI_PRJ_TSK.PRJ_CD IS 'プロジェクトコード';
COMMENT ON COLUMN PJTR_MI_NEXTMI_PRJ_TSK.TSK_NO IS 'タスク番号';
COMMENT ON COLUMN PJTR_MI_NEXTMI_PRJ_TSK.NEXTMI_TSK_NM IS 'NextMIタスク名';
COMMENT ON COLUMN PJTR_MI_NEXTMI_PRJ_TSK.TSK_VLD_STR_DT IS 'タスク有効開始日';
COMMENT ON COLUMN PJTR_MI_NEXTMI_PRJ_TSK.TSK_VLD_END_DT IS 'タスク有効終了日';
COMMENT ON COLUMN PJTR_MI_NEXTMI_PRJ_TSK.LEVY_POS_FLG IS '賦課可能フラグ';
COMMENT ON COLUMN PJTR_MI_NEXTMI_PRJ_TSK.SV_TYP_CD IS 'サービスタイプコード';
COMMENT ON COLUMN PJTR_MI_NEXTMI_PRJ_TSK.TSK_ENF_ORGAN_ID IS 'タスク実施組織ID';
COMMENT ON COLUMN PJTR_MI_NEXTMI_PRJ_TSK.TRAN_MNG_INFO_VLD_STR_DT IS '取引管理情報有効開始日';
COMMENT ON COLUMN PJTR_MI_NEXTMI_PRJ_TSK.TRAN_MNG_INFO_VLD_END_DT IS '取引管理情報有効終了日';
COMMENT ON COLUMN PJTR_MI_NEXTMI_PRJ_TSK.FORM_SEG IS '形態別区分';
COMMENT ON COLUMN PJTR_MI_NEXTMI_PRJ_TSK.FORM_SEG_NM IS '形態別区分名称';
COMMENT ON COLUMN PJTR_MI_NEXTMI_PRJ_TSK.VAC_FLG IS '休暇フラグ';
COMMENT ON COLUMN PJTR_MI_NEXTMI_PRJ_TSK.DEL_FLG IS '削除フラグ';
COMMENT ON COLUMN PJTR_MI_NEXTMI_PRJ_TSK.REG_USR_ID IS '登録ユーザID';
COMMENT ON COLUMN PJTR_MI_NEXTMI_PRJ_TSK.REG_PGM_ID IS '登録プログラムID';
COMMENT ON COLUMN PJTR_MI_NEXTMI_PRJ_TSK.REG_TS IS '登録タイムスタンプ';
COMMENT ON COLUMN PJTR_MI_NEXTMI_PRJ_TSK.UPD_USR_ID IS '更新ユーザID';
COMMENT ON COLUMN PJTR_MI_NEXTMI_PRJ_TSK.UPD_PGM_ID IS '更新プログラムID';
COMMENT ON COLUMN PJTR_MI_NEXTMI_PRJ_TSK.UPD_TS IS '更新タイムスタンプ';
COMMENT ON COLUMN PJTR_MI_NEXTMI_PRJ_TSK.VER_NO IS 'バージョン番号';

-- ユニークインデックス用DDL
CREATE UNIQUE INDEX UX_PJTR_MI_NEXTMI_PRJ_TSK ON PJTR_MI_NEXTMI_PRJ_TSK (
    PRJ_CD ,
    TSK_NO 
);

-- インデックス用DDL
