-- テーブル用DDL
DROP TABLE PJTR_MI_OPENT_TPL_DT CASCADE CONSTRAINTS;

CREATE TABLE PJTR_MI_OPENT_TPL_DT
(
    EMP_ID                         NUMBER(10) NOT NULL ,
    OPE_ENT_TPL_SEQ                NUMBER(4) NOT NULL ,
    TSK_ID                         NUMBER(15) NOT NULL ,
    TSK_MK_SYS_SEG                 CHAR(1) DEFAULT '0' NOT NULL ,
    DSP_SEQ                        NUMBER(4) NOT NULL ,
    DEL_FLG                        CHAR(1) DEFAULT '0' NOT NULL ,
    REG_USR_ID                     NUMBER(10) NOT NULL ,
    REG_PGM_ID                     CHAR(11) NOT NULL ,
    REG_TS                         TIMESTAMP(3) NOT NULL ,
    UPD_USR_ID                     NUMBER(10) NOT NULL ,
    UPD_PGM_ID                     CHAR(11) NOT NULL ,
    UPD_TS                         TIMESTAMP(3) NOT NULL ,
    VER_NO                         NUMBER(10) DEFAULT 0 NOT NULL
);
ALTER TABLE PJTR_MI_OPENT_TPL_DT ADD CONSTRAINT PK_PJTR_MI_OPENT_TPL_DT PRIMARY KEY (EMP_ID, OPE_ENT_TPL_SEQ, TSK_ID, TSK_MK_SYS_SEG, DSP_SEQ ) ;

COMMENT ON TABLE PJTR_MI_OPENT_TPL_DT IS '稼働入力テンプレート明細トラン(ver.0.4)';
COMMENT ON COLUMN PJTR_MI_OPENT_TPL_DT.EMP_ID IS '従業員ID';
COMMENT ON COLUMN PJTR_MI_OPENT_TPL_DT.OPE_ENT_TPL_SEQ IS '稼働入力テンプレート連番';
COMMENT ON COLUMN PJTR_MI_OPENT_TPL_DT.TSK_ID IS 'タスクID';
COMMENT ON COLUMN PJTR_MI_OPENT_TPL_DT.TSK_MK_SYS_SEG IS 'タスク作成システム区分';
COMMENT ON COLUMN PJTR_MI_OPENT_TPL_DT.DSP_SEQ IS '表示順';
COMMENT ON COLUMN PJTR_MI_OPENT_TPL_DT.DEL_FLG IS '削除フラグ';
COMMENT ON COLUMN PJTR_MI_OPENT_TPL_DT.REG_USR_ID IS '登録ユーザID';
COMMENT ON COLUMN PJTR_MI_OPENT_TPL_DT.REG_PGM_ID IS '登録プログラムID';
COMMENT ON COLUMN PJTR_MI_OPENT_TPL_DT.REG_TS IS '登録タイムスタンプ';
COMMENT ON COLUMN PJTR_MI_OPENT_TPL_DT.UPD_USR_ID IS '更新ユーザID';
COMMENT ON COLUMN PJTR_MI_OPENT_TPL_DT.UPD_PGM_ID IS '更新プログラムID';
COMMENT ON COLUMN PJTR_MI_OPENT_TPL_DT.UPD_TS IS '更新タイムスタンプ';
COMMENT ON COLUMN PJTR_MI_OPENT_TPL_DT.VER_NO IS 'バージョン番号';

-- ユニークインデックス用DDL

-- インデックス用DDL
