-- テーブル用DDL
DROP TABLE PJTR_MI_OPE_DT CASCADE CONSTRAINTS;

CREATE TABLE PJTR_MI_OPE_DT
(
    OPE_DT_ID                      NUMBER(15) NOT NULL ,
    ENT_PSN_ID                     NUMBER(10) NOT NULL ,
    OPE_DT                         DATE NOT NULL ,
    TSK_ID                         NUMBER(15) NOT NULL ,
    TSK_MK_SYS_SEG                 CHAR(1) DEFAULT '0' NOT NULL ,
    OPE_DT_SEQ                     NUMBER(4) NOT NULL ,
    PRJ_CD                         CHAR(10) NOT NULL ,
    OPE_TM                         NUMBER(4,2) ,
    EGY_CHG_ID                     NUMBER(10) ,
    OPE_DT_CMT                     VARCHAR2(360) ,
    TMP_COMP_DONE_FLG              CHAR(1) DEFAULT '0' NOT NULL ,
    BUSI_PROC_DT                   DATE NOT NULL ,
    DEL_FLG                        CHAR(1) DEFAULT '0' NOT NULL ,
    REG_USR_ID                     NUMBER(10) NOT NULL ,
    REG_PGM_ID                     CHAR(11) NOT NULL ,
    REG_TS                         TIMESTAMP(3) NOT NULL ,
    UPD_USR_ID                     NUMBER(10) NOT NULL ,
    UPD_PGM_ID                     CHAR(11) NOT NULL ,
    UPD_TS                         TIMESTAMP(3) NOT NULL ,
    VER_NO                         NUMBER(10) DEFAULT 0 NOT NULL
);
ALTER TABLE PJTR_MI_OPE_DT ADD CONSTRAINT PK_PJTR_MI_OPE_DT PRIMARY KEY (OPE_DT_ID ) ;

COMMENT ON TABLE PJTR_MI_OPE_DT IS '稼働明細トラン(ver.0.7)';
COMMENT ON COLUMN PJTR_MI_OPE_DT.OPE_DT_ID IS '稼働明細ID';
COMMENT ON COLUMN PJTR_MI_OPE_DT.ENT_PSN_ID IS '入力者ID';
COMMENT ON COLUMN PJTR_MI_OPE_DT.OPE_DT IS '稼働日';
COMMENT ON COLUMN PJTR_MI_OPE_DT.TSK_ID IS 'タスクID';
COMMENT ON COLUMN PJTR_MI_OPE_DT.TSK_MK_SYS_SEG IS 'タスク作成システム区分';
COMMENT ON COLUMN PJTR_MI_OPE_DT.OPE_DT_SEQ IS '稼働明細連番';
COMMENT ON COLUMN PJTR_MI_OPE_DT.PRJ_CD IS 'プロジェクトコード';
COMMENT ON COLUMN PJTR_MI_OPE_DT.OPE_TM IS '稼働時間';
COMMENT ON COLUMN PJTR_MI_OPE_DT.EGY_CHG_ID IS '営業担当者ID';
COMMENT ON COLUMN PJTR_MI_OPE_DT.OPE_DT_CMT IS '稼働明細コメント';
COMMENT ON COLUMN PJTR_MI_OPE_DT.TMP_COMP_DONE_FLG IS '仮計算済フラグ';
COMMENT ON COLUMN PJTR_MI_OPE_DT.BUSI_PROC_DT IS '業務処理日付';
COMMENT ON COLUMN PJTR_MI_OPE_DT.DEL_FLG IS '削除フラグ';
COMMENT ON COLUMN PJTR_MI_OPE_DT.REG_USR_ID IS '登録ユーザID';
COMMENT ON COLUMN PJTR_MI_OPE_DT.REG_PGM_ID IS '登録プログラムID';
COMMENT ON COLUMN PJTR_MI_OPE_DT.REG_TS IS '登録タイムスタンプ';
COMMENT ON COLUMN PJTR_MI_OPE_DT.UPD_USR_ID IS '更新ユーザID';
COMMENT ON COLUMN PJTR_MI_OPE_DT.UPD_PGM_ID IS '更新プログラムID';
COMMENT ON COLUMN PJTR_MI_OPE_DT.UPD_TS IS '更新タイムスタンプ';
COMMENT ON COLUMN PJTR_MI_OPE_DT.VER_NO IS 'バージョン番号';

-- ユニークインデックス用DDL
CREATE UNIQUE INDEX UX_PJTR_MI_OPE_DT ON PJTR_MI_OPE_DT (
    ENT_PSN_ID ,
    OPE_DT ,
    TSK_ID ,
    TSK_MK_SYS_SEG ,
    OPE_DT_SEQ 
);

-- インデックス用DDL
CREATE INDEX IX1_PJTR_MI_OPE_DT ON PJTR_MI_OPE_DT (
    PRJ_CD 
);

