-- テーブル用DDL
DROP TABLE PJTR_MI_NEXTMI_PRJ CASCADE CONSTRAINTS;

CREATE TABLE PJTR_MI_NEXTMI_PRJ
(
    PRJ_CD                         CHAR(10) NOT NULL ,
    PRJ_NM                         VARCHAR2(90) NOT NULL ,
    PRJ_TYP                        VARCHAR2(20) NOT NULL ,
    PRJ_STATS                      CHAR(3) NOT NULL ,
    PRJ_OWN_ORGAN_CD               VARCHAR2(150) NOT NULL ,
    PRJ_STR_DT                     DATE ,
    PRJ_END_DT                     DATE ,
    CONT_SEG                       CHAR(1) DEFAULT '0' NOT NULL ,
    PRJ_EGY_EMP_CD                 VARCHAR2(30) ,
    DEL_FLG                        CHAR(1) DEFAULT '0' NOT NULL ,
    REG_USR_ID                     NUMBER(10) NOT NULL ,
    REG_PGM_ID                     CHAR(11) NOT NULL ,
    REG_TS                         TIMESTAMP(3) NOT NULL ,
    UPD_USR_ID                     NUMBER(10) NOT NULL ,
    UPD_PGM_ID                     CHAR(11) NOT NULL ,
    UPD_TS                         TIMESTAMP(3) NOT NULL ,
    VER_NO                         NUMBER(10) DEFAULT 0 NOT NULL
);
ALTER TABLE PJTR_MI_NEXTMI_PRJ ADD CONSTRAINT PK_PJTR_MI_NEXTMI_PRJ PRIMARY KEY (PRJ_CD ) ;

COMMENT ON TABLE PJTR_MI_NEXTMI_PRJ IS 'NextMIプロジェクトトラン(ver.0.6)';
COMMENT ON COLUMN PJTR_MI_NEXTMI_PRJ.PRJ_CD IS 'プロジェクトコード';
COMMENT ON COLUMN PJTR_MI_NEXTMI_PRJ.PRJ_NM IS 'プロジェクト名';
COMMENT ON COLUMN PJTR_MI_NEXTMI_PRJ.PRJ_TYP IS 'プロジェクトタイプ';
COMMENT ON COLUMN PJTR_MI_NEXTMI_PRJ.PRJ_STATS IS 'プロジェクトステータス';
COMMENT ON COLUMN PJTR_MI_NEXTMI_PRJ.PRJ_OWN_ORGAN_CD IS 'プロジェクト所有組織コード';
COMMENT ON COLUMN PJTR_MI_NEXTMI_PRJ.PRJ_STR_DT IS 'プロジェクト開始日';
COMMENT ON COLUMN PJTR_MI_NEXTMI_PRJ.PRJ_END_DT IS 'プロジェクト終了日';
COMMENT ON COLUMN PJTR_MI_NEXTMI_PRJ.CONT_SEG IS '成約区分';
COMMENT ON COLUMN PJTR_MI_NEXTMI_PRJ.PRJ_EGY_EMP_CD IS 'プロジェクト営業従業員コード';
COMMENT ON COLUMN PJTR_MI_NEXTMI_PRJ.DEL_FLG IS '削除フラグ';
COMMENT ON COLUMN PJTR_MI_NEXTMI_PRJ.REG_USR_ID IS '登録ユーザID';
COMMENT ON COLUMN PJTR_MI_NEXTMI_PRJ.REG_PGM_ID IS '登録プログラムID';
COMMENT ON COLUMN PJTR_MI_NEXTMI_PRJ.REG_TS IS '登録タイムスタンプ';
COMMENT ON COLUMN PJTR_MI_NEXTMI_PRJ.UPD_USR_ID IS '更新ユーザID';
COMMENT ON COLUMN PJTR_MI_NEXTMI_PRJ.UPD_PGM_ID IS '更新プログラムID';
COMMENT ON COLUMN PJTR_MI_NEXTMI_PRJ.UPD_TS IS '更新タイムスタンプ';
COMMENT ON COLUMN PJTR_MI_NEXTMI_PRJ.VER_NO IS 'バージョン番号';

-- ユニークインデックス用DDL

-- インデックス用DDL
