-- テーブル用DDL
DROP TABLE PJTR_MI_OPENT_HIST CASCADE CONSTRAINTS;

CREATE TABLE PJTR_MI_OPENT_HIST
(
    OPE_DT_ID                      NUMBER(15) NOT NULL ,
    OPE_DT_VER_NO                  NUMBER(10) NOT NULL ,
    ENT_PSN_ID                     NUMBER(10) NOT NULL ,
    OPE_DT                         DATE NOT NULL ,
    TSK_ID                         NUMBER(15) NOT NULL ,
    TSK_MK_SYS_SEG                 CHAR(1) DEFAULT '0' NOT NULL ,
    OPE_DT_SEQ                     NUMBER(4) NOT NULL ,
    PRJ_CD                         CHAR(10) NOT NULL ,
    OPE_TM                         NUMBER(4,2) NOT NULL ,
    OPE_STATS                      CHAR(1) DEFAULT '0' NOT NULL ,
    APP_PSN_ID                     NUMBER(10) NOT NULL ,
    EXE_PSN_ID                     NUMBER(10) NOT NULL ,
    EXE_HMS                        TIMESTAMP(3) NOT NULL ,
    DEL_FLG                        CHAR(1) DEFAULT '0' NOT NULL ,
    REG_USR_ID                     NUMBER(10) NOT NULL ,
    REG_PGM_ID                     CHAR(11) NOT NULL ,
    REG_TS                         TIMESTAMP(3) NOT NULL ,
    UPD_USR_ID                     NUMBER(10) NOT NULL ,
    UPD_PGM_ID                     CHAR(11) NOT NULL ,
    UPD_TS                         TIMESTAMP(3) NOT NULL ,
    VER_NO                         NUMBER(10) DEFAULT 0 NOT NULL
);
ALTER TABLE PJTR_MI_OPENT_HIST ADD CONSTRAINT PK_PJTR_MI_OPENT_HIST PRIMARY KEY (OPE_DT_ID, OPE_DT_VER_NO ) ;

COMMENT ON TABLE PJTR_MI_OPENT_HIST IS '稼働入力履歴トラン(ver.0.8)';
COMMENT ON COLUMN PJTR_MI_OPENT_HIST.OPE_DT_ID IS '稼働明細ID';
COMMENT ON COLUMN PJTR_MI_OPENT_HIST.OPE_DT_VER_NO IS '稼働明細バージョン番号';
COMMENT ON COLUMN PJTR_MI_OPENT_HIST.ENT_PSN_ID IS '入力者ID';
COMMENT ON COLUMN PJTR_MI_OPENT_HIST.OPE_DT IS '稼働日';
COMMENT ON COLUMN PJTR_MI_OPENT_HIST.TSK_ID IS 'タスクID';
COMMENT ON COLUMN PJTR_MI_OPENT_HIST.TSK_MK_SYS_SEG IS 'タスク作成システム区分';
COMMENT ON COLUMN PJTR_MI_OPENT_HIST.OPE_DT_SEQ IS '稼働明細連番';
COMMENT ON COLUMN PJTR_MI_OPENT_HIST.PRJ_CD IS 'プロジェクトコード';
COMMENT ON COLUMN PJTR_MI_OPENT_HIST.OPE_TM IS '稼働時間';
COMMENT ON COLUMN PJTR_MI_OPENT_HIST.OPE_STATS IS '稼働ステータス';
COMMENT ON COLUMN PJTR_MI_OPENT_HIST.APP_PSN_ID IS '承認者ID';
COMMENT ON COLUMN PJTR_MI_OPENT_HIST.EXE_PSN_ID IS '実行者ID';
COMMENT ON COLUMN PJTR_MI_OPENT_HIST.EXE_HMS IS '実行日時';
COMMENT ON COLUMN PJTR_MI_OPENT_HIST.DEL_FLG IS '削除フラグ';
COMMENT ON COLUMN PJTR_MI_OPENT_HIST.REG_USR_ID IS '登録ユーザID';
COMMENT ON COLUMN PJTR_MI_OPENT_HIST.REG_PGM_ID IS '登録プログラムID';
COMMENT ON COLUMN PJTR_MI_OPENT_HIST.REG_TS IS '登録タイムスタンプ';
COMMENT ON COLUMN PJTR_MI_OPENT_HIST.UPD_USR_ID IS '更新ユーザID';
COMMENT ON COLUMN PJTR_MI_OPENT_HIST.UPD_PGM_ID IS '更新プログラムID';
COMMENT ON COLUMN PJTR_MI_OPENT_HIST.UPD_TS IS '更新タイムスタンプ';
COMMENT ON COLUMN PJTR_MI_OPENT_HIST.VER_NO IS 'バージョン番号';

-- ユニークインデックス用DDL

-- インデックス用DDL
CREATE INDEX IX1_PJTR_MI_OPENT_HIST ON PJTR_MI_OPENT_HIST (
    ENT_PSN_ID ,
    OPE_DT ,
    OPE_STATS 
);

