-- テーブル用DDL
DROP TABLE PJTR_MI_NEXTMI_PRJ_MBR CASCADE CONSTRAINTS;

CREATE TABLE PJTR_MI_NEXTMI_PRJ_MBR
(
    PRJ_CD                         CHAR(10) NOT NULL ,
    PRJ_MBR_EMP_CD                 VARCHAR2(30) NOT NULL ,
    ROLE                           VARCHAR2(4) NOT NULL ,
    VLD_STR_DT                     DATE NOT NULL ,
    VLD_END_DT                     DATE ,
    DEL_FLG                        CHAR(1) DEFAULT '0' NOT NULL ,
    REG_USR_ID                     NUMBER(10) NOT NULL ,
    REG_PGM_ID                     CHAR(11) NOT NULL ,
    REG_TS                         TIMESTAMP(3) NOT NULL ,
    UPD_USR_ID                     NUMBER(10) NOT NULL ,
    UPD_PGM_ID                     CHAR(11) NOT NULL ,
    UPD_TS                         TIMESTAMP(3) NOT NULL ,
    VER_NO                         NUMBER(10) DEFAULT 0 NOT NULL
);
ALTER TABLE PJTR_MI_NEXTMI_PRJ_MBR ADD CONSTRAINT PK_PJTR_MI_NEXTMI_PRJ_MBR PRIMARY KEY (PRJ_CD, PRJ_MBR_EMP_CD, ROLE, VLD_STR_DT ) ;

COMMENT ON TABLE PJTR_MI_NEXTMI_PRJ_MBR IS 'NextMIプロジェクトメンバトラン(ver.0.6)';
COMMENT ON COLUMN PJTR_MI_NEXTMI_PRJ_MBR.PRJ_CD IS 'プロジェクトコード';
COMMENT ON COLUMN PJTR_MI_NEXTMI_PRJ_MBR.PRJ_MBR_EMP_CD IS 'プロジェクトメンバ従業員コード';
COMMENT ON COLUMN PJTR_MI_NEXTMI_PRJ_MBR.ROLE IS 'ロール';
COMMENT ON COLUMN PJTR_MI_NEXTMI_PRJ_MBR.VLD_STR_DT IS '有効開始日';
COMMENT ON COLUMN PJTR_MI_NEXTMI_PRJ_MBR.VLD_END_DT IS '有効終了日';
COMMENT ON COLUMN PJTR_MI_NEXTMI_PRJ_MBR.DEL_FLG IS '削除フラグ';
COMMENT ON COLUMN PJTR_MI_NEXTMI_PRJ_MBR.REG_USR_ID IS '登録ユーザID';
COMMENT ON COLUMN PJTR_MI_NEXTMI_PRJ_MBR.REG_PGM_ID IS '登録プログラムID';
COMMENT ON COLUMN PJTR_MI_NEXTMI_PRJ_MBR.REG_TS IS '登録タイムスタンプ';
COMMENT ON COLUMN PJTR_MI_NEXTMI_PRJ_MBR.UPD_USR_ID IS '更新ユーザID';
COMMENT ON COLUMN PJTR_MI_NEXTMI_PRJ_MBR.UPD_PGM_ID IS '更新プログラムID';
COMMENT ON COLUMN PJTR_MI_NEXTMI_PRJ_MBR.UPD_TS IS '更新タイムスタンプ';
COMMENT ON COLUMN PJTR_MI_NEXTMI_PRJ_MBR.VER_NO IS 'バージョン番号';

-- ユニークインデックス用DDL

-- インデックス用DDL
CREATE INDEX IX1_PJTR_MI_NEXTMI_PRJ_MBR ON PJTR_MI_NEXTMI_PRJ_MBR (
    PRJ_MBR_EMP_CD ,
    VLD_STR_DT ,
    VLD_END_DT 
);

