-- テーブル用DDL
DROP TABLE PJTW_MI_OPENT_AUTH_DLG_LNK CASCADE CONSTRAINTS;

CREATE TABLE PJTW_MI_OPENT_AUTH_DLG_LNK
(
    DLGFRM_APP_PSN_ID              NUMBER(10) NOT NULL ,
    AUTH_TRANS_SEQ                 NUMBER(4) NOT NULL ,
    DLGTO_APP_PSN_ID               NUMBER(10) NOT NULL ,
    AUTH_TRANS_STR_DT              DATE NOT NULL ,
    AUTH_TRANS_END_DT              DATE NOT NULL ,
    DEL_FLG                        CHAR(1) DEFAULT '0' NOT NULL ,
    REG_USR_ID                     NUMBER(10) NOT NULL ,
    REG_PGM_ID                     CHAR(11) NOT NULL ,
    REG_TS                         TIMESTAMP(3) NOT NULL ,
    UPD_USR_ID                     NUMBER(10) NOT NULL ,
    UPD_PGM_ID                     CHAR(11) NOT NULL ,
    UPD_TS                         TIMESTAMP(3) NOT NULL ,
    VER_NO                         NUMBER(10) DEFAULT 0 NOT NULL
);
ALTER TABLE PJTW_MI_OPENT_AUTH_DLG_LNK ADD CONSTRAINT PK_PJTW_MI_OPENT_AUTH_DLG_LNK PRIMARY KEY (DLGFRM_APP_PSN_ID, AUTH_TRANS_SEQ ) ;

COMMENT ON TABLE PJTW_MI_OPENT_AUTH_DLG_LNK IS '稼働入力承認権限委譲設定連携ワーク(ver.0.1)';
COMMENT ON COLUMN PJTW_MI_OPENT_AUTH_DLG_LNK.DLGFRM_APP_PSN_ID IS '委譲元承認者ID';
COMMENT ON COLUMN PJTW_MI_OPENT_AUTH_DLG_LNK.AUTH_TRANS_SEQ IS '承認権限委譲連番';
COMMENT ON COLUMN PJTW_MI_OPENT_AUTH_DLG_LNK.DLGTO_APP_PSN_ID IS '委譲先承認者ID';
COMMENT ON COLUMN PJTW_MI_OPENT_AUTH_DLG_LNK.AUTH_TRANS_STR_DT IS '承認権限委譲開始日';
COMMENT ON COLUMN PJTW_MI_OPENT_AUTH_DLG_LNK.AUTH_TRANS_END_DT IS '承認権限委譲終了日';
COMMENT ON COLUMN PJTW_MI_OPENT_AUTH_DLG_LNK.DEL_FLG IS '削除フラグ';
COMMENT ON COLUMN PJTW_MI_OPENT_AUTH_DLG_LNK.REG_USR_ID IS '登録ユーザID';
COMMENT ON COLUMN PJTW_MI_OPENT_AUTH_DLG_LNK.REG_PGM_ID IS '登録プログラムID';
COMMENT ON COLUMN PJTW_MI_OPENT_AUTH_DLG_LNK.REG_TS IS '登録タイムスタンプ';
COMMENT ON COLUMN PJTW_MI_OPENT_AUTH_DLG_LNK.UPD_USR_ID IS '更新ユーザID';
COMMENT ON COLUMN PJTW_MI_OPENT_AUTH_DLG_LNK.UPD_PGM_ID IS '更新プログラムID';
COMMENT ON COLUMN PJTW_MI_OPENT_AUTH_DLG_LNK.UPD_TS IS '更新タイムスタンプ';
COMMENT ON COLUMN PJTW_MI_OPENT_AUTH_DLG_LNK.VER_NO IS 'バージョン番号';

-- ユニークインデックス用DDL

-- インデックス用DDL
