--NextMIプロジェクトメンバ(NextMIプロジェクトメンバトラン)と
--PJNaviプロジェクトメンバ(プロジェクトリソーストラン)の連結VIEW
--PK:プロジェクトコード,従業員ID,ロール

CREATE OR REPLACE VIEW PJVR_MI_PRJ_MBR_UNI AS
SELECT NEXTMI_PRJ_MBR.PRJ_CD               AS PRJ_CD
     , NEXTMI_PRJ_MBR.PRJ_MBR_EMP_CD       AS PRJ_MBR_EMP_CD
     , NEXTMI_PRJ_MBR.ROLE                 AS ROLE
     , NEXTMI_PRJ_MBR.VLD_STR_DT           AS VLD_STR_DT
     , NEXTMI_PRJ_MBR.VLD_END_DT           AS VLD_END_DT
  FROM PJTR_MI_NEXTMI_PRJ_MBR NEXTMI_PRJ_MBR
 WHERE DEL_FLG = '0'
UNION ALL
SELECT PRJ_RESRC.PRJ_CD                    AS PRJ_CD
     , PRJ_RESRC.PRJ_RESRC_EMP_CD          AS PRJ_MBR_EMP_CD
     , PRJ_RESRC.PRJ_RESRC_ROLE            AS ROLE
     , PRJ_RESRC.PRJ_RESRC_STR_DT          AS VLD_STR_DT
     , PRJ_RESRC.PRJ_RESRC_END_DT          AS VLD_END_DT
  FROM PJTR_PJ_PRJ_RESRC PRJ_RESRC
 WHERE DEL_FLG = '0'
;

COMMENT ON TABLE PJVR_MI_PRJ_MBR_UNI IS 'プロジェクトメンバトラン連結ビュー(ver.0.1)';
COMMENT ON COLUMN PJVR_MI_PRJ_MBR_UNI.PRJ_CD IS 'プロジェクトコード';
COMMENT ON COLUMN PJVR_MI_PRJ_MBR_UNI.PRJ_MBR_EMP_CD IS 'プロジェクトメンバ従業員コード';
COMMENT ON COLUMN PJVR_MI_PRJ_MBR_UNI.ROLE IS 'ロール';
COMMENT ON COLUMN PJVR_MI_PRJ_MBR_UNI.VLD_STR_DT IS '有効開始日';
COMMENT ON COLUMN PJVR_MI_PRJ_MBR_UNI.VLD_END_DT IS '有効終了日';

