--ログインユーザの従業員IDと職責を紐付ける
--NextMIへのDBLink

CREATE OR REPLACE VIEW PJVW_SY_SESSION_LNK AS
SELECT SESSION_V.MI_SESSION_ID   AS MI_SESSION_ID
     , SESSION_V.EMP_ID          AS EMP_ID
     , SESSION_V.RES_ID          AS RES_ID
  FROM APPS.XXPJNAVI_EX_IF_SESSION_V@PJLK_NEXTMI SESSION_V
  WITH READ ONLY
;

COMMENT ON TABLE PJVW_SY_SESSION_LNK IS 'セッションマスタビュー(ver.0.1)';
COMMENT ON COLUMN PJVW_SY_SESSION_LNK.MI_SESSION_ID IS 'MIセッションID';
COMMENT ON COLUMN PJVW_SY_SESSION_LNK.EMP_ID IS '従業員ID';
COMMENT ON COLUMN PJVW_SY_SESSION_LNK.RES_ID IS '職責ID';

