-- テーブル用DDL
DROP TABLE XXPJ_SESSION_V CASCADE CONSTRAINTS;

CREATE TABLE XXPJ_SESSION_V
(
    SESSION_ID                     VARCHAR2(100) NOT NULL ,
    EMPLOYEE_ID                    NUMBER(15) ,
    RESPONSIBILITY_ID              VARCHAR2(103)
);
ALTER TABLE XXPJ_SESSION_V ADD CONSTRAINT PK_XXPJ_SESSION_V PRIMARY KEY (SESSION_ID ) ;

COMMENT ON TABLE XXPJ_SESSION_V IS 'PJNaviセッション情報ビュー';
COMMENT ON COLUMN XXPJ_SESSION_V.SESSION_ID IS 'MIセッションID';
COMMENT ON COLUMN XXPJ_SESSION_V.EMPLOYEE_ID IS '従業員ID';
COMMENT ON COLUMN XXPJ_SESSION_V.RESPONSIBILITY_ID IS '職責ID';

--ログインユーザの従業員IDと職責を紐付ける
--NextMIへのDBLink
CREATE OR REPLACE VIEW PJVW_SY_SESSION_LNK AS
SELECT SESSION_V.SESSION_ID           AS MI_SESSION_ID
     , SESSION_V.EMPLOYEE_ID          AS EMP_ID
     , SESSION_V.RESPONSIBILITY_ID    AS RES_ID
--  FROM XXPJ_SESSION_V@PJLK_NEXTMI SESSION_V
  FROM XXPJ_SESSION_V SESSION_V
WITH READ ONLY
;

COMMENT ON TABLE PJVW_SY_SESSION_LNK IS 'セッションマスタビュー(ver.0.1)';
COMMENT ON COLUMN PJVW_SY_SESSION_LNK.MI_SESSION_ID IS 'MIセッションID';
COMMENT ON COLUMN PJVW_SY_SESSION_LNK.EMP_ID IS '従業員ID';
COMMENT ON COLUMN PJVW_SY_SESSION_LNK.RES_ID IS '職責ID';

