-- テーブル用DDL
DROP TABLE XXSCM_EX_IF_SESSION CASCADE CONSTRAINTS;

CREATE TABLE XXSCM_EX_IF_SESSION
(
    SESSION_ID                     VARCHAR2(100) NOT NULL 
);
ALTER TABLE XXSCM_EX_IF_SESSION ADD CONSTRAINT PK_XXSCM_EX_IF_SESSION PRIMARY KEY (SESSION_ID ) ;

COMMENT ON TABLE XXPJ_SESSION_V IS 'セッション管理テーブル';
COMMENT ON COLUMN XXPJ_SESSION_V.SESSION_ID IS 'MIセッションID';

--NextMIで管理しているセッションIDを保持しているテーブルへのDBLink
--※レコード削除可能
CREATE OR REPLACE VIEW PJVW_SY_SESSION_MNG_TBL AS
SELECT IF_SESSION.SESSION_ID AS MI_SESSION_ID
--  FROM XXSCM_EX_IF_SESSION@PJLK_NEXTMI IF_SESSION
  FROM XXSCM_EX_IF_SESSION
;

COMMENT ON TABLE PJVW_SY_SESSION_MNG_TBL IS 'セッション管理テーブルビュー(ver.0.1)';
COMMENT ON COLUMN PJVW_SY_SESSION_MNG_TBL.MI_SESSION_ID IS 'MIセッションID';

