--NextMIで管理しているセッションIDを保持しているテーブルへのDBLink
--※レコード削除可能

CREATE OR REPLACE VIEW PJVW_SY_SESSION_MNG_TBL AS
SELECT IF_SESSION.SESSION_ID AS MI_SESSION_ID
  FROM XXSCM.XXSCM_EX_IF_SESSION@PJLK_NEXTMI IF_SESSION
;

COMMENT ON TABLE PJVW_SY_SESSION_MNG_TBL IS 'セッション管理テーブルビュー(ver.0.1)';
COMMENT ON COLUMN PJVW_SY_SESSION_MNG_TBL.MI_SESSION_ID IS 'MIセッションID';
