-- テーブル用DDL
DROP TABLE PJTM_FW_BUSI_DT CASCADE CONSTRAINTS;

CREATE TABLE PJTM_FW_BUSI_DT
(
    ON_BAT_SEG                     CHAR(2) NOT NULL ,
    BUSI_DT                        DATE NOT NULL ,
    DEL_FLG                        CHAR(1) DEFAULT '0' NOT NULL ,
    REG_USR_ID                     NUMBER(10) NOT NULL ,
    REG_PGM_ID                     CHAR(11) NOT NULL ,
    REG_TS                         TIMESTAMP(3) NOT NULL ,
    UPD_USR_ID                     NUMBER(10) NOT NULL ,
    UPD_PGM_ID                     CHAR(11) NOT NULL ,
    UPD_TS                         TIMESTAMP(3) NOT NULL ,
    VER_NO                         NUMBER(10) DEFAULT 0 NOT NULL
);
ALTER TABLE PJTM_FW_BUSI_DT ADD CONSTRAINT PK_PJTM_FW_BUSI_DT PRIMARY KEY (ON_BAT_SEG ) ;

COMMENT ON TABLE PJTM_FW_BUSI_DT IS '業務日付マスタ(ver.0.3)';
COMMENT ON COLUMN PJTM_FW_BUSI_DT.ON_BAT_SEG IS 'オンバッチ区分';
COMMENT ON COLUMN PJTM_FW_BUSI_DT.BUSI_DT IS '業務日付';
COMMENT ON COLUMN PJTM_FW_BUSI_DT.DEL_FLG IS '削除フラグ';
COMMENT ON COLUMN PJTM_FW_BUSI_DT.REG_USR_ID IS '登録ユーザID';
COMMENT ON COLUMN PJTM_FW_BUSI_DT.REG_PGM_ID IS '登録プログラムID';
COMMENT ON COLUMN PJTM_FW_BUSI_DT.REG_TS IS '登録タイムスタンプ';
COMMENT ON COLUMN PJTM_FW_BUSI_DT.UPD_USR_ID IS '更新ユーザID';
COMMENT ON COLUMN PJTM_FW_BUSI_DT.UPD_PGM_ID IS '更新プログラムID';
COMMENT ON COLUMN PJTM_FW_BUSI_DT.UPD_TS IS '更新タイムスタンプ';
COMMENT ON COLUMN PJTM_FW_BUSI_DT.VER_NO IS 'バージョン番号';

-- ユニークインデックス用DDL

-- インデックス用DDL
