-- テーブル用DDL
DROP TABLE PJTR_FW_INTERJOB_PARAM CASCADE CONSTRAINTS;

CREATE TABLE PJTR_FW_INTERJOB_PARAM
(
    PARAM_KEY                      VARCHAR2(200) NOT NULL ,
    LINE_NO                        NUMBER(6) NOT NULL ,
    PARAM                          VARCHAR2(1000) NOT NULL ,
    DEL_FLG                        CHAR(1) DEFAULT '0' NOT NULL ,
    REG_USR_ID                     NUMBER(10) NOT NULL ,
    REG_PGM_ID                     CHAR(11) NOT NULL ,
    REG_TS                         TIMESTAMP(3) NOT NULL ,
    UPD_USR_ID                     NUMBER(10) NOT NULL ,
    UPD_PGM_ID                     CHAR(11) NOT NULL ,
    UPD_TS                         TIMESTAMP(3) NOT NULL ,
    VER_NO                         NUMBER(10) DEFAULT 0 NOT NULL
);
ALTER TABLE PJTR_FW_INTERJOB_PARAM ADD CONSTRAINT PK_PJTR_FW_INTERJOB_PARAM PRIMARY KEY (PARAM_KEY, LINE_NO ) ;

COMMENT ON TABLE PJTR_FW_INTERJOB_PARAM IS 'ジョブ間パラメータ保持トラン(ver.1.01)';
COMMENT ON COLUMN PJTR_FW_INTERJOB_PARAM.PARAM_KEY IS 'パラメータキー';
COMMENT ON COLUMN PJTR_FW_INTERJOB_PARAM.LINE_NO IS '行番号';
COMMENT ON COLUMN PJTR_FW_INTERJOB_PARAM.PARAM IS 'パラメータ';
COMMENT ON COLUMN PJTR_FW_INTERJOB_PARAM.DEL_FLG IS '削除フラグ';
COMMENT ON COLUMN PJTR_FW_INTERJOB_PARAM.REG_USR_ID IS '登録ユーザID';
COMMENT ON COLUMN PJTR_FW_INTERJOB_PARAM.REG_PGM_ID IS '登録プログラムID';
COMMENT ON COLUMN PJTR_FW_INTERJOB_PARAM.REG_TS IS '登録タイムスタンプ';
COMMENT ON COLUMN PJTR_FW_INTERJOB_PARAM.UPD_USR_ID IS '更新ユーザID';
COMMENT ON COLUMN PJTR_FW_INTERJOB_PARAM.UPD_PGM_ID IS '更新プログラムID';
COMMENT ON COLUMN PJTR_FW_INTERJOB_PARAM.UPD_TS IS '更新タイムスタンプ';
COMMENT ON COLUMN PJTR_FW_INTERJOB_PARAM.VER_NO IS 'バージョン番号';

-- ユニークインデックス用DDL

-- インデックス用DDL
